### ISSUE TITLE
Cloud resources documentation generates false links

### ISSUE THREAD

**Issue by xhochy** [jupyterhub/binderhub#1000]
The documentation about the Helm installation in https://binderhub.readthedocs.io/en/latest/create-cloud-resources.html#initialization creates links that are relative to the binderhub documentation but actually should point to the zero-to-jupyterhub documentation where the helm section is copied from. The link to https://binderhub.readthedocs.io/en/latest/security.html#use-role-based-access-control-rbac goes into nowhere but https://zero-to-jupyterhub.readthedocs.io/en/latest/security.html exists correctly.

**Comment by manics** [comment]
It looks like the docs have been rewritten
