### ISSUE TITLE
Serve UI config from the backend

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#1025]
Following up on https://github.com/jupyterhub/binderhub/pull/1017#issuecomment-561082718. In particular the comment about "reduce duplication".

A possible way to do that which I've seen in other projects is to add an endpoint to the backend from which the UI loads the config. We'd have an endpoint like `binder.example.com/_config` which returns a JSON which is then used to configure the dropdown and labels on the main page.

The endpoint at `/_config` has access to the whole config of the binder hub like for example which repo providers are configured etc.

Things to do if you'd like to work on this or even just make a small prototype to see how it would work:
* add a new endpoint at something like `/_config` that serves up a static config
* add new code  to our JS which loads the config
* transfer the labels currently configured in the JS to the repo provider classes
* modify the `/_config` endpoint to dynamically generate the JSON it serves from the repo provider classes

Addressing the problem that we have some duplication between repo2docker and BinderHub is something I'd tackle in a new PR and not as part of this one.

**Comment by choldgraf** [comment]
I think it's a great idea - you could imagine a BinderHub provider that wants to have a drop-down item that is institution-specific. This could be a way that they can easily configure their hub to do so without needing to fork the BinderHub codebase

**Comment by consideRatio** [comment]
Closing as resolved by #1038!
