### ISSUE TITLE
Launch jupyter-notebook instead of jupyterhub-singleuser

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binderhub#103]
One of the tensions with adopting jupyterhub for binder is that the authentication mechanism used for jupyterhub requires jupyterhub to be installed in the container and to be a compatible version. This is a bit frustrating because the authentication is mostly irrelevant to binder.

jupyterhub-singleuser does two things right now, on top of `jupyter notebook`:

- authenticate with the Hub
- provide links back to the hub

The links back to the hub are actively unhelpful in Binder because they won't work. Authenticating with the Hub is also unnecessary for Binder containers.

If, instead, we launched `jupyter notebook`, we would get rid of all of the problems dealing with matching hub and container versions. This matches the behavior of old binder and makes it much more resilient to version changes (jupyterhub doesn't need to be installed at all).

We could even keep authentication if we require `notebook>=4.3` and launch with `--NotebookApp.token=...`, letting the notebook server authenticate with a token instead of deferring to jupyterhub.

**Comment by choldgraf** [comment]
re: authentication, can't we imagine use-cases where somebody would want authentication with binder? e.g., internal institutional (or company) binder deployments w/ fancier hardware behind them etc?

**Comment by minrk** [comment]
Yes, though that may not end up being related to the authentication of the running notebook container, rather the binderhub service itself.

**Comment by yuvipanda** [comment]
This would definitely solve a lot of problems! But does that mean we get
rid of Jupyterhub completely? Or somehow hack it to make this possible?

**Comment by minrk** [comment]
> But does that mean we get rid of Jupyterhub completely?

With the current design, no. JupyterHub makes no hard assumptions about the servers it starts (Spawners may). We would have to make sure that no jupyterhub-specific CLI args get passed to the subprocess, but that's about it (env can be safely ignored).

As it is now, we have the following assumptions that it is jupyterhub:

- we check for `x-jupyterhub-version` header on start, and warn if it doesn't match. This has no behavioral consequences, though, so is fine.
- The default `get_args()` behavior assumes jupyterhub-singleuser. We'd need to be careful here, when building the CMD to start.

JupyterHub would still launch and manage the container, but KubeSpawner would tell it to run `jupyter notebook` instead of `jupyterhub-singleuser`. All the rest of the info would be the same.

Doing this as an official deployment is baking in some assumptions, both to Binder and JupyterHub:

1. Binder won't ever require software that we install in the image (we can never do this as long as we support user Dockerfiles). That means that Binder can never *rely on* notebook extensions, etc.
2. JupyterHub can never make assumptions about what it spawns (e.g. require webhooks for spawn callbacks, etc.)
