### ISSUE TITLE
https / loading insecure resources in an iframe

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterhub/binderhub#104]
In the xeus C++ kernel, the html mime representation in inspection replies are an `iframe` tag pointing to the location of the requested documentation.

This is what it normally looks like:

![cpp-kernel](https://user-images.githubusercontent.com/2397974/30230613-54361c6c-94e7-11e7-8c55-98a4db090b38.png)

When the connection to the notebook server is over https, the iframe content is not loaded when trying to get content from cppreference, which is served over http.

I am seeing the following error:

![screenshot from 2017-09-08 22-46-14](https://user-images.githubusercontent.com/2397974/30230674-8cb23418-94e7-11e7-8130-c4c30fda132b.png)

However, with documentation coming from readthedocs, which is served over https, we are getting the expected result.

**Comment by yuvipanda** [comment]
I'm not sure if there's any way around this other than reporting it to the people maintaining https://en.cppreference.com/w/. They seem to have a valid HTTPS certificate but have misconfigured their software, hence causing https to not work.

**Comment by SylvainCorlay** [comment]
Thanks. I reported it upstream

For reference
-> https://github.com/p12tic/cppreference-doc/issues/49#issuecomment-328324613
-> http://en.cppreference.com/w/Talk:Main_Page

**Comment by yuvipanda** [comment]
Awesome! Thanks, @SylvainCorlay!
