### ISSUE TITLE
jupyter pods left behind in "Completed" state

### ISSUE THREAD

**Issue by alex-orange** [jupyterhub/binderhub#1040]
Completed jupyter pods (notebooks?) are not getting culled. I'm not sure if these timed out or if I hit the quit button, but it seems that they decided to stop on their own (all fine and good). However nothing seems to be cleaning them up.

```
jupyter-alex-5forange-2dcal-2dion-2ddata-2dbinder-2dajpxbyb3   0/1     Completed   9          46h
jupyter-alex-5forange-2dcal-2dion-2ddata-2dbinder-2dazro0hrt   1/1     Running     0          21h
jupyter-alex-5forange-2dcal-2dion-2ddata-2dbinder-2dr42w76sm   0/1     Completed   0          2d
jupyter-alex-5forange-2dcal-2dion-2ddata-2dbinder-2duetqq755   0/1     Completed   15         47h
```

I'm not even sure which component is in charge of handling such things, so feel free to ask for more info.

**Comment by betatim** [comment]
I've seen this on some clusters as well. I think this is a configuration option for the kubernetes cluster itself. The "Completed" status means the Pod successfully ran to completion and exited. It sticks around so you can inspect it. AFAIK there is an option in k8s that specifies for how long/how many completed pods should exist before they get removed. A completed pod doesn't consume RAM or CPU so I think it is mostly harmless (yet annoying).

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).

**Comment by alex-orange** [comment]
:+1:
