### ISSUE TITLE
Parse mybinder.org URLs into the form fields when pasting on front page

### ISSUE THREAD

**Issue by westurner** [jupyterhub/binderhub#1057]
When I copy a url (e.g. [1]) to the field on https://mybinder.org, JS could fill out the form fields ("Git branch, tag, or commit", "Path to a notebook file (optional)") from the url with a regex that -- IIRC -- is the same for GitLab as for GitHub.

[1] https://mybinder.org/v2/gh/econ-ark/HARK/master?filepath=examples%2FGentle-Intro%2FGentle-Intro-To-HARK.ipynb

**Comment by betatim** [comment]
xref: https://github.com/jupyterhub/binderhub/issues/844 #322

The idea of a smarter text input field is being discussed under the label of "awesome bar": https://github.com/jupyterhub/binderhub/search?q=awesome+bar+is%3Aissue&type=Issues which has a few related issues.

**Comment by manics** [comment]
Closing, see above linked issues
