### ISSUE TITLE
Custom 404 pages

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#106]
Sometimes BinderHub sends you to a page you weren't expecting. In this case, you'll get a generic 404 "does not exist" page. If we could specify a custom 404 that actually printed the path the user tried to access, I think it would help make people realize what's wrong. Many don't think to look at the URL of the resulting page.

**Comment by choldgraf** [comment]
I hear from @yuvipanda that @minrk is doing some work to avoid this problem in the future...so if that happens perhaps we can close this issue

**Comment by yuvipanda** [comment]
I don't think this is relevant anymore.
