### ISSUE TITLE
Q: What repo2docker command should I run locally to do the same thing as mybinder.org?

### ISSUE THREAD

**Issue by westurner** [jupyterhub/binderhub#1060]
What repo2docker command should I run locally to do the same thing as mybinder.org? TBH, this command could be in the footer on mybinder.org.

https://blog.jupyter.org/introducing-repo2docker-61a593c0752d mentions that:

> repo2docker can optionally run a Jupyter server from within the built image, which makes it possible to verify the results of analyses in an environment that was built solely from the configuration files present in the repository.

How do I do this?

Not tangentially, a few weeks ago I put together a few ideas for an 'nbhandler': https://github.com/westurner/nbhandler/issues/1 . Please feel free to steal the name and or the ideas therein:

> Launch a notebook server locally from a link or a downloaded file; like binder for the desktop

**Comment by betatim** [comment]
The command is `repo2docker https://github.com/<org>/<repo>` for the simplest case.

Adding it to the user docs would indeed be a good idea for a PR. Not sure if we can also autogenerate it and where it would be on the landing page of mybinder.org as the form at the top is already super busy and confusing.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/project-jupyter-security-subproject/10175/4
