### ISSUE TITLE
Q: Could BinderHub be modified for local desktop use without k8s?

### ISSUE THREAD

**Issue by westurner** [jupyterhub/binderhub#1061]
Is this the best project for this feature?

- User clicks a URI with a scheme for which a handler has been registered:
  ``nbhandler://`` or ``notebook://`` or ``...``
- Clone the repo to the configured file path
- Launch a notebook server locally from a link or a downloaded file; like binder for the desktop
- If the user doesn't have a `docker` (or `podman`) command available, link them to the install docs
- Open the browser to ``http://{containername}:{jupyterport}/ \<subpath>
  - \<subpath>: see the regex for
    "ENH: Parse [GitHub,] urls into the form fields on paste" #1057

From "Q: What repo2docker command should I run locally to do the same thing as mybinder.org?" https://github.com/jupyterhub/binderhub/issues/1060 :

> Not tangentially, a few weeks ago I put together a few ideas for an 'nbhandler': https://github.com/westurner/nbhandler/issues/1 . **Please feel free to steal the name and or the ideas therein:**
>
>> Launch a notebook server locally from a link or a downloaded file; like binder for the desktop
>
> https://github.com/westurner/nbhandler/issues/1 here:

And I'll just cc from westurner/nbhandler#1:

> Objectives:
> - Launch a notebook server locally from a link or a downloaded file; like binder for the desktop
> 
> Platforms:
> - [ ] Linux
> - [ ] MacOS
> - [ ] Windows
> 
> Workflow:
> - User installs nbhandler
>   - installer installs a URI handler
>   - installer installs an extension handler
> - User configures nbhandler ({Conda||...}, environments directory)
> - User launches a REES spec-compatible repo
>   - User clicks a 'Launch in Binder Desktop' badge link (or similar)
>   - OR, User downloads a .rees (?) file and double-clicks it
> - Browser calls nbhandler with the URI
> - nbhandler creates a {conda,} env
> - nbhandler git clones the repo
> - nbhandler runs binder / repo2docker on the repo
> - nbhandler launches the [cached] built/pulled docker container with a free port
> - browser tab opens
> - user interacts with the docker container
> - user shuts down the container from within jupyterlab
> - user shuts down the container from {nbhandler || docker}
> 
> Products:
> - [ ] nbhandler/main.py
> - [ ] nbhandler/install.py
> - [ ] setup.py
> - [ ] BUILD / Makefile / portable build script
> 
> Questions / Blockers:
> - Could BinderHub be modified to enable simple local desktop installs?
>   - What's a good way to open a window listing the tasks and containers running in BinderHub?
>   - Do I really need k8s and helm to run repo2docker and start and stop local containers?
>     - https://binderhub.readthedocs.io/en/latest/overview.html#what-happens-when-a-user-clicks-a-binder-link
>    - Could I just use buildah to build containers as non-root and podman to run them without an unnecessary docker socket with root access?
> - How to register a file extension handler in Lin/Mac/Win?
> - How to register a URI scheme handler in Lin/Mac/Win/Browser_xyz?
> - Would it be better to just add nbhandler to BinderHub?
>   - Are there other more suitable, maintained, tools that wrap repo2docker?
>     - https://libraries.io/pypi/jupyter-repo2docker/usage lists a few projects it's used by
>       - https://github.com/machine-learning-apps/repo2docker-action is a GitHub Action that runs repo2docker and uploads to dockerhub. This is useful for projects that don't need to be built by end users if there's already an image to just pull

**Comment by betatim** [comment]
This is a cool idea. I think the right place is probably repo2docker and not BinderHub.

The idea of having a webserver running locally that understands binder links (you'd have to replace the hostname with `localhost:8888`) has been floated a few times but as far as I know no prototypes exist. Using a different protocol and registering a handler for it sounds like a smart idea!

**Comment by manics** [comment]
Closing as there's nothing to do here.

**Comment by westurner** [comment]
How is there nothing to do here?

**Comment by manics** [comment]
See the previous comment- this is the wrong repo for this feature.
