### ISSUE TITLE
Unwanted webpack popup on docs page

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/binderhub#1069]
When I open the latest binderhub documentation (https://binderhub.readthedocs.io/en/latest/), first there is an alert saying "hi from webpack" and also style looks different:

![image](https://user-images.githubusercontent.com/6059799/75340681-33c1d800-5893-11ea-8a32-bcddf8c20811.png)

Stable documentation (https://binderhub.readthedocs.io/en/stable/) has no problem.

**Comment by manics** [comment]
https://binderhub.readthedocs.io/en/latest/_static/js/theme.js
Contains this line about 3/4 of the way down
`eval("/*** IMPORTS FROM imports-loader ***/\n(function() {\n\nalert('hi from webpack') ...`

**Comment by manics** [comment]
It's from this theme PR: https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/pull/88/files#diff-3815714ad1e7b52734db844706028cc6R96

**Comment by manics** [comment]
... And deleted in https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/pull/98 so maybe the BinderHub docs just needs a rebuild?
