### ISSUE TITLE
RShiny app with tidytext library 500: Internal Server Error

### ISSUE THREAD

**Issue by supern8ent** [jupyterhub/binderhub#1074]
I noticed rshiny apps that use tidytext don't work on mybinder.org, giving a "500: Internal Server Error" message, so I made a minimal app to demonstrate this:  
https://gitlab.com/nathan.lloyd/shiny-tinytext  
The binder link is  
https://mybinder.org/v2/gl/nathan.lloyd%2Fshiny-tinytext/master?urlpath=shiny  

I also tried this with repo2docker (0.11.0+13.g26542df) and it works fine.

**Comment by supern8ent** [comment]
Interesting note: if I change the keyword to `urlpath=rstudio`, load the project, and run the app, it works.

**Comment by manics** [comment]
If this is still a bug please could you open an issue on https://github.com/jupyterhub/repo2docker ? Thanks!
