### ISSUE TITLE
Exact nature of ephemeral sessions?

### ISSUE THREAD

**Issue by csbrown** [jupyterhub/binderhub#1077]
The docs state:

"""Binder is meant for interactive and ephemeral interactive coding, meaning that it is ideally suited for relatively short sessions. Binder will automatically shut down user sessions that have more than 10 minutes of inactivity (if you leave your window open, this will be counted as “activity”).

Binder aims to provide at least 12 hours of session time per user session. Beyond that, we cannot guarantee that the session will remain running."""

Presumably, any data I have in volatile storage will be lost after some time.  However, it is not entirely clear what this means in the context of non-volatile storage and the Docker image/container.  From other info in the docs, it seems that the image remains.  Does the container remain?  If so, will stuff saved to file remain?  E.g. when the jupyter notebook "autosaves", will that be retained long-term, or is that also lost?

**Comment by manics** [comment]
Binder uses JupyterHub, in particular it incorporates the https://zero-to-jupyterhub.readthedocs.io Helm Chart. This means you're free to choose what happens to containers and data. The default is an ephemeral container, but you can add authentication to JupyterHub/BinderHub, configure permanent storage, and decide whether to keep our delete stopped containers, all in the Z2JH chart.
