### ISSUE TITLE
iframe a binderhub instance?

### ISSUE THREAD

**Issue by csbrown** [jupyterhub/binderhub#1078]
Is it possible to iframe a binderhub instance?

My specific use case is that I am using reveal.js to give a presentation, and would like to simply have a jupyter notebook on one of my slides.  However, I'm getting a "Blocked by Content Security Policy" error.  Possibly there is a jupyterhub config that I can include that will make this work?

To be clear, I am iframing the "sharable" link:  https://mybinder.org/v2/gh/csbrown/cs4all/master?filepath=loops%2Fresources%2Floops.ipynb

**Comment by betatim** [comment]
If you run your own BinderHub instance you can configure the content security policy to allow iframe'ing. I don't think we will allow it on mybinder.org in the near future.

**Comment by tonyphoang** [comment]
I'm interested in creating a website that contains a video + mybinder instance so people can follow along. 

So you're saying the mybinder.org does not allow iframe at all? 
If so, would I just need to create a k8s instance and run my own BinderHub from it? Or more specifically repo2docker which generates a runnable container containing jupyter and a single spawner.  https://github.com/jupyter/repo2docker

**Comment by betatim** [comment]
Hi,

this thread is more of a support question than a technical discussion about how to change the code in this repo. We have recently decided to move all support questions to the forum https://discourse.jupyter.org/ to keep thing streamlined. So a bot will be closing this issue soon.

Please report your question in the forum.
