### ISSUE TITLE
CI tests broken: test_hydroshare_doi

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#1080]
The tests are broken in master, as can be seen here: https://travis-ci.org/github/jupyterhub/binderhub/builds/666475370?utm_source=github_status&utm_medium=notification

```
=================================== FAILURES ===================================
_____________________________ test_hydroshare_doi ______________________________
    async def test_hydroshare_doi():
        spec = '10.4211/hs.b8f6eae9d89241cf8b5904033460af61'
    
        provider = HydroshareProvider(spec=spec)
    
        ref = await provider.get_resolved_ref()
>       assert ref == 'b8f6eae9d89241cf8b5904033460af61.v1565445792'
E       AssertionError: assert 'b8f6eae9d892...1.v1585005408' == 'b8f6eae9d892...1.v1565445792'
E         - b8f6eae9d89241cf8b5904033460af61.v1565445792
E         ?                                     ^  ^^^^^
E         + b8f6eae9d89241cf8b5904033460af61.v1585005408
E         ?                                     ^^^^  ^^
binderhub/tests/test_repoproviders.py:126: AssertionError
```

**Comment by betatim** [comment]
Thanks! That looks like Hydroshare changed something in what the DOI resolves to.

**Comment by betatim** [comment]
@sblack-usu do you have time to look into why the resolved ref of the DOI changed? I looked at https://www.hydroshare.org/resource/b8f6eae9d89241cf8b5904033460af61/ and I can't see anything about versions of the dataset or recent edits that would explain why the resolved ref should have changed.

**Comment by consideRatio** [comment]
@betatim it seems like they use UNIX timestamps, in the error ...v1565445792 is asserted to equal ...v1585005408

Right now it is `1585227781`. So, it seems like the test has asserted something too rigid.

**Comment by sblack-usu** [comment]
@consideRatio is correct, the timestamp check is too rigid in this test as well as the test above.  https://github.com/jupyterhub/binderhub/blob/0a0c0cac40843e3024a80818bd660736a5ca6399/binderhub/tests/test_repoproviders.py#L102

I verified the resource has a modified date of March 23... so at least the timestamp logic works.  I'll submit a PR with a regex comparison on the slug for these two tests.

**Comment by sblack-usu** [comment]
@betatim - would you prefer the comparison to just check with in:
```
ref = await provider.get_resolved_ref()
assert 'b8f6eae9d89241cf8b5904033460af61.v' in ref

slug = provider.get_build_slug()
assert 'hydroshare-b8f6eae9d89241cf8b5904033460af61.v' in slug
```

Or would you like me to import re and check for the 10 digits in the timestamp as well?

**Comment by sblack-usu** [comment]
Just as a note, the resources in these tests are published so the data is immutable.  However, we do still allow some of the metadata to be changed after a resource is published, which is why the timestamp changed.  I did not take that into account updating metadata when writing these tests originally.

**Comment by sblack-usu** [comment]
@betatim Here is the proposed fix.  I'll submit a PR if you approve of this approach.  If you'd rather have me check for the digits of the timestamp with a regular expression instead, I'm happy to make those changes.
https://github.com/sblack-usu/binderhub/commit/85fdfde31ca61d02eac3111d232b3f8528ef3a0c

**Comment by consideRatio** [comment]
@sblack-usu your suggested fix makes sense to me, thanks for helping out resolving this! :heart:

**Comment by betatim** [comment]
Sounds like a reasonable fix :) Thanks for explain how it came about.

**Comment by betatim** [comment]
Merged :)
