### ISSUE TITLE
documentation typo: Installing R packages using install.R

### ISSUE THREAD

**Issue by sje30** [jupyterhub/binderhub#1086]
Hi,
reading over https://mybinder.readthedocs.io/en/latest/sample_repos.html  I notice that in the R section you say:

```

where YYYY-MM-DD is a snapshot at MRAN that will be used for installing LIBRARIES.

You can also have an install.R file that will be executed during build, and can be used to install LIBRARIESl.

```

just a small suggestion: could you change both instances of LIBRARIES above (caps mine for emphasis) to "packages"  -- as this is to install packages into libraries.

**Comment by betatim** [comment]
Sounds like a good thing to do. Do you want to open a PR? The source for that page is https://github.com/jupyterhub/binder/blob/master/doc/sample_repos.md

---

If you are a new/first time contributor: this is a good issue to get started contributing 🎉 Instructions for how to setup sphinx on your local machine to work on the documentation is in https://github.com/jupyterhub/binder/blob/master/CONTRIBUTING.rst. If you have any questions please ask me.

**Comment by sje30** [comment]
Thanks.  Just done, https://github.com/jupyterhub/binder/pull/192

**Comment by GeorgianaElena** [comment]
Closed by https://github.com/jupyterhub/binder/pull/192.
Thanks @sje30! :tada:
