### ISSUE TITLE
UI to show resource usage (e.g. CPU, memory) if limits are set

### ISSUE THREAD

**Issue by manics** [jupyterhub/binderhub#1097]
### Proposed change
Include a component in the default notebook UI that shows when excessive resources are being used.

This came to mind after a question in the UKRSE slack, where it turned out a notebook wouldn't run because it had hit the mybinder memory limit. I think it'd be nice if there was a way to see current resource usage along with the limits.

### Who would use this feature?
- New users to mybinder who aren't aware of the resource limits.
- Existing users who may find it interesting to see the resource consumption of their notebooks

### (Optional): Suggest a solution
It might be enough to include https://github.com/yuvipanda/nbresuse in repo2docker though I'll need to check whether it will correctly show the K8S resource limits. It's also undergoing heavy redevelopment at the moment, especially with regards to jupyterlab.

**Comment by betatim** [comment]
Sounds like a good idea. nbresuse should "just work" (I've used it on z2jh deployments). Do you know if it works with lab as well?

**Comment by jtpio** [comment]
> Do you know if it works with lab as well?

Lab shows the memory usage in the status bar if the `nbresuse` data is available:

![image](https://user-images.githubusercontent.com/591645/81553782-ef1fe600-9385-11ea-8317-c7359b98553e.png)

There are also some alternative frontends using `nbresuse` but displaying the data differently:

- https://github.com/jtpio/jupyterlab-system-monitor
- https://github.com/NERSC/jupyterlab-cpustatus
