### ISSUE TITLE
mybinder fails to build image with nix, complains it needs nix>=2.2

### ISSUE THREAD

**Issue by jboynyc** [jupyterhub/binderhub#1110]
### Bug description

Launching Binder for a repository containing a `default.nix` file, it starts building an image containing nix 2.1.1. Everything seems to go as desired until it gets to step 41/50, when it adds the nixpkgs-unstable channel.

![2020-06-11-133334_818x291_scrot](https://user-images.githubusercontent.com/2187261/84380792-7f488980-abd7-11ea-8385-7f9ec1109379.png)

(Sorry, couldn't copy the text, hence the screenshot.)

After this message, it fails.

#### Expected behaviour

Build image, run `nix-shell`.

#### Actual behaviour

Fails to build image, never gets to the point where it can run `nix-shell`.

### How to reproduce

Try to start Binder using the Github repository jboynyc/textnets or any other that contains `default.nix` and hasn't had an image created for it yet.

**Comment by manics** [comment]
This sounds like a problem with [repo2docker](https://github.com/jupyter/repo2docker/) which is the build tool underlying BinderHub.

Would you mind reopening the issue over there? If you're interested in debugging the problem this is the nix buildpack:
https://github.com/jupyter/repo2docker/tree/master/repo2docker/buildpacks/nix

**Comment by jboynyc** [comment]
Done, thanks!
