### ISSUE TITLE
Improve setup instructions to avoid confusion

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#112]
I'm going to dump a few things that need improving here, per @henchc 's attempt at setting up binderhub...feel free to append chris!

https://binderhub.readthedocs.io/en/latest/setup-binderhub.html

- Make it more clear that you need to have 2 different DNS addresses point to the IP we're setting up

**Comment by henchc** [comment]
"Now find the IP of the nginx-ingress-controller:" should just add "EXTERNAL-IP" for clarification

**Comment by henchc** [comment]
"<the json file from service account>"

this is more difficult than copying and pasting, you have to make sure the JSON can be parsed to yaml, I just made it all one line

**Comment by choldgraf** [comment]
We should also make it really clear that you *need* to have a DNS set up, you can't use IP addresses

**Comment by minrk** [comment]
Closed by #113
