### ISSUE TITLE
CI failure with 429 too many requests to github

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#1131]
The test names test_main_page make a wrb request to GitHub, and the CI system got a 429 error code back which is "too many requests". So, i suspect we may be doing too many calls in general to github in the tests. Perhaps its a one off, but perhaps its noted often before - i dont know.

![Screenshot_20200723-205159](https://user-images.githubusercontent.com/3837114/88326685-96c27880-cd26-11ea-8b01-fd39123f1e2d.png)

**Comment by manics** [comment]
Accidental dupe? https://github.com/jupyterhub/binderhub/issues/1132
