### ISSUE TITLE
docs reference binderhub-deploy

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binderhub#114]
The docs for deploying your own binderhub reference binderhub-deploy, but that repo [is only for deploying mybinder.org specifically](https://github.com/jupyterhub/mybinder.org-deploy/issues/2#issuecomment-330619633). We should update the docs to avoid pulling in binderhub-deploy.

**Comment by choldgraf** [comment]
specifically we should point the links here:

https://github.com/jupyterhub/binderhub/blob/master/doc/setup-binderhub.rst#download-the-helm-chart-and-deployment-repo-for-binderhub

to the new `jupyterhub/binderhub` repo helm chart + support apps. Does that sound right?

**Comment by minrk** [comment]
I think so. The helm-chart here doesn't include things like the support charts for LEGO, etc. so we'll have to figure out where things like that belong if they should be part of public 'roll your own' docs/charts as opposed to mybinder.org-specific.

**Comment by choldgraf** [comment]
I think this has now been addressed, as [this page](https://github.com/jupyterhub/binderhub/blob/master/doc/setup-binderhub.rst#download-the-helm-chart-and-deployment-repo-for-binderhub) no longer points to `mybinder.org-deploy`
