### ISSUE TITLE
c.NotebookApp.extra_static_paths not working on MyBinder

### ISSUE THREAD

**Issue by Senui** [jupyterhub/binderhub#1146]
### Bug description
I am trying to add an extra path for the Jupyter service on MyBinder to find Javascript files. I placed the following content in the file $HOME/.jupyter/jupyter_notebook_config.py of the running Binder instance:

```
scriptdir = '/path/to/my/jsfiles'
c.NotebookApp.extra_static_paths = [scriptdir]
```
These Javscript files are correctly found when using repo2docker (i.e. starting the Jupyter service locally), but on mybinder.org I get the error:

```
GET https://hub.gke.mybinder.org/hub/static/scripts/JSRootCore.js?v=20200826120322 net::ERR_ABORTED 404
```
Where JSRootCore.js is in `scriptdir/scripts`.

The thing I suspect that could cause this issue only on mybinder.org, is the fact that the base URL has an extra /hub/ route, in comparison to how it is locally (http://127.0.0.1:58713/static/).

#### Expected behaviour
I expect the JS files in the paths defined in `c.NotebookApp.extra_static_paths` to be found.

#### Actual behaviour
The expected files are not found. In the browser console, I get a 404 error for requesting a JS file that is located in `extra_static_paths`.

### How to reproduce

1. Create the file content as described in the bug description (I'm doing so in a Dockerfile)
2. Launch the Binder instance on mybinder.org
3. Run a cell that requires a JS file found in `extra_static_paths`
4. Open your browser console and notice a 404 error requesting that JS file

### Your personal set up

 - OS: Linux Ubuntu 18.04 LTS
 - Version: latest jupyter

**Comment by betatim** [comment]
Thanks for reporting this. Can you share a link to a minimal example repository (with a `Dockerfile`) that reproduces this?

The problem is that the JS file is being requested from the wrong URL. It should be something like https://hub.gke.mybinder.org/user/binder-examples-requirements-lboc1j7m/static/tree/js/main.min.js?v=7c0e25cc7282dcba9603c595da332685 - with a username and such in the path.

The thing to investigate is the code that generates the link and what kind of custom things you do in your `Dockerfile`.

**Comment by Senui** [comment]
As I was trying to create a reproducer, I read that the issue I have is actually caused by the library (JSROOT) itself. It relies on requirejs currently to load the Javascript files, and it seems like the issue has recently been resolved: https://github.com/root-project/jsroot/issues/166

I will wait for the release to try it out, but I think we can close this issue for now. If that doesn't solve it I will reopen it. Thanks for having a look @betatim !
