### ISSUE TITLE
Docs for personal BinderHub CORS setup

### ISSUE THREAD

**Issue by ashtonmv** [jupyterhub/binderhub#1150]
### Proposed change
Consolidated documentation for setting up CORS headers on personal BinderHub deployments with helm.

### Alternative options
Leave the documentation as it is - and I will just be grateful for an already awesome tool!

### Who would use this feature?
Anyone wishing to connect to a personal BinderHub deployment via clients that rely on CORS requests, like [Juniper](https://github.com/ines/juniper).

### (Optional): Suggest a solution
My knowledge of CORS headers, etc. is quite limited. But as far as I have pieced together from the MyBinder deployment config/ other Github issues, the following minimal additions must be added to `config.yaml`:

```yaml
binderhub:
  cors: &cors
    allowOrigin: "*"

  jupyterhub:
    custom:
      cors: *cors
```

And I remember reading a comment somewhere from @minrk that only authenticated requests are supposed to work with cors, so maybe the [authentication options](https://binderhub.readthedocs.io/en/latest/authentication.html) should also be added?

If I ever get my own cors setup to work, I would be happy to contribute this section to the documentation myself. Unfortunately, my naive attempts with the above options have failed so far. For reference, I am trying to use juniper on [this page](https://www.michael-ashton.com/pyiron_beta_site/getting-started) to connect to [this binder](https://binder.michael-ashton.com/v2/gh/ashtonmv/pyiron_binder/master). For debugging, the page console is logging connection events as experienced by juniper, which is where I'm seeing the CORS error. I'm not giving up, but maybe someone has some helpful tips in the meantime.

**Comment by TomasBeuzen** [comment]
Just adding my 2 cents here. I am a complete newbie to this as well but I recently added these headers to my config.yaml for a binder hosted on AWS and they worked a charm! I wrote all my steps out in a guide, [here is the section with my config.yaml](https://github.com/TomasBeuzen/binderhub-aws-docs/blob/master/binderhub_AWS_DOCKERHUB.md#4-customize-and-secure-binderhub-) in case it's helpful.

**Comment by ashtonmv** [comment]
Thanks @TomasBeuzen, that did it! I'm pretty sure I just had the yaml nesting wrong. Had I seen your config.yaml this morning it would have saved me quite a few headaches 😅 

So my problem is solved. If you're up for it, I would recommend that you (or I if you don't want to!) make a pull request for the documentation with a small section about CORS and includes your full working config.yaml (probably under Customization, next to the https stuff?)

**Comment by TomasBeuzen** [comment]
Glad I could help! (I also had many headaches trying to sort this out so I know what it's like!). I recently opened #1151 to add some more documentation supporting HTTPS for AWS users. This CORS stuff probably fits pretty naturally into/around that PR so I can include that too. Will link this issue once I open the PR :)

**Comment by betatim** [comment]
Do you want to make a separate PR for the CORS documentation? In general smaller PRs or PRs that touch only one topic are easier and faster to review than bigger ones.

**Comment by TomasBeuzen** [comment]
Sure sounds good
