### ISSUE TITLE
No latest version of binderhub helm chart

### ISSUE THREAD

**Issue by ctr26** [jupyterhub/binderhub#1152]
`helm show chart jupyterhub/binderhub`

Returns:

`Error: failed to download "jupyterhub/binderhub" (hint: running `helm repo update` may help)`

I've opened a sister issue at helmsman because helmsman relies on there being a latest helm chart available.

https://github.com/Praqma/helmsman/issues/512

Would it be possible for binderhub to have a latest version assigned like with jupyterhub?

Best

Craig

**Comment by ctr26** [comment]
Any thoughts on this?

**Comment by consideRatio** [comment]
I know it has been an intentional choice in the past, but I know Helm charts typically has this, so I'm inclined to say it would be fine to package a latest version as well.

**Comment by ctr26** [comment]
How would I get this implemented?

**Comment by consideRatio** [comment]
Whats needed is proper version bumps of binderhub. We now only create pre-releases and the helm chart repo doesnt contain anything else i think.
