### ISSUE TITLE
Binder not opening a specific file when directed to (Jupyter Lab)

### ISSUE THREAD

**Issue by melaniewalsh** [jupyterhub/binderhub#1163]
### Bug description

Binder is not opening a specific file (with Jupyter Lab) when directed to it

Example: https://mybinder.org/v2/gh/melaniewalsh/Intro-Cultural-Analytics/master?urlpath=lab/tree/book/Data-Analysis/Pandas-Basics-Part1.ipynb

#### Expected behaviour

Binder opens a specific file when it is directed to

#### Actual behaviour

Instead Binder opens in the root directory. It looks like at the last second `?clone` is added to the end of the url, which might be the problem?

### How to reproduce

1. Go to this Binder link https://mybinder.org/v2/gh/melaniewalsh/Intro-Cultural-Analytics/master?urlpath=lab/tree/book/Data-Analysis/Pandas-Basics-Part1.ipynb
2. See that it's opening in the root directory (but weirdly if you refresh the page, then the Pandas-Basics-Part1.ipynb file opens)

**Comment by betatim** [comment]
Hi there 👋 !

When I click your link I end up at the following:

<img width="1312" alt="Screenshot 2020-10-06 at 12 45 39" src="https://user-images.githubusercontent.com/1448859/95192053-ee269f80-07d1-11eb-89a0-93f0d9983698.png">

Which looks like it worked. The URL I end up at is https://hub.gke2.mybinder.org/user/melaniewalsh-in-tural-analytics-btp7mufo/lab. Could you post the one you end up? Maybe one of the clusters behind mybinder.org behaves differently, which we could spot from the different hostnames in the URL. I am using Firefox 82.0b3 (64-bit) on OSX and you?

**Comment by melaniewalsh** [comment]
Thanks for trying it out, @betatim! And, yes, it looks like it worked for you. Good to know that it's working correctly sometimes.

I just tried the same link a handful more times, and Binder opened the filepath correctly a couple of times, but it still opened in the root directory at other times.

These are two of the URLS from when Binder opened in the root directory:

- https://hub.gke2.mybinder.org/user/melaniewalsh-in-tural-analytics-4p5vxlda/lab/workspaces/auto-q/tree/book/Data-Analysis/Pandas-Basics-Part1.ipynb

- https://hub.gke2.mybinder.org/user/melaniewalsh-in-tural-analytics-7nivyo39/lab/workspaces/auto-h/tree/book/Data-Analysis/Pandas-Basics-Part2.ipynb

I'm using Chrome Version 85.0.4183.121 (64-bit) on OSX.

**Comment by fm75** [comment]
We have seen this on our instance and noticed that the expected behavior works in Chrome Incognito mode.

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug- it's most likely an issue in JupyterLab. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
