### ISSUE TITLE
Fail to create temporary user - hub readiness probe failed

### ISSUE THREAD

**Issue by ltetrel** [jupyterhub/binderhub#1211]
### Bug description
The user environment won't spawn. The logs says that the docker image is found, but our cluster does not have this image.
After, jupyterhub fails to create the user.

It could be related to this comment: https://github.com/jupyterhub/binderhub/issues/1140#issuecomment-676502803

#### Expected behaviour
Binderhub successfully create a user environment.

#### Actual behaviour
When we describe the hub pod, it shows:
```
Readiness probe failed: Get "http://10.244.1.4:8081/jupyter/hub/health": dial tcp 10.244.1.4:8081: connect: connection refused
```
Why is it pointing to the internal url and not the domain we use in the config ?
And why cannot he connect to the internal url ?

### How to reproduce
Try to build a binderhub instance.

### Your personal set up

 - OS:
 ubuntu 18.04
 - Version:
 v0.2.0-n361.h6f57706
 helm 3.4
 kubectl 1.19.3
 cert-manager 1.0.3
 - Configuration:
```
jupyterhub:
  ingress:
    enabled: true
    hosts:
      - <>
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    https:
      enabled: true
      type: nginx
    config:
      # Allow POSTs of upto 64MB, for large notebook support.
      proxy-body-size: 64m
    tls:
      - secretName: <>-tls
        hosts:
          -<>
  hub:
    baseUrl: /jupyter/
    image:
      name: conpdev/hub-image
      tag: v1.5
  proxy:
    service:
      type: NodePort
  cull:
    timeout: 600
    every: 120
  singleuser:
    memory:
       guarantee: 2G
    cpu:
       guarantee: 1

# BinderHub config
config:
  GitHubRepoProvider:
    banned_specs:
      - ^(?!neurolibre\/.*).*
      - ^ines/spacy-binder.*
      - ^soft4voip/rak.*
      - ^hmharshit/cn-ait.*
      - ^shishirchoudharygic/mltraining.*
      - ^hmharshit/mltraining.*
  BinderHub:
    hub_url: https://<>/jupyter
    use_registry: true
    image_prefix: conpdev/<>-

service:
  type: NodePort

storage:
  capacity: 2G

ingress:
  enabled: true
  hosts:
    - <>
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  https:
    enabled: true
    type: nginx
  config:
    # Allow POSTs of upto 64MB, for large notebook support.
    proxy-body-size: 64m
  tls:
    - secretName: <>-tls
      hosts:
        - <>

**Comment by betatim** [comment]
Could you clarify which hub pod you are describing (JupyterHub or BinderHub?).

A readiness probe is a form of monitoring kubernetes offers. It is configured for a Pod and requests are made from the node that the pod is running on. That is why it uses the internal IP of the pod. This is not something you can change or need to change. The readiness check failing suggests that the hub pod is not ready/crashing/broken.

**Comment by consideRatio** [comment]
> The user environment won't spawn. The logs says that the docker image is found, but our cluster does not have this image.
After, jupyterhub fails to create the user.

This is too vague for me to understand clearly, so it becomes hard to say what's likely causing your experience @ltetrel.

__Generally though__
If you have a readinessProbe failing, debug that first and everything else second.

I would say that a readinessProbe that is failing in the hub pod is very likely a configuration mistake or similarly. The readinessProbe shouldn't be influenced at all by your ingress configuration btw, because it is just between Kubelet running on the k8s node where the pod is scheduled and the k8s pod.

**Comment by ltetrel** [comment]
Thanks for your reply, this is appreciated.

So we are indeed talking about the jupyter hub pod (called `hub-7cd64fdf88-nxz9w` in our cluster).
I don't think it is a configuration issue (at least I would say, it is not the config.yaml) because we already used this configuration before. But just in case I will (re)double check it.
Also do you know why it says (on the binderhub logs output on the main page when building) that the pod image is found but in reality there is no such image? It indeed exists on dockerhub, but not on the cluster. Is it a new behaviour from latest binderhub ?

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
