### ISSUE TITLE
Support for Quay container registry

### ISSUE THREAD

**Issue by amx52** [jupyterhub/binderhub#1217]
Hi,

Currently it seems as though the config does not support the workflow needed to use Quay enterprise container registry as the initial authentication happens via a bearer token and not username/password. Since the token can only be generated manually in the Quay dashboard, there is no way to generate a token with username and password through the API. The workflow for using the API can be found here:
https://docs.quay.io/api/ 

It does seem a bit odd to use a token in order to generate a different access token, but would it be possible to add a bearer token field to the binderhub config?

In addition to this, generating an access token also requires the "title" field in the body.

If this is already supported and I am missing something then I apologize for the suggestion.

Thank you!

**Comment by manics** [comment]
Sorry for the slow response. BinderHub already supports a username/password for authenticating with the container registry:
https://binderhub.readthedocs.io/en/latest/zero-to-binderhub/setup-binderhub.html#create-secret-yaml-file

If you need more help please post on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions 😃
