### ISSUE TITLE
CI: let CodeQL run as a cronjob only?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#1224]
The test suite takes ~4-12 minutes now depending on whats changed, but the Python CodeQL test take ~15 minutes.

I have not seen it fail yet and figured we could perhaps run run only as a cronjob daily instead?

**Comment by betatim** [comment]
The CodeQL test is not correctly configured right now. I think this is why they don't fail. Spending some time to figure out how to get them to run would be nice. Lets see what does to how fast it runs and if we find the output useful.

I think running it only as a cron job means no one will ever look at the output. So I think if we get them to work and find the output useful we should run them on each PR. As far as I understand it the idea of the code scanning is to prevent us from introducing things which are potential security problems. So you want to use it like a unit test that runs for each PR and you only merge if it is green.

**Comment by consideRatio** [comment]
> I think running it only as a cron job means no one will ever look at the output.

I agree it doesn't get much attention then, but if we make it have a badge in the README and run as a dedicated workflow I would care. This is similar to having links becoming broken in docs over time I'd say, and I figure it makes sense to not make PR authors get stuck on that doing unrelated things.

> So I think if we get them to work and find the output useful we should run them on each PR.

I fully agree!

> As far as I understand it the idea of the code scanning is to prevent us from introducing things which are potential security problems. So you want to use it like a unit test that runs for each PR and you only merge if it is green.

I'm not sure at all what it does yet, but I assume it would to a large extent scan existing code based on current knowledge of vulnerabilities, which means that it is likely to also start failing for non-changes by more vulnerabilities become known over time.

**Comment by consideRatio** [comment]
It is not running as a cronjob only, and it leads to results showing up in https://github.com/jupyterhub/binderhub/security/code-scanning.
