### ISSUE TITLE
ci system following two merged PRs get stuck

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#1237]
I merged #1236 and #1235 which both seemed fine to me, but now our tests fail in a new way. Did the combination of these PRs introduce a new bug? I'm clueless.

Test failure: https://github.com/jupyterhub/binderhub/actions/runs/466459518

![image](https://user-images.githubusercontent.com/3837114/103787603-11195780-503e-11eb-9c38-f14bb1807a14.png)

---

From the namespace report, it seems like the binder pod became ready and running though...

```
NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/proxy            1/1     1            1           10m
deployment.apps/user-scheduler   2/2     2            2           10m
deployment.apps/hub              1/1     1            1           10m
deployment.apps/binder           1/1     1            1           10m
```

The actual test seem to be...

```
  . ci/common
  await_binderhub
  echo "curl http://localhost:30901/health" to check BinderHub\'s health
  curl http://localhost:30901/health
```

And the initial output of this test is...
```
deployment "proxy" successfully rolled out
deployment "hub" successfully rolled out
Waiting for deployment "binder" rollout to finish: 0 of 1 updated replicas are available...
deployment "binder" successfully rolled out
curl http://localhost:30901/health to check BinderHub's health
<THIS IS WHERE IT ALL GETS STUCK: in the "curl http://localhost:30901/health" statement>
```

It seems to me that the /health endpoint now fail to respond or perhaps streams a response or similar that is never completed?

**Comment by consideRatio** [comment]
Here is a test run from #1238 that provides more details about the state of things associated with new failure. Nothing seems wrong to me, but I'm not sure what causes the curl request to get stuck.

https://github.com/jupyterhub/binderhub/pull/1238/checks?check_run_id=1657413955

**Comment by betatim** [comment]
I think it has happened before that the `curl` call gets stuck. Restarting the CI run seems to fix it. So I think this is a flakey test/setup kind of issue :-/

**Comment by consideRatio** [comment]
No because the echoed statement is executes

**Comment by manics** [comment]
Is there a potential race condition? Could the check in
https://github.com/jupyterhub/binderhub/blob/f76e37e334e49749bc883eade8ac63da70e4abdb/ci/common#L22
succeed before `/health` and/or the network routing is ready?

**Comment by consideRatio** [comment]
Hmmmm, well there are no readiness probe for the binder deployment apparently, so just attempting to start (having pulled the image etc) will make the rollout status work clear.

**Comment by consideRatio** [comment]
From some experimentation, I found enough evidence to support the idea that @manics guess was correct.

Without a readinessProbe, the following only concludes the binder pod has started, not that it has become ready.
https://github.com/jupyterhub/binderhub/blob/f76e37e334e49749bc883eade8ac63da70e4abdb/ci/common#L22

Due to this, I marked #1242 to close this issue.
