### ISSUE TITLE
JupyterLab Themes

### ISSUE THREAD

**Issue by YeaToast** [jupyterhub/binderhub#1253]
I use JupyterLab in conjunction with GESIS Notebooks, however, when i install extension (theme) @arbennet/base16-nord, and restart the JupyterLab instance, the theme is deleted. I have to installl the theme every bootup, and i can't find a way to automate it (and the rebuild also).
Is there a way that i can make the theme persistent?

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
