### ISSUE TITLE
Install JupyterLab extensions in default build

### ISSUE THREAD

**Issue by ellisonbg** [jupyterhub/binderhub#126]
It would be great if we could install some common JupyterLab extensions in the default binder. Where would we submit a PR to add these? Thanks! @blink1073 @sccolbert

**Comment by ellisonbg** [comment]
The word over on repo2docker is that users can add a bash script called `postBuild` that installed jupyterlab extensions.

**Comment by choldgraf** [comment]
We should add an example the shows this off (yes this is possible and we
want to highlight this kinda stuff!)
