### ISSUE TITLE
Launch binder doesn't work for Dataverse DOI

### ISSUE THREAD

**Issue by atrisovic** [jupyterhub/binderhub#1263]
Hi there!

### Bug description
I created this repository with a Binder badge that worked about a week ago, but it doesn't work anymore. https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/EA3LC5

#### Expected behaviour
It should build and work.

#### Actual behaviour
It doesn't :-(

### How to reproduce

1. Go to https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/EA3LC5
2. Click on Launch Binder
3. Wait

**Comment by Xarthisius** [comment]
It's a regression introduced by https://github.com/jupyterhub/repo2docker/pull/993

Example of why it's happening is here: https://github.com/jupyterhub/repo2docker/pull/993/files#diff-78c5df16e11de88f5f7ad6688a315012698d56db263e9dda580bddf13c51e09fL78-R76

DV responds with `{"data": payload}` and the code used to immediately go one level deep. Now, it's not the case so every `deep_get(data, ...)` is of by a `data.`.
