### ISSUE TITLE
Route added by server extension no longer accessible

### ISSUE THREAD

**Issue by rmorshea** [jupyterhub/binderhub#1264]
I have a Jupyter server extension that adds a custom `_idom_web_modules` route to serve static resources. About a month ago this worked perfectly on Binder (and still works locally in Lab and the Notebook), but it seems like this route has recently started producing a 404 on Binder. Has something changed?

Here's an example of where the route ought to be found:

```
https://hub.gke2.mybinder.org/user/idom-team-idom-jupyter-9h4du6h7/_idom_web_modules
```

Useful links:

- [Binder](https://mybinder.org/v2/gh/idom-team/idom-jupyter/main?filepath=notebooks%2Fintroduction.ipynb) - Run all the code cells in the notebook and you should see the 404 on the console logs after running the last code cell.
- [Repo](https://github.com/idom-team/idom-jupyter) - Source code for the binder link is shown above
- [Server Extension](https://github.com/idom-team/idom-jupyter/blob/main/idom_jupyter/jupyter_server_extension.py) - source code for the server extension that is adding the `_idom_web_modules` route

**Comment by manics** [comment]
Hi! Could you try and reproduce your problem when runing repo2docker locally? Please install from the `master` branch rather than the latest release: https://github.com/jupyterhub/repo2docker

**Comment by rmorshea** [comment]
@manics I can confirm that this issue persists when running under `jupyter-repo2docker` as installed from `master`.

**Comment by manics** [comment]
@rmorshea Thanks for checking. It sounds like this is related to the dependencies that are installed, as opposed to a bug in BinderHub or repo2docker, so I'll close this issue.

Your best option is probably to go through the dependencies (e.g. the version of Jupyter notebook) to try and pin down which change is causing this error. You can also post on the Jupyter community forum https://discourse.jupyter.org/ and cross-reference this issue. Hope this helps you get started!

**Comment by rmorshea** [comment]
@manics I'm not so sure this is related to the version of Jupyter given that I'm able to run this fine locally on the latest version of the Jupyter Notebook and Jupyter Lab. It's something about the deployment environment that is blocking requests to my added route. I can imagine something like a rule in an NGINX server could be to blame.

**Comment by rmorshea** [comment]
Ok, looks like I'd manually enabled my server extension in my local environment by running `jupyter serverextension --enable ...` which placed a config in `~/.jupyter` thus obscuring the fact that my `jupyter_server_config.d` files were not being installed correctly.
