### ISSUE TITLE
JupyterLab related questions

### ISSUE THREAD

**Issue by ellisonbg** [jupyterhub/binderhub#127]
Hi all, we are starting to look at using binder to encapsulate our JupyterLab demos and other JupyterLab related stuff. I have a few questions related to that:

1. As we give talks about JupyterLab, this has the potential to drive non-trivial traffic to beta.mybinder.org. How ready are you for that?
2. Is it possible to specify the initial URL for a repo, so that JupyterLab could open rather than the classic notebook (at the repo's choice)? It is simply `/lab` rather than `/tree`.
3. How willing are the binder folks to coordinate with us on releases so we can have a relatively short time between releasing JupyterLab and it being live on binder?

Thanks for all the awesome work here!

**Comment by ellisonbg** [comment]
Adding @jasongrout and @jzf2101 as this will enable us to move forward with getting the jupyterlab-demo to use binder.

**Comment by yuvipanda** [comment]
(2) should be easily doable, can you open another issue for that?

(3) is 'very' :)

(1) is 'we will find out depending on your timeline'. I'm spending this week on doing operational work on binder, and will have a better understadning of its 'readiness' when I'm done.

**Comment by ellisonbg** [comment]
(2) Done #128 

(3) many thanks - we will be in touch as new releases approach.

(1) we will likely first use this later in October. I am giving a talk at UCSD and would love to try showing JupyterLab running in binder at that point. I don't think that traffic will be too much (maybe dozens of folks). The bigger concern is that someone Tweets about a binder and all of Twitter visits binder. Maybe we could do some deliberate tests when you are ready - have a nice binder ready, Tweet about it and then watch in real time how everything holds up.

**Comment by choldgraf** [comment]
Agree with Yuvi on all points above.

Re: people slamming the servers, it'll probably be OK depending on how
large the crowd, but it is good to keep in mind that the public binder is
not a "one size fits all" kinda setup. Its resources are (intentionally)
limited and is sort of "use at your own risk".

That said perhaps we could make a special case for our jupyter lab
teammates and up the resources that day or something :-)

**Comment by yuvipanda** [comment]
Going to close this as sorted out now :) 

and yes, we're happy to pump up resources for specific time periods. Just give us advance notice!
