### ISSUE TITLE
Mybinder exposes my computers files on the nbviewer

### ISSUE THREAD

**Issue by SilasK** [jupyterhub/binderhub#1280]
### Bug description

I loaded a [GitHub repo](https://github.com/metagenome-atlas/Tutorial) to mybinder.org. 

As usual, while waiting for the building one can look at the files in [nbviewer](https://nbviewer.jupyter.org/github/metagenome-atlas/Tutorial/tree/master/). 

When going to the [enclosing folder in the nbviewer](https://nbviewer.jupyter.org/github/metagenome-atlas/) one has access to all the files in the enclosing folder on my computer. This is a serious security problem!!!

I don't understand how this can happen because the enclosing folder is not loaded in the Github repo. 

I use a [second github repo](https://github.com/metagenome-atlas/BinderTutorial) to build only the conda environment, as suggested elsewhere.

**Comment by manics** [comment]
https://nbviewer.jupyter.org/github/metagenome-atlas/ is a list of the public repos in https://github.com/metagenome-atlas/
