### ISSUE TITLE
image_prefix broken for DockerHub.

### ISSUE THREAD

**Issue by MridulS** [jupyterhub/binderhub#1281]
### Bug description

`image_prefix` for images hosted on DockerHub expects to be of the format `image_prefix: <docker-id OR organization-name>/<prefix>-` but the recent changes in https://github.com/jupyterhub/binderhub/pull/1269 breaks that. The `image_prefix` in case of docker hub only has one `'/'` so it breaks the image name.
``` python
In [38]: image_name = 'orgname/repo:HEAD'

# this is new behaviour 
In [39]: image_name.split('/',1)[-1].split(':', 1)
Out[39]: ['repo', 'HEAD']

# this is old behaviour 
In [40]: '/'.join(image_name.split('/')[-2:]).split(':', 1)
Out[40]: ['orgname/repo', 'HEAD'] 
```

#### Expected behaviour

DockerHub should work as expected.

#### Actual behaviour

Getting `Failed to get image manifest for ......` errors.

### How to reproduce

Go to gesis.mybinder.org and try running a repo twice. (We use DockerHub).

### Your personal set up

 - OS:
 
 - Version(s):
 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by MridulS** [comment]
similar behaviour at turing.mybinder.org (the server doesn't launch but the build pods seems to running and pushing to docker hub without any issues, just tried with https://hub.docker.com/r/turingmybinder/binder-prod-networkx-2dnotebooks-0c9816/)

**Comment by rappertomate** [comment]
The new PR https://github.com/jupyterhub/binderhub/pull/1283 should not let this happen again. See this snippet from the according unit test. Full image name -> image name, tag:
`("jupyterhub/k8s-binderhub:0.2.0-a2079a5", "jupyterhub/k8s-binderhub", "0.2.0-a2079a5")`

**Comment by manics** [comment]
https://github.com/jupyterhub/binderhub/pull/1269 was reverted in https://github.com/jupyterhub/binderhub/pull/1282
Is this still broken?

**Comment by MridulS** [comment]
Yeah it's fixed now. Thanks!
