### ISSUE TITLE
cleaner not mounting the dind socket properly and won't start

### ISSUE THREAD

**Issue by jabbera** [jupyterhub/binderhub#1284]
### Bug description
Image cleaner won't start with when using dind because it's unable to mount /var/run/docker.sock 

The dind socket is located here: 

https://github.com/jupyterhub/binderhub/blob/4b41dc23312b9b1f8ea5cd1434403752632c9644/helm-chart/binderhub/templates/dind/daemonset.yaml#L43

The image cleaner doesn't properly use the hostSocketDir and blindly mounts /var/run/docker.sock  for both dind as well as host docker.

https://github.com/jupyterhub/binderhub/blob/4b41dc23312b9b1f8ea5cd1434403752632c9644/helm-chart/binderhub/templates/image-cleaner.yaml#L44

#### Expected behaviour
image cleaner should start

#### Actual behaviour
image cleaner doesn't start

**Comment by betatim** [comment]
If you are using DIND there should be two image cleaners. One for the host's dockerd and one for the DIND dockerd. The source of the mount is defined towards the bottom of `templates/image-cleaner.yaml`.
