### ISSUE TITLE
Embedding Bokeh server applications in Binder Notebooks

### ISSUE THREAD

**Issue by bisejdiu** [jupyterhub/binderhub#1289]
### Proposed change

I would like to be able to embed bokeh server applications directly in Binder Notebooks, something that is easy to do with locally run notebooks.  

### Alternative options

There is this [example](https://github.com/binder-examples/bokeh) which shows how to run a bokeh server using Binder but, to my understanding, it uses `subprocess.Popen` to execute `bokeh serve` and then redirects to the default 5006 port. My objective, however, is to embed the applications directly inside the notebook. 

### Who would use this feature?

Anyone who uses Bokeh server applications and Binder. I have a few Bokeh server applications that run embedded inside Jupyter Notebooks and  I am currently writing tutorials for these apps and would like to share them using Binder Notebooks. The problem is, this is currently not doable. At least not the same way it works within locally run notebooks. 

### (Optional): Suggest a solution

The solution would (ideally) look quite similar to the following [example](https://github.com/bokeh/bokeh/blob/2.3.1/examples/howto/server_embed/notebook_embed.ipynb) from the Bokeh docs.
The following [Topic](https://discourse.bokeh.org/t/embedding-bokeh-server-applications-in-mybinder-notebooks/7604) discusses this issue with the Bokeh community.

**Comment by manics** [comment]
This is something you should be able to achieve in your notebook container, for example with https://github.com/jupyterhub/jupyter-server-proxy/ or perhaps https://discourse.jupyter.org/t/new-package-to-run-arbitrary-web-service-in-jupyterhub-jhsingle-native-proxy/3493

Please post on the community forum if you need more support.
