### ISSUE TITLE
Handle errors in starting pods

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#131]
Be more robust to failures in starting pods from binder.

**Comment by willingc** [comment]
To add a bit more context to this...

Is this to add more error reporting and automated recovery from errors when creating a [namespaced  build pod](https://github.com/jupyterhub/binderhub/blob/master/binderhub/build.py#L98) via the kubernetes API?

**Comment by yuvipanda** [comment]
It's both:

1. When launching pods to do the builds
2. When launching pods by talking to the hub api to launch user servers

Both these can fail for many reasons, and we should report them back to the user.

**Comment by willingc** [comment]
Add better reporting to the user that the build has failed along with any detail about why the build failed. #149 is a more specific case of this issue.

**Comment by choldgraf** [comment]
It looks like we've got both #149 and #90 improving this. Can we consider this issue resolved?

**Comment by manics** [comment]
No one objected to the last comment, closing.
