### ISSUE TITLE
Binder in iframe

### ISSUE THREAD

**Issue by smithis7** [jupyterhub/binderhub#1312]
### Bug description

When I try to embed binder into an html page with iframe, I am told that binder is not connecting -- this just happens with binder, and not other websites that I embed. This is happening on chrome, using documentation built by sphinx.

I have just used the simple `<iframe src="insert-url-to-notebook"></iframe>`. Am I able to embed binder in a webpage? If so, how, and if not, why?

**Comment by manics** [comment]
Sorry for the slow response. You'll need to edit the tornado settings to allow embedding as an iframe. I'm not sure of theconfig but there are a few examples on the [community forum](https://discourse.jupyter.org/) which is also the best place to go for help.
