### ISSUE TITLE
Automating build fails from GitLab.com repo

### ISSUE THREAD

**Issue by adamivisonnhs** [jupyterhub/binderhub#1313]
I run coffee and coding sessions where we utilise Binder for a small group of 15-30 learners. I am trying to use commits to master as a trigger for an initial binder build / launch to automate the first build to ensure everything is always up to date and opens without the first build delay.

We are forced to host in GitLab.com and you can find the repo [here](https://gitlab.com/nhsbsa/insight/shared/coffee-and-coding).

Upon running `.gitlab-ci.yml` and invoking `trigger_binder.sh`, the response is:

![image](https://user-images.githubusercontent.com/66741381/123287959-0e84be80-d507-11eb-9987-2458416cc274.png)

Although it looks like the CI passes it doesn’t, as the build is blocked due to the GitLab CI coming from Google Cloud (I guess)?.

Is there a fix for this or another way I can automate this?

Cheers,

Adam

**Comment by manics** [comment]
This is being handled on https://discourse.jupyter.org/t/mybinder-org-blocking-launches-originating-from-most-cloud-providers/8094/2
