### ISSUE TITLE
Launch server & wait for completion as part of eventstream

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#133]
Right now, we wait for the event stream to finish, and then redirect the user to a separate 'redirect' url that does the launching of the server and waiting for it to start & then redirecting.

Instead, we should do that as part of the eventstream itself.  It should just return the url + token at the end. Then the mybinder.org frontend code should be able to read that and construct appropriate URL to redirect to.

This way, other third party code can easily get the token + URL and use it as it sees fit.

**Comment by minrk** [comment]
#135 implements this and a Python example for launching via the API

**Comment by willingc** [comment]
@minrk @yuvipanda Did #135 resolve this issue fully?

**Comment by minrk** [comment]
yup, forgot to auto-close
