### ISSUE TITLE
Not being able to use Sudo without password

### ISSUE THREAD

**Issue by AyaanZaveri** [jupyterhub/binderhub#1333]
## Is there a default password for **root**?

It says:
```
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

**Comment by manics** [comment]
Hi! There isn't a default password. If you want to find out more on customising your images see the repo2docker docs: https://repo2docker.readthedocs.io/en/latest/config_files.html

If you need more help please start  topic on the [Jupyter community forum](https://discourse.jupyter.org/) instead. Thanks!
