### ISSUE TITLE
Update helm linter to accept .Values.service.loadBalancerIP

### ISSUE THREAD

**Issue by Forzzark** [jupyterhub/binderhub#1378]
The helm templates accept specifying the `loadBalancerIP` for helm-chart/binderhub/templates/service.yaml, but the helm values schema in values.schema.json doesn't allow it.

**Comment by consideRatio** [comment]
:tada: thanks for catching this!!! I'll fix it

**Comment by Forzzark** [comment]
Thanks for the quick response. If you can point me to the fix once that's ready I'll appreciate it
