### ISSUE TITLE
Add a "pause" button to build page

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#141]
My problem: didn't remember to copy the text for the badge the first time I built a container, and then every time I visit https://beta.mybinder.org/v2/gh/wildtreetech/epfl-osip-2017/master the container is launched so quickly that I didn't have time to copy the badge stuff from the dropdown.

Maybe the solution is to have a button to "pause auto launch"? I also tried to go back to the page to then edit the branch name, kind of using it as a template, but again ... got auto launched into the container :)

**Comment by choldgraf** [comment]
What about a "launch=false" rest param? And if "launch=true" then it just
fills in the fields but doesn't launch.

**Comment by choldgraf** [comment]
@betatim now that the URL is auto-generated as you type, do you think that this UI is still necessary?

Alternatively, maybe we can re-purpose this issue to match our discussions around the new behavior on the build page. Namely, don't launch it automatically anymore now that users won't hit this page when they click a binder link.

**Comment by willingc** [comment]
I would recommend closing this issue as I think we have resolved @betatim's initial concern. We can always open a new issue with more specific next generation UI enhancements.

**Comment by yuvipanda** [comment]
+1 to @willingc :) (I also think we should continue auto-launching :D)
