### ISSUE TITLE
If a build fails, binderhub still tries to launch

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#144]
If a repo fails to build for some reason, binderhub will fail for the user and be ok. However, it'll still try to launch the user notebook, which will fail with an ImagePullBackoff.

**Comment by yuvipanda** [comment]
This can be reproduced with binder-examples/requirements repo at 7e367f1

**Comment by minrk** [comment]
This doesn't happen on beta right now, or local testing with master. Is this fixed?

**Comment by yuvipanda** [comment]
I can see a lot of ImagePullBackoffs in beta right now because of this.

**Comment by yuvipanda** [comment]
@minrk yeah, it's what @choldgraf points to. repo2docker can emit a 'failed' message, but the pod will still mark as 'succeeded'. In this case, we no longer launch. I needed it for metrics since I was splitting by 'success' and 'fail'

**Comment by minrk** [comment]
Thanks for finding it! I just couldn't see it.
