### ISSUE TITLE
better errors when the pod doesn't start

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binderhub#149]
When a pod fails to start, often there is useful log output, accessible from `kubectl logs user-pod...`. It can be simple permission issues, etc. in a custom dockerfile. It would be useful if we could relay this info to the eventstream for the failure, rather than just saying "it didn't start".

**Comment by choldgraf** [comment]
hmm - are you thinking just auto-call `logs` on a pod in any failed state and display it in the log? Seems reasonable to me.

**Comment by willingc** [comment]
@minrk I'm going to close this as a duplicate and more specific case of #131.
