### ISSUE TITLE
Failure to push an image to a registry isn't always detected as an error

### ISSUE THREAD

**Issue by manics** [jupyterhub/binderhub#1524]
### Bug description

If the repo2docker build pod builds an image but can't push it to the registry this should be detected as a failure. However sometimes BinderHub doesn't detect the error, and instead proceeds to attempt to launch the image as if it had been pushed.

#### Expected behaviour

Failure to build or push a repo to a container registry should result in BinderHub returning an error, and not attempting to launch the image in JupyterHub

#### Actual behaviour

Sometimes the push fails, but BinderHub still attempts to launch the image. JupyterHub fails since the image wasn't pushed.

### How to reproduce

This is an intermittent bug, I haven't figured out how to reproduce it reliably. I've experienced it with Docker Hub, and it sounds like this has occurred in https://discourse.jupyter.org/t/eks-binder-fails-to-build-repo/15287/6

**Comment by sharmadhiraj86** [comment]
Hii @manics, I want to work on this issue. Can you please assign this issue to me?

**Comment by consideRatio** [comment]
Hi @sharmadhiraj86, thats great!!

I'm not sure, but I think this may have been resolved by #1525. @manics what do you think?
