### ISSUE TITLE
Binder badge dropdown box vanishes upon clicking

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#158]
Right now when you click the dropdown arrow the box correctly pops up with the various binder badge buttons. When you click on one of the options, a window pops up with the text you need to copy. However, this window will vanish any time you click on it making the text impossible to copy. See GIF for demo.

![binder](https://user-images.githubusercontent.com/1839645/31156486-8cac7a74-a869-11e7-8c66-7189343c85e6.gif)

**Comment by nthiery** [comment]
+1
On my firefox, I manage to copy the link by draging the mouse over it, but it's rather inconvenient. I guess a "copy to clipboard" approach would be more convenient.

**Comment by choldgraf** [comment]
this will be closed by #220 (I think)

**Comment by nthiery** [comment]
I confirm copy-pasting is now easy. Thanks a lot!

**Comment by choldgraf** [comment]
hooray! thanks for bringing this up!
