### ISSUE TITLE
route to offlinenotebook

### ISSUE THREAD

**Issue by dg-data** [jupyterhub/binderhub#1604]
### Bug description
jupyter-offlinenotebook extension fails to initialize

### How to reproduce

(https://mybinder.org/v2/gh/rwcitek/MyBinder.dockerfile/HEAD?urlpath=offlinenotebook%2Fconfig)
results to 404 error
Using other github repos, without a Dockerfile to build from, I can save notebooks to browser storage.  
### Your personal set up

 - OS: windows 10
 
 - Version(s):
 
Opera 94.0 browser

**Comment by manics** [comment]
jupyter-offlinenotebook isn't installed in your Dockerfile:
https://github.com/rwcitek/MyBinder.dockerfile/blob/main/Dockerfile

If you need more help please use the Jupyter community forum https://discourse.jupyter.org/

**Comment by dg-data** [comment]
According to [this post](https://discourse.jupyter.org/t/getting-your-notebook-after-your-binder-has-stopped/3268), installation of the extension is **automatic**.

> We have added a few new buttons to the toolbar of the notebook on [mybinder.org](http://mybinder.org/)
It will be automatically installed when you (re)build your repository.
Try it out with one of our [demo repositories](https://mybinder.org/v2/gh/binder-examples/conda_environment/master?filepath=index.ipynb).

In that demo repo the extension neither installed in an explicit way.
In the repo with Dockerfile, Jupyterlab shows the extension as installed and enabled, but the server side is not working.
