### ISSUE TITLE
Dataverse test failure in main branch

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#1614]
Is this failure just tests being outdated, or indicative of a malfunction in the dataverse repoprovider?

Recent [main branch test failure](https://github.com/jupyterhub/binderhub/actions/runs/3837733452/jobs/6533372219#step:29:279):

![image](https://user-images.githubusercontent.com/3837114/210562232-ffad6e00-301c-4ccb-b656-749c05e98a6e.png)

**Comment by pdurbin** [comment]
As I [mentioned](https://github.com/jupyterhub/binderhub/pull/1615#discussion_r1061960340) in the PR, I published a new version of that https://doi.org/10.7910/DVN/TJCLKP dataset yesterday, bumping it from version 3 to 4. I didn't realize tests were hard coded to version 3.
