### ISSUE TITLE
requirements.txt not found

### ISSUE THREAD

**Issue by theanoli** [jupyterhub/binderhub#163]
Hi All, 

I'm trying to build a notebook that uses pandas. I have a requirements.txt file in the same directory as the notebook; it includes the following line: 

`pandas==0.19.2`

...along with a bunch of other stuff. However, when I build the repository in GitHub, it doesn't seem to find the requirements.txt file. If I try to `import pandas` in my notebook, I get an `ImportError`. Looking at the log, requirements.txt isn't touched at all, as far as I can tell. 

Any thoughts on what is going wrong? Am I putting requirements.txt in the wrong place?

Thanks, 
Theano.

P.S. Thanks for building a super-useful tool, I'm really glad to have found it!

**Comment by choldgraf** [comment]
hey - can you send a link to your repo?

**Comment by theanoli** [comment]
Sure: https://github.com/theanoli/tsch

The notebook is in mininetpipe/, in the master branch.

**Comment by choldgraf** [comment]
ah - requirements.txt (and any other build files) need to be either:

1. In the root of the repository
2. In a folder called `binder`, which itself is in the root of the repository.

try thta

**Comment by theanoli** [comment]
That did it. I somehow glossed over that point in the instructions. Thank you!

**Comment by choldgraf** [comment]
no problem! closing this issue :-)
