### ISSUE TITLE
Jupyter Server support

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binderhub#1634]
### Proposed change

Recent JupyterLab, and a growing number of extensions require the newer Jupyter Server, and will no longer run on the legacy `jupyter-notebook` server. But BinderHub (without auth) hardcodes the launch command as `jupyter-notebook`, and there's no way for repos to opt-in to the current standard Jupyter server (except by [redefining `jupyter-notebook`](https://github.com/jorgensd/dolfinx-tutorial/pull/113)).

At this point, I think we should switch to launching jupyter-server by default, which I think will be more compatible more often, but is a backward-incompatible change for _some_ repos, especially those that may have old server extensions. In a _binder_ context, I think there are far more lab extensions than classic nb extensions, so I think at this point it will result in _fewer_ broken repos, not more. But it's still a breaking change since which repos are broken will _change_.

xref https://github.com/jupyter-server/jupyter_server/issues/1038

### Alternative options

Make this an option somehow, and possibly opt-in (eventually, it has to be opt-out since we're currently defaulting to a deprecated package that already doesn't work with the current version of our default UI). I don't know where to express that., though, in a way that's going to work.

### Who would use this feature?

Everyone who wants to use recent JupyterLab or any other Jupyter frontends other than `notebook<7`.

### (Optional): Suggest a solution

Add to our launch command `jupyter-server` _by default_ with a fallback on `jupyter-notebook`. We could gate this on the presence of Jupyter Server 2.0, because Jupyter Server 1.0 _tends_ to be compatible with the legacy notebook server. This decision isn't really made by the user though, it's made for most repos by the repo2docker base env. And I think it would be pretty weird to say 'if you want to launch the old jupyter-notebook, install jupyter-server<2.'

**Comment by mathbunnyru** [comment]
I think this is the reason why https://mybinder.org/v2/gh/jupyter/docker-stacks/main?urlpath=lab/tree/README.ipynb is broken for `jupyter/docker-stacks` project after a recent update.

**Comment by mathbunnyru** [comment]
I hope it will be fixed after a merge :)

**Comment by mathbunnyru** [comment]
<img width="1470" alt="Screenshot 2023-02-28 at 17 11 25" src="https://user-images.githubusercontent.com/12270691/221864070-5e6c249d-5148-4325-bae5-31d765693938.png">

It doesn't work for me :(
Launch url: https://mybinder.org/v2/gh/jupyter/docker-stacks/main?urlpath=lab/tree/README.ipynb
Project: https://github.com/jupyter/docker-stacks

**Comment by manics** [comment]
@mathbunnyru It's fixed in BinderHub, but it's not yet deployed to mybinder.org

**Comment by mathbunnyru** [comment]
Thank you @manics. I thought it was deployed automatically after GitHub push. Could you please ping me when it will be deployed?

**Comment by manics** [comment]
@mathbunnyru Since it's a potentially disruptive breaking change it'll be announced on Discourse.

**Comment by minrk** [comment]
@mathbunnyru this has been deployed to mybinder.org now

**Comment by mathbunnyru** [comment]
@minrk, thank you. I've updated the image and confirm it works well 👍

**Comment by mathbunnyru** [comment]
It seems to be a bit slow to start, though.
