### ISSUE TITLE
BinderHub fails with internal server error if repo2docker produces non JSON output

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#164]
Due to a broken docker image, repo2docker produced the following stdout output:

```
/ # jupyter-repo2docker https://github.com/yuvipanda/example-requirements --json-logs
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-repo2docker", line 11, in <module>
    load_entry_point('jupyter-repo2docker==0.4.1', 'console_scripts', 'jupyter-repo2docker')()
  File "/usr/local/lib/python3.6/site-packages/repo2docker/__main__.py", line 6, in main
    f.start()
  File "/usr/local/lib/python3.6/site-packages/repo2docker/app.py", line 309, in start
    checkout_path
  File "/usr/local/lib/python3.6/site-packages/repo2docker/app.py", line 95, in fetch
    capture=self.json_logs):
  File "/usr/local/lib/python3.6/site-packages/repo2docker/utils.py", line 12, in execute_cmd
    proc = subprocess.Popen(cmd, **kwargs)
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'
```

BinderHub then tried to parse this as JSON, choked and produced an 'internal server error' that isn't very useful.

This is what caused https://github.com/jupyterhub/mybinder.org-deploy/pull/52 to fail

**Comment by yuvipanda** [comment]
I'm still unsure why / how it worked on staging tho.

**Comment by choldgraf** [comment]
I thought that this broken r2d image had been fixed,  but I'm getting the same server error when trying to build this repo:

https://github.com/binder-examples/latex

Note that this doesn't happen for all repos (it built a repo with *just* requirements.txt fine)

**Comment by choldgraf** [comment]
ah after trying it locally with r2d I see it is in fact the same problem...per https://github.com/jupyter/repo2docker/pull/85 we're raising an error if postBuild isn't executable, but we still don't have the pieces in place to grab this information and display it to the user

**Comment by choldgraf** [comment]
Now I'm getting this strange error, it detects `postBuild` and then tries to run it, but when it does it can't seem to find the file

![image](https://user-images.githubusercontent.com/1839645/31288017-2b892b14-aa78-11e7-821d-b64cf1dcbcc2.png)

**Comment by yuvipanda** [comment]
We need a two pronged approach here:

1. Make sure that all output from repo2docker is JSON, without exception. Any exception thrown should probably result in a 'failed' message.
2. Make sure we handle non-json output properly anyway.

I'll open an issue in the repo2docker repo.

**Comment by yuvipanda** [comment]
https://github.com/jupyter/repo2docker/issues/91 is the issue in repo2docker.

**Comment by minrk** [comment]
https://staging.mybinder.org/v2/gh/minrk/junk/bad-post-build to see one of the examples where there was an error due to non-json output before.
