### ISSUE TITLE
ci: indentation failure - why!?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#1701]
We error in the k8s 1.26 / main test, because the built pod can fail to startup because of an indentation error in `singleuser.cmd`.

![image](https://github.com/jupyterhub/binderhub/assets/3837114/c6b6a4bb-1f5b-44f2-82ed-495732a8811c)

But we don't have an indentation error in the provided config:

https://github.com/jupyterhub/binderhub/blob/9cdae11b6671d87b4355534d3edeedfac0a26774/helm-chart/binderhub/values.yaml#L213-L231

Yet we have it [in the pod based on k8s namespace report](https://github.com/jupyterhub/binderhub/actions/runs/5042805566/jobs/9043834434?pr=1697#step:34:184):
![image](https://github.com/jupyterhub/binderhub/assets/3837114/933226ea-5fc5-4c72-aed9-cdc4e85b5d9e)

---

Is the singleuser.cmd processed in any way by us or `helm` making this happen? Is variable expansion involved adding a space or similar?

**Comment by manics** [comment]
It's fine on main
https://github.com/jupyterhub/binderhub/actions/runs/5045025696/jobs/9048789662
Does it happen everytime on https://github.com/jupyterhub/binderhub/pull/1697 ?

**Comment by consideRatio** [comment]
I think so, it mayyyyyy be related to rebuilding the image if its failing there, which makes chartpress do things it otherwise may not do.

**Comment by consideRatio** [comment]
Okay this is what goes wrong:

https://github.com/jupyterhub/binderhub/blob/2b824a55f4193f5a47c4d150dbe7bb89277a3b68/testing/local-binder-k8s-hub/install-jupyterhub-chart#L38-L39

Apparently this file dump doesn't represent the original YAML content.

**Comment by consideRatio** [comment]
From the binderhub repo's folder, this returns weird indentation.

```python
    import os
    from ruamel import yaml

    with open(os.path.join("helm-chart", "binderhub", "values.yaml")) as values_in:
        read_values = yaml.safe_load(values_in)
    
    print(read_values["jupyterhub"]["singleuser"]["cmd"][2])
```

**Comment by consideRatio** [comment]
Reading, writing, and then makes it reproduce the issue:

```python
import os
from ruamel import yaml

with open(os.path.join("helm-chart", "binderhub", "values.yaml")) as values_in:
    read_values = yaml.safe_load(values_in)
print(read_values["jupyterhub"]["singleuser"]["cmd"][2])

with open("dump.yaml", "w") as values_out:
    yaml.safe_dump(read_values["jupyterhub"], values_out)

with open("dump.yaml") as values_in_again:
    read_values = yaml.safe_load(values_in_again)
print(read_values["singleuser"]["cmd"][2])
```
