### ISSUE TITLE
Source file of docs/source/_static/images/architecture.png

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/binderhub#1706]
@consideRatio do you have the SVG file of [docs/source/_static/images/architecture.png](https://github.com/jupyterhub/binderhub/blob/main/docs/source/_static/images/architecture.png)?

**Comment by minrk** [comment]
It's made in Google Slides: https://docs.google.com/presentation/d/1t5W4Rnez6xBRz4YxCxWYAx8t4KRfUosbCjS4Z1or7rM/
