### ISSUE TITLE
CORS is not enabled for BinderHub API

### ISSUE THREAD

**Issue by SamLau95** [jupyterhub/binderhub#177]
I'd like to use BinderHub's API to start kernels from another webpage.

When trying to start a notebook server using the BinderHub API, the browser will error because the Access-Control-Allow-Origin HTTP header is missing.

![screenshot 2017-10-05 19 48 03](https://user-images.githubusercontent.com/2468904/31328265-da7a66a8-ac88-11e7-9eec-ee12b9374336.png)

I believe this should be a simple implementation of [`set_default_headers`](https://stackoverflow.com/a/35259440) in the `base.py:BaseHandler` class but I'm still trying to get binderhub set up locally so I can't test it myself.

In addition, the current release of `notebook` (5.1.0) is missing a header that allows starting kernels from another domain. I fixed it in https://github.com/jupyter/notebook/pull/2876 but is there something we can do to get the fix in for the current deployment of Binder?

Happy to talk more about this (in person works too).

Related to #13.

**Comment by minrk** [comment]
Now that tokens are enabled, we no longer need to relax CORS restrictions. When you access a notebook server via Binder, a token will be given to you, and that should be used to authenticate requests. Token-authenticated requests are not affected by CORS restrictions.

Here is [a Python example](https://gist.github.com/minrk/1fdc9786a5852584854b7c3f548fa0c9) extending the binder-api example in this repo that requests a kernel and runs code using the token without any relaxation of CORS restrictions.

I'd love to have a javascript example that does the same thing using the JupyterLab js.

**Comment by minrk** [comment]
Having done some browser testing, I think I've misunderstood some of how browsers implement CORS.  Using tokens bypasses the *server-side* CORS check, which allows scripted access to the resources. However, it doesn't bypass the origin checking that happens in the browser.

I've opened https://github.com/jupyter/notebook/pull/2920 to make default notebook server behavior what I thought it already was.

#180 should restore CORS access in general on Binder, but only for authenticated requests, as it should be.

**Comment by SamLau95** [comment]
It looks like #180 restores CORS access to the notebook server, but from what I understand there are two steps in starting kernels using the BinderHub API:

1. Make an EventSource request to `https://beta.mybinder.org/build/<provider>/<spec>`
2. Once a `ready` event is emitted by the EventSource, we have a running notebook server and a token to access it. Now we can use the `Kernel` api in `@jupyterlab/services` to start a kernel on the notebook server.

Correct me if I'm wrong, but it looks like #180 allows CORS for 2. while we still need to allow CORS for 1.

**Comment by minrk** [comment]
@SamLau95 you are 100% correct

**Comment by minrk** [comment]
#182 enables CORS on BinderHub itself, with some questions about how exactly we should be doing it.

**Comment by minrk** [comment]
@SamLau95 CORS should be deployed to beta.mybinder.org now.

**Comment by SamLau95** [comment]
Thanks @minrk!
