### ISSUE TITLE
BinderHub overview meeting notes

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#183]
@mpacer @Carreau @yuvipanda @ian-r-rose @jzf2101 do we want to synthesize the BinderHub meeting notes at all? Here's a link:

https://hackmd.io/MwMwJgTGDGBsBGBaYsIkQFmsADIghuAByIQCmZGMYAjDQJwhlA==

**Comment by choldgraf** [comment]
Closing this as there doesn't seem to be anything actionable from it

**Comment by Carreau** [comment]
Sweet thanks !

**Comment by Carreau** [comment]
Oh, I misread, though it was notes from this week meeting. :-( sad now.

**Comment by choldgraf** [comment]
we didn't have a meeting this week!
