### ISSUE TITLE
Autodetect repo to launch based on HTTP referer

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#1860]
Given https://github.com/jupyterhub/binderhub/pull/891 has been in draft for a few years, I wanted to memorialize the feature it is trying to add in this issue so we can close the PR.

We could add an `/autodetect` endpoint that would detect the URL to launch based on the referer, and redirect the user to the correct full URL.

However, I think there's been some changes in which links get `Referer` passed and which don't in the last few years, so I'm not sure what the feasibility of this is.

**Comment by manics** [comment]
I don't think it's worth doing any more. Browser security and anti-tracking protections have increased a lot to the point where it wouldn't be reliable. 

Auto detecting a pasted URL is nice though (covered in another issue).
