### ISSUE TITLE
launch timeout for large images

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binderhub#187]
We've seen timeouts waiting for launch with two causes recently:

1. when the server is under too much load and there are a lot of Pending pods
2. when the image is large and the pull takes a while

The latter is caused because the launch timeout is short - about 80 seconds right now, and a few large images take longer than that to pull to the node. Upping that limit would help. The former could perhaps be alleviated by setting a maximum concurrent servers limit in the Hub (we can only handle ~100 user pods right now, based on memory limits). 

I think there is a bug somewhere, though, that's causing launches to be retried infinitely under certain circumstances. When binder is under load, there seems to be a feedback loop causing many additional launches to be attempted, which ultimately makes matters worse. This will happen, for instance, if an eventstream reconnects on failure instead of closing. I haven't been able to trigger it myself, though. This could potentially be alleviated in KubeSpawner by deleting pods when spawn fails due to a timeout. Right now, they are never killed and the pod will wait forever and eventually start (and never be stopped because KubeSpawner has detached from it after giving up due to the timeout).

**Comment by willingc** [comment]
@minrk For item 1, GitHub's service degradation today coincided with the spike in pending pods. Could be a coincidence or a cascade effect.

**Comment by willingc** [comment]
@minrk @yuvipanda @choldgraf Can this be closed?
