### ISSUE TITLE
how to run `/testing/k8s-binder-k8s-hub` using k8s

### ISSUE THREAD

**Issue by otary** [jupyterhub/binderhub#1896]
### Bug description

how to run `/testing/k8s-binder-k8s-hub` using k8s？I am a beginner and I sincerely need help.

**Comment by manics** [comment]
https://github.com/jupyterhub/binderhub/tree/main/testing/k8s-binder-k8s-hub is mostly for our GitHub CI https://github.com/jupyterhub/binderhub/blob/main/.github/workflows/test.yml

If you just want to install BinderHub please see https://binderhub.readthedocs.io/en/latest/zero-to-binderhub/index.html
