### ISSUE TITLE
Figure out a local setup / testing solution for Binder

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#19]
So people can use this for local development as well, not just for use on binder.

**Comment by choldgraf** [comment]
Hmmm, this is gonna require people to use kubernetes locally isn't it?

**Comment by yuvipanda** [comment]
Nope. Shouldn't. Only the distributed building part requires kubernetes​ :)
the building only requires docker

On May 21, 2017 5:06 PM, "Chris Holdgraf" <notifications@github.com> wrote:

Hmmm, this is gonna require people to use kubernetes locally isn't it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yuvipanda/builderhub/issues/19#issuecomment-302972610>,
or mute the thread

**Comment by choldgraf** [comment]
this is handled by repo2docker now, yeah? can we close this?

**Comment by yuvipanda** [comment]
@choldgraf nah, this is for testing binderhub locally, which we have instructions for now in CONTRIBUTING.md
