### ISSUE TITLE
Badge hard to copy

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/binderhub#195]
The dropdown get dismissed on mouse-button-up event. So you can't Ctrl-C.

**Comment by Carreau** [comment]
Also the link is not generated correctly (is `null`) if you click on the arrow directly after pasting the URL. The URL is likely generated on focus-in/focus-out.

**Comment by choldgraf** [comment]
yeah this UI bug kinda kills me...it's super frustrating when you try to copy a link :-/

**Comment by willingc** [comment]
@Carreau do you want to do a PR for the fix?

**Comment by choldgraf** [comment]
I may have fixed it in #220 ! (I say "may" because I have no confidence in my javascript skills)

**Comment by yuvipanda** [comment]
Fixed.
