### ISSUE TITLE
Feature request: Support for launching binders to different launch environment

### ISSUE THREAD

**Issue by edwins** [jupyterhub/binderhub#204]
This is a feature request more for the public mybinder site.

Currently, when a user clicks on the "launch" button, binder service will launch the binder to one server/endpoint. This is a feature request to allow a maintainer for the binder service to configure additional launch targets for binder, other than the default (e.g. "Launch on CyVerse").

**Comment by choldgraf** [comment]
this is related to #63 ...I totally agree something like this would be great. Do we want to keep this issue open or move discussion to #63 ?

**Comment by betatim** [comment]
Closing this in favour of #63
