### ISSUE TITLE
Possibility of python-markdown nbextension

### ISSUE THREAD

**Issue by step21** [jupyterhub/binderhub#225]
Hi, I recently got into using jupyter/ipython notebooks, and locally a really handy thing to have that make the whole thing so much better is the python-markdown extension. Especially for binder it seems also relevant, as it helps making clean, easily updated documents. See also ["Publication ready python notebooks"](http://blog.juliusschulz.de/blog/ultimate-ipython-notebook) which mentions this and some other tips. Only when then using such a notebook with mybinder, all variables used in `{{ }}` do not display obviously :-/
So, is there any discussion/hope that this will be possible in the future? I guess you have to be careful with extensions due to security and so on, but maybe at least this very useful extension or a similar one could be added? (f.e. I would be fine with just using variables in markdown, or maybe only certain approved functions instead of all of python.

**Comment by choldgraf** [comment]
This is a great point! notebook extensions are actually already supported, and can be enabled with `postBuild` files (see https://github.com/binder-examples/jupyter-extension)

The main hangup is that python-markdown only supports notebook versions <= 4. The current version is 5, and it looks like the authors of that extension haven't updated it yet. Let me see if I can put together a repo that accomplishes what you're trying out

**Comment by choldgraf** [comment]
I take it back! figured it out with notebook == 5, though note that there are some weird-ish things you've got to do with the `postBuild` file:

https://github.com/binder-examples/jupyter-extension

binder link:

https://beta.mybinder.org/v2/gh/binder-examples/jupyter-extension/master?filepath=index.ipynb

**Comment by choldgraf** [comment]
gonna close this since the extension does work, but LMK if you have other questions!

**Comment by step21** [comment]
Cool, thanks very much. Locally it already worked with 5, but I didn't know about postBuild. I think maybe with 5 sometimes you have to rerun/restart but otherwise it'd fine.
