### ISSUE TITLE
can't see full build logs

### ISSUE THREAD

**Issue by djarecka** [jupyterhub/binderhub#228]
Hi, I'm trying to use mybinder, building a docker image fails, but I'm not able to see entire build logs. The error message is long and I'm not able to scroll anything. I'm using Google Chrome on OSX,  any suggestions?

**Comment by yuvipanda** [comment]
Heya! Thanks for posting the bug report!

Can you tell us which repository you were trying to build? Also if at all possible post a screenshot of what you are seeing? Last we checked things seem to be working on on Chrome OS X...

**Comment by djarecka** [comment]
@yuvipanda Hi, I'm sorry for late answer, I came back to this only last Friday. The error itself was related to our Dockerfile, now it is fixed and it's working (this is the [repo](https://github.com/miykael/nipype_tutorial). 
However, I was building various container for the last few days, and during some builds (I don't know maybe 10 or 20% of them) I was not able to scroll within the build log window.
