### ISSUE TITLE
Build handler that does not launch.

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/binderhub#229]
Some images take a while to build. 

Would it make sens to have an endpoint to trigger-build-if-necessary but does not launch ?
Or is launching cheap enough that's it's ok if an image stars and is not used ?

**Comment by yuvipanda** [comment]
launching is cheap enough, and we have a 10minute cleanup timeout now, so it's ok I think!

**Comment by Carreau** [comment]
Ok. Thanks.
