### ISSUE TITLE
Unable to set vanilla setup

### ISSUE THREAD

**Issue by drorata** [jupyterhub/binderhub#236]
I tried to follow the steps described in [the manual](https://binderhub.readthedocs.io/en/latest/create-cloud-resources.html) and failed at the very end. I try to serve [a repository](https://github.com/drorata/test_binder) and the log ends with:

```
Successfully built 0ef70d4d9c47
denied: Unable to create the repository, please check that you have access to do so.
```

During the installation, I had a problem with setting the `Service account` and I set it wrongly. I recreated the account and repeated the steps of the installation (including deleting the pervious one `helm del --purge binder;`). However, the problem was not solved and I still fail to serve the notebook.

I'd appreciate any kind of help.

**Comment by drorata** [comment]
I killed the project and restarted from scratch. Now it is working. Worthy mentioning, I had to `gcloud config set project project-name` as I used a new name for the project.

**Comment by choldgraf** [comment]
thanks for the note - created an issue to add that language in there as it may be confusing for some people
