### ISSUE TITLE
doc/env.yml innacurate ?

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/binderhub#246]
```
$ conda env create -f doc/environment.yml -n bdoc
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - mne -> mayavi -> apptools 4.2.0 -> python 2.7*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

Not sure how it works on RTD....

**Comment by willingc** [comment]
Is `mne` a dependency? The current environment.yml is for Python 3.5 and doesn't list mne and RTD is building using this file unless @choldgraf has customized in another place.

**Comment by choldgraf** [comment]
I bet that's a carryover from the old days... I think we can remove mne.

**Comment by willingc** [comment]
Cool. Tahnks @choldgraf

**Comment by Carreau** [comment]
I think there might be also a bug in Conda, where 'pip' needs to be explicitely listed if there is a `pip:` sections. And it would be nice to get a more stable pygraphviz (that I can't install on my machine).

**Comment by willingc** [comment]
@Carreau If you remove only mne and leave the rest of the environment.yml the same do you get an error? It's building correctly on MacOS 10.12.6 with Python 3.

**Comment by Carreau** [comment]
Yes, but if you remove the _build directory and rerun, then the schema is
missing from the built docs (at least for me). And I suppose RTD starts
from a clear _build directory right ?

**Comment by choldgraf** [comment]
ah - looks like I was using MNE for the flow diagram:

https://github.com/jupyterhub/binderhub/blob/0460c2c26ff2fca56eadf3a77aa303d592f7ec81/doc/script/flow_diagram.py

There's been discussion about just creating a static "flow" diagram, which I think is a good idea! I opened up #249 to iterate on that specific issue

**Comment by willingc** [comment]
> And I suppose RTD starts from a clear _build directory right ?

It should. Though they do keep the build container around for a while so sometimes you need to go into their versions page and wipe the build.

I think you are right about the schema stuff. I'm heading out for the day, and Steve has eye surgery tomorrow so I'll be at the hospital for most of the day (he'll be fine and hopefully will not see 3 of everything in one eye any more). I'll amend my review on your PR so I'm not blocking progress ;-)
