### ISSUE TITLE
Creating a static diagram

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#249]
Currently the diagram is being generated by code each time the docs build. As mentioned in a few issues, this is a sub-optimal solution, and it'd probably be easier to just use static diagrams that we can include in the documentation.

I took a stab at drafting what these might look like:

https://docs.google.com/presentation/d/1t5W4Rnez6xBRz4YxCxWYAx8t4KRfUosbCjS4Z1or7rM/edit?usp=sharing

There are two components in there:

* JupyterHub with Kubernetes
* BinderHub

Think we can iterate on this and get two "canonical" diagrams for our uses?

**Comment by willingc** [comment]
>Think we can iterate on this and get two "canonical" diagrams for our uses? (one for jupyterhub one for binderhub)

Good idea @choldgraf. Let's iterate on these. Also, we've had a pretty standard visual for JupyterHub for a while. Let's scope this issue to:
- JupyterHub with Kubernetes
- BinderHub

**Comment by choldgraf** [comment]
ah yes, good point, I meant JupyterHub k8s!

**Comment by choldgraf** [comment]
I'll plan to freeze the diagrams in that google presentation and make a PR to add them to the docs soon, so I'd love to hear thoughts/feedback/suggestions etc!

**Comment by choldgraf** [comment]
hey all - these diagrams are now semi-finished (in the always evolving but currently pretty good sense), so I'm closing this!
