### ISSUE TITLE
error on GKE after helm init

### ISSUE THREAD

**Issue by brooksambrose** [jupyterhub/binderhub#251]
On GKE following the docs I get this on `helm init`:

```
$ helm init
Creating /home/brooksambrose/.helm
Creating /home/brooksambrose/.helm/repository
Creating /home/brooksambrose/.helm/repository/cache
Creating /home/brooksambrose/.helm/repository/local
Creating /home/brooksambrose/.helm/plugins
Creating /home/brooksambrose/.helm/starters
Creating /home/brooksambrose/.helm/cache/archive
Creating /home/brooksambrose/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /home/brooksambrose/.helm.
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system
/deployments: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```

Comes up again a few steps later at `helm install`:

```
$ helm install jupyterhub/binderhub --version=v0.1.0-789e30a
 --name=binder --namespace=binder -f secret.yaml -f config.yaml
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cnam
e%3Dtiller: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```

**Comment by brooksambrose** [comment]
The cluster is up on console.cloud.google.com, but I something went wrong on the cloud shell. Deleting the cluster and starting it again worked.

```
$ kubectl get node
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by choldgraf** [comment]
huh, that is weird!

**Comment by brooksambrose** [comment]
It looks like helm wasn't able to talk to the cluster to install the Tiller, and tried to install it on the cloud console...?

**Comment by betatim** [comment]
Was it/is it using the wrong credentials? I remember getting a weird sounding error similar to that when I switched projects or something (sorry for vagueness). I think I used https://cloud.google.com/sdk/gcloud/reference/container/clusters/get-credentials to fix it.

**Comment by ProProgrammer** [comment]
I my case the issue was that the current context was not set correctly, I ran `gcloud container clusters get-credentials <cluster_name> --zone <zone_name>` and post that I checked that the context has been set for kubectl by running `kubectl config current-context` and it worked as expected.
