### ISSUE TITLE
Make binderhub chart work with latest master of JupyterHub chart

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#262]
Currently it does not. Investigate why and fix it!

**Comment by hydrosquall** [comment]
I originally got the following error in my console (and the site refuses to load) after following the directions in `CONTRIBUTING.md`, and attempting to visit the following link in either Chrome or Safari. (I am developing on Mac OSX). 

https://localhost:8585/

```bash
[I 171111 13:31:50 http1connection:253] Malformed HTTP message from ::1: Malformed HTTP headers: '\n\x01\x00\x00wZZ\x00\x00ÿ\x01\x00\x01\x00\x00\x00\x00\x0e\x00\x0c\x00\x00\tloca'
```

However, the error went away when I switched from `https` to `http` inside my web browser. Maybe this could be related?

**Comment by hydrosquall** [comment]
#265 fixes the part where the I can now successfully pull down new repositories (which wasn't true before). However, after the container for the repo entered into the UI builds, the new server fails to launch.

**Comment by choldgraf** [comment]
@yuvipanda does this work now? alternatively, do you think this is related to the RBAC challenges reported in #391

**Comment by choldgraf** [comment]
It does now! thanks to #402
