### ISSUE TITLE
Setup Unit Testing for Binderhub

### ISSUE THREAD

**Issue by hydrosquall** [jupyterhub/binderhub#268]
See this comment: https://github.com/jupyterhub/binderhub/pull/264#issuecomment-343750132

Reference for mocking + examples:

- https://github.com/jupyterhub/jupyterhub/tree/master/jupyterhub/tests

Additional tasks that could be separate PRs or part of this

- Including code coverage statistics in CI
- Add running unit tests to the `setup.py` + `travis.yml`

**Comment by betatim** [comment]
For coverage: codecov works well for me. Below some snippets to help make that happen.

A `.codecov.yml` to ignore coverage of tests:
```
coverage:
  ignore:
    - "binderhub/tests/*"
```
and this bit of magic in `.travis.yml` as well as installing the `coverage` module from PyPi:
```
script:
  - if [ ${COVERAGE} == "true" ];
    then pytest --cov=binderhub; else
    pytest;
    fi

after_success:
  - if [ ${COVERAGE} == "true" ]; then
    pip install codecov;
    codecov;
    fi
```
Maybe an admin also has to enable codecov.

**Comment by minrk** [comment]
#270 starts uploading coverage to codecov
