### ISSUE TITLE
tornado.httpclient.HTTPError: HTTP 403: Forbidden

### ISSUE THREAD

**Issue by brooksambrose** [jupyterhub/binderhub#269]
I put a GKE cluster to sleep by resizing it to zero, after I brought it back up I am getting build fails with an "Internal Server Error" from my binderhub page. The binderhub pod log says `tornado.httpclient.HTTPError: HTTP 403: Forbidden`. 

![screenshot 2017-11-12 20 44 59](https://user-images.githubusercontent.com/1271481/32710259-99292620-c7eb-11e7-98f4-8f83cecb2411.png)

I purged the helm release and deleted the namespace, then repeated the binder hub docs instructions. I also killed the cluster and started it again from scratch, to no avail. I am reusing the same `secret.yaml`. Any clue what's going wrong?

**Comment by choldgraf** [comment]
I remember @yuvipanda had mentioned some weirdness around resizing a google cluster to 0, then bringing it back. Something about the IP not being retained?

@brooksambrose does the same problem happe nwhen you resize down to 1 node?

**Comment by brooksambrose** [comment]
I've torn the cluster down and started the instructions from the beginning several times, and I'm still getting the same problem. I'll kill the whole project and really start over. Any clue about where/why the error is happening?

**Comment by brooksambrose** [comment]
Never figured it out but trashing the project and my [google cloud console home directory](https://cloud.google.com/shell/docs/limitations#resetting_cloud_shell_to_default_state) worked.

**Comment by choldgraf** [comment]
... Hooray?

We should make sure to warn people of this behavior if it happens fairly often

**Comment by willingc** [comment]
@brooksambrose I'm going to reopen this. Thanks for bringing it to our attention. A couple of questions:

- did you follow the [z2jh instructions for resizing](http://zero-to-jupyterhub.readthedocs.io/en/latest/extending-jupyterhub.html?highlight=resize#expanding-and-contracting-the-size-of-your-cluster) to zero?
- what version of gcloud and kubectl are you using?

I think it's worth testing this out to determine what happens with ssh and credentials when resizing to a) one node and b) zero nodes on Google Cloud.

From https://cloud.google.com/kubernetes-engine/docs/support:

> If you've scaled down the number of nodes in your cluster to zero, SSH tunnels won't work.
To fix it, resize your cluster to have at least one node.


Related issue https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/181

**Comment by minrk** [comment]
It would be useful to know what URL being requested is failing with 403. Have you set up GitHub OAuth credentials? If not, there's a chance you are running into GitHub API rate limit.

If it's an internal API issue, it could be that the token used to communicate between BinderHub and JupyterHub is not in sync. I'm not certain exactly how to fix that one.

**Comment by brooksambrose** [comment]
Sadly I'm a little distant from the error now and can't repro. @aculich had a hunch about "cruft" accruing in my google cloud project due to stopping and starting a lot of clusters, or I may have had a bad config. Safe to close if it hasn't come up for anyone else imho. I will be starting a new cluster in the Spring so I'll document if I run into it again.
