### ISSUE TITLE
Make it more clear that a binder is building/loading

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#271]
@sylvaincorlay mentioned that several of their xtensor users have been confused after clicking Binder badges. They get redirected to a new page, and because nothing changes super-quickly they just close the page and move on.

This issue is for discussing ways to make it more clear to users that "your binder is building" during this time.

A few suggestions that popped up:
* Add more steps to the progress bar during build. This would only really make sense for the "build" phase of repos, which mostly just pertains to the repo author.
* Add a separate "launch" page that'd have its own progress bar / UI
* Restart the progress bar during the launch stage and add in some "fake" progress steps while we wait for the server to launch.

I believe @minrk had some ideas on this too!

**Comment by minrk** [comment]
It would be cool (not sure how feasible) to make the build progress count and track the docker statements, so build could get X/Y updates as it moves along.

**Comment by astrofrog** [comment]
One idea I had would be to make it so the URL includes an extra optional argument e.g. ``simpleprogress=1`` which, if set, would show a simplified progress bar for users.

**Comment by choldgraf** [comment]
I think something like that sounds good - or even do the opposite behavior, have a keyword like "buildcontrol=True" to force it to show the build UI, and have a binder link default to the "simple progress" page

**Comment by betatim** [comment]
I think we can address this by showing a different page (with a spinner) to people who visit `mybinder.org/v2/gh/blah/foo/master` directly. So they don't see the form at all and if you visit `mybinder.org/` we show you the form and detailed logs. IMHO this would also fit with #196

**Comment by choldgraf** [comment]
for sure - that's what I meant by

 > and have a binder link default to the "simple progress" page

so +1 from me :-)

**Comment by choldgraf** [comment]
What do folks think for something like this for the page you'd hit after clicking on a binder link (it'd be much smoother in the actual browser, choppiness is because of the gif capture):

![loadingdemo](https://user-images.githubusercontent.com/1839645/34393904-345990ca-eb56-11e7-8393-d0bc03c818da.gif)

**Comment by choldgraf** [comment]
@betatim you mentioned a spinner before, is this what you imagined?

I think we could combine this w/ some kind of cycling through clever phrases (e.g. "reticulating splines")

**Comment by astrofrog** [comment]
This looks great!

**Comment by choldgraf** [comment]
If folks in general are happy w/ that page, I can make a PR to have ParameterizedMainHandler point there instead of the build page and we can iterate on specifics there. LMK

**Comment by betatim** [comment]
Just found this tab again. Must have been to mesmerised by the spinner (which is awesome) to actually post a reply. LGTM!!

**Comment by choldgraf** [comment]
Note that I've got #384 mostly ready to go to implement a loading page! Will iterate on discussion there @betatim :-)

**Comment by choldgraf** [comment]
this is now fixed with #384 , ping @SylvainCorlay :-)

**Comment by SylvainCorlay** [comment]
Awesome!

**Comment by astrofrog** [comment]
Thanks! 👍
