### ISSUE TITLE
Replace badge.svg to match badge from shields.io

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#279]
We should just have shields.io generate a badge and check that in replacing the current badge.

**Comment by choldgraf** [comment]
+1

**Comment by choldgraf** [comment]
How about this one:

https://img.shields.io/badge/launch-binder-E66581.svg?style=flat

![](https://img.shields.io/badge/launch-binder-E66581.svg?style=flat)

I can just copy that svg into `mybinder.org/badge.svg`. Alternatively I wonder if there's some way to link that `badge.svg` to the `shields.io` badge...

**Comment by yuvipanda** [comment]
@choldgraf +1 to just copying it. I don't think we should depend on a 3rd party service for the badge.

**Comment by willingc** [comment]
I agree +1 to copying.

**Comment by yuvipanda** [comment]
Let's try do this before the blog posts go out?

**Comment by choldgraf** [comment]
already done! https://github.com/jupyterhub/binderhub/pull/285 + a few followups
