### ISSUE TITLE
How to handle long slug names

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#290]
For some providers, our current manner of handling slugs will create slugs that are too long. @mariusvniekerk ran into this potential issue on the gitlab PR (#266). We should figure out how to handle these situations!

**Comment by yuvipanda** [comment]
Where is this a problem? Can you point me to a specific comment? We make sure that slug name lengths aren't a problem in https://github.com/jupyterhub/binderhub/pull/266/files#r152119597

**Comment by choldgraf** [comment]
I can go digging when I land, I think it was on gitter and I just wanted to
make sure it didn't get lost in case it was a real issue. If this is not a
real issue then we can close.

**Comment by yuvipanda** [comment]
It was clarified in the PR and is not an issue anymore there :)
