### ISSUE TITLE
Document setting up your GitHub credentials with a local dev install

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#291]
@jzf2101 was setting up a BinderHub with someone at a sprint and they ran into GitHub rate limit issues on their local test. We should document how to set up GitHub credentials so that BinderHub uses them in a local test.

@yuvipanda @minrk have either of you figured this out? Feel free to post barebones steps in this issue and I can make a PR to `CONTRIBUTING.md`.

**Comment by jzf2101** [comment]
@ventilooo mentioned this to me

**Comment by minrk** [comment]
1. create a new token with default (check no boxes) permissions [here](https://github.com/settings/tokens/new)
2. store it somewhere (e.g. keychain, netrc, etc.)
3. when running tests, `export GITHUB_ACCESS_TOKEN=...`

**Comment by jzf2101** [comment]
I'm going to mark this down so we can put get this ready for the PyData NYC sprint
