### ISSUE TITLE
Travis testing of docs

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/binderhub#296]
I don't see doc builds in our travis yml, perhaps we should be doing this? @Carreau can you confirm?

**Comment by willingc** [comment]
@jzf2101 We are not testing in Travis. You could add the doc build/test in Travis, but please do not modify the readthedocs.yml deployment. Thanks!

**Comment by choldgraf** [comment]
@jzf2101 were you just talking about for testing? As @willingc mentions, docs are auto-deploying to the web via readthedocs right now!

**Comment by jzf2101** [comment]
@choldgraf yes

**Comment by manics** [comment]
The docs are built on readthedocs including for PRs (link is included in the PR checks statuses)
