### ISSUE TITLE
build crashes if apt.txt contains an empty line

### ISSUE THREAD

**Issue by giovannipizzi** [jupyterhub/binderhub#302]
I hope this is the best place to report the bug.
I think when parsing apt.txt, one could/should remove empty lines - probably something like the following:
```python
for l in lines:
    package = l.partition('#')[0].strip()
    if not package:
       continue
    # do stuff here
```
that also takes allows for comments in that file.

**Comment by betatim** [comment]
Thanks for reporting this! The building of the container from the repository is handled by https://github.com/jupyter/repo2docker. I will create a copy of this issue there and close this one.
