### ISSUE TITLE
wait for test hub to be responsive in install-hub

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binderhub#312]
The testing/minikube/install-hub script is used to launch jupyterhub with helm. Currently, it waits for the pods to be running, but it doesn't wait for the hub socket to accept connections.

The fixture in conftest.py checks for a running hub with a timeout, but will fail immediately with ConnectionRefused if nothing is there. This has caused the main tests to fail sometimes on Travis when jupyterhub is slow to warm up.

As a band-aid in #305 I added a sleep after running install-hub on Travis because I didn't want to hold up that PR for a fix.

The fix should be: in install-hub, after waiting for the pod to be running, wait for the Hub to accept connections. With that, the sleep in ci/test-main ought to be removed.

**Comment by yuvipanda** [comment]
Hmm, perhaps we can add a readiness check to the hub deployment, which will make it not be Running until it passes the check? (I think)

**Comment by manics** [comment]
I'm assuming this has been fixed since the CI has had quite a few changes in the past few years.
