### ISSUE TITLE
abort launch if connection is lost

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binderhub#314]
Right now, if a connection is dropped during a build, launch is not attempted thanks to the `raise web.Finish` in emit. However, if a connection is dropped after launch is requested and before redirect occurs (e.g. refreshing the page several times of an already-built image), the launch still completes.

If the request is closed before launch completes, we should cleanup the Hub user immediately, so it's not taking up a slot for ten minutes when we know nobody can be using it.

**Comment by willingc** [comment]
Similar to #245. Do we want to close #245?

**Comment by manics** [comment]
Closing as suggested, see #245
