### ISSUE TITLE
Make URL handlers more forgiving

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#318]
http://mybinder.org//v2/gh/katyhuff/npre412/master gives a 404. http://mybinder.org/v2/gh/katyhuff/npre412/master (one less /) works though.

Is this a bug or "your own fault for putting two /"?

**Comment by choldgraf** [comment]
if it's a simple matter of adding a `.strip('/')` somewhere then I'm +1, if it's more complex I dunno if it's worth trying to fix this since I imagine users will figure it out eventually

**Comment by manics** [comment]
Closing since there's no clear decision, feel free to re-open.
