### ISSUE TITLE
Wrong url when starting jupyterlab

### ISSUE THREAD

**Issue by mdeff** [jupyterhub/binderhub#321]
If I go to <https://mybinder.org/> and fill in `mdeff/ntds_2017`, branch `conda-env` and url `lab` it builds and launches properly but then redirect me to a url like <https://hub.mybinder.org/user/mdeff-ntds_2017-kc5st22d/tree/lab>. Note the `tree/lab` at the end.

If I instead call binder with <https://mybinder.org/v2/gh/mdeff/ntds_2017/conda-env?urlpath=lab>, then I don't get the `tree` part and am correctly redirected to <https://hub.mybinder.org/user/mdeff-ntds_2017-kc5st22d/lab>.

**Comment by choldgraf** [comment]
this sounds like intended behavior to me...note the "file" state of the button just to the left of `launch`.

![image](https://user-images.githubusercontent.com/1839645/33498475-4d1f309a-d686-11e7-8208-77c3e9d4c6fe.png)

That will make the URL contain `filepath=` not `urlpath=` as a parameter. You wanna click the button and then select "URL" then try again. Does that fix it?

**Comment by mdeff** [comment]
Okay I found the issue... I was selecting "File" and not "URL" in the path field. Could it instead be inferred that if the path ends with `.ipynb` it's a notebook and `tree` should be appended to the url?

**Comment by choldgraf** [comment]
(FWIW this is definitely an unintuitive UI and we're thinking about ways to improve it)

**Comment by mdeff** [comment]
Ah I discovered it too late. Thanks @choldgraf. It's very unintuitive indeed... Maybe at least put the selector on the left?

**Comment by choldgraf** [comment]
We've got a PR that'll update the launch button to the right, and I think the next step will be figuring out stuff like URL vs. filepath. I agree putting the button on the left might help!

Mind if I close this in the meantime? Hopefully UI improvements will come soon :-)

**Comment by mdeff** [comment]
Sure. I look forward to the UI update.

**Comment by choldgraf** [comment]
Thanks for the feedback! Agree there's a ways to go on the UI side. We've spent most of our time on backend stuff so far but it's time for a few front-end cycles methinks :-)

**Comment by mdeff** [comment]
While you are here, any idea why the jupyterlab I get with <https://mybinder.org/v2/gh/mdeff/ntds_2017/conda-env?urlpath=lab> is broken? I installed jupyterlab and the launcher with `conda` while the example used `pip`.

**Comment by choldgraf** [comment]
yes I do actually, I ran into the problem yesterday :-)

It's an annoying bug introduced by the fact that we pinned jupyterlab to 0.28, but jupyterlab_launcher 0.6 isn't compatible with it. The bugfix is already making its way through the pipeline and should be fixed soon. In the meantime you *should* be able to get this working by pinning jupyterlab_launcher to 0.5

**Comment by mdeff** [comment]
Oh that's good thanks :-)

**Comment by mdeff** [comment]
Confirmed to work: <https://mybinder.org/v2/gh/mdeff/ntds_2017/master?urlpath=lab> :-)

**Comment by choldgraf** [comment]
wohoo!!
