### ISSUE TITLE
add max pod age

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binderhub#326]
Our culler currently shuts down only idle pods. But some pods get stuck with an open connection.

JupyterHub doesn't track start time of Spawners (it should! https://github.com/jupyterhub/jupyterhub/issues/1573), so we would need to talk to pods directly to get their age.

Another option is to use a culler that talks to the notebook API, which differentiates kinds of traffic, and can ignore open connections as an activity metric, if we so choose. This is notebook specific, though, and not generalizable to other applications.

**Comment by minrk** [comment]
The notebook API approach is not just notebook specific, but notebook *version* specific, as the activity API is new in 5.1, I think, and improved in 5.2.

**Comment by choldgraf** [comment]
I believe this is closed by https://github.com/jupyterhub/binderhub/pull/502
