### ISSUE TITLE
URL Type: Zip files

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#33]
This is a future feature idea. Some of the sphinx-gallery devs said that it'd be useful if Binder supported zipfiles that basically had the full contents of a github repository.

So you could give binder a URL to a zip file, and the inside of that file is the contents of a github repository. Binder would unzip first, and then treat the contents the same way as any other repo. Doesn't seem too tough to implement but I wonder if there would be security issues?

cc @Titan-C in case he has any thoughts!

**Comment by yuvipanda** [comment]
I'm going to decline this - primarily because URLs are not immutable. They can change under us at any point, and there's no real way to ensure that they're the same from a while ago. I think supporting #62 is going to tackle the use case of 'something simpler than a full fledged github repo'
