### ISSUE TITLE
Polish the new UI

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/binderhub#330]
I recently merged #252, by leaving a few comments about the UI (https://github.com/jupyterhub/binderhub/pull/252#issuecomment-350263076) and on the diff itself.

Most of these are small things just polishing the last 1% of a really good UI, and cleaning some technical/user-interface debt. It should be good for first time contributor and relatively easy.

**Comment by Carreau** [comment]
Meh, I did part of that in #332, there are still a couple of fixes that need to be done for media-queries at narrow width.

**Comment by choldgraf** [comment]
Do we have a specific list of improvements to be made? I find this issue a bit hard to work on since I don't know what you have in mind @Carreau :-)

**Comment by choldgraf** [comment]
I believe these have all been taken care of, so I'm gonna close this...feel free to re-open, or to open other more specific design issues!
