### ISSUE TITLE
rate-limit individual repos

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binderhub#331]
We had a significant spike in traffic earlier today, almost entirely from one repo.

<img width="753" alt="screen shot 2017-12-08 at 14 53 47" src="https://user-images.githubusercontent.com/151929/33768756-9f502cec-dc27-11e7-9a5a-4a76193eaaa8.png">

We should consider limiting the impact one repo can have on the rest of the service. As it is now, one repo can easily consume the entirety of Binder. Setting an upper limit on the number of concurrent users running from a given repo would give us a knob for something like this.

On one hand, it's nice to be able to handle traffic peaks from things like the eLife announcement, or a norvig post. On another, it's an avenue for abuse of the service and can prevent others from being able to use it.

**Comment by choldgraf** [comment]
is it possible to do this w/ a whitelist of some kind? e.g., we could make a PR to a whitelist of repos in anticipation of heavy traffic on a single repo

**Comment by minrk** [comment]
This came up again yesterday, where one image was running ~750 containers:

<img width="675" alt="screen shot 2017-12-20 at 14 36 15" src="https://user-images.githubusercontent.com/151929/34209647-4fbedee2-e593-11e7-8bae-0035cc63d678.png">

We now have a blacklist (#367), but a rate limit will allow us to mitigate this in the future. I think instituting a plain rate limit for now, with the possibility of a whitelist in the future will help us out.
