### ISSUE TITLE
Measure typical user browser's window height.

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/binderhub#333]
I believe the "height" of the binder main page (when creating a repo or waiting) is too heigh. I have a hi-dpi screen set to 1/2 usual size and can't see the bottom of the bottom of the binder form:

<img width="377" alt="screen shot 2017-12-08 at 22 33 45" src="https://user-images.githubusercontent.com/335567/33786063-f06d2e00-dc67-11e7-92a5-aff5b12f87eb.png">

I suggest tracking (temporarly?) with GA the `$(window).height()` / `$(window).width()` of our users (as well as whether they are filling the form or waiting for launch), and make sure the all form fit in the usual user window.

We can also in css use vh/vw units to help with that.

**Comment by choldgraf** [comment]
sounds like a good idea to me (though I have no idea how to do this :-)

**Comment by yuvipanda** [comment]
I believe Google Analytics already does this?

**Comment by choldgraf** [comment]
ah yep, here's what we've got for screen resolution:


1. 1920x1080
884(22.91%)
65.05%
575(23.38%)
71.61%
1.58
00:01:31
0.00%
0(0.00%)
$0.00(0.00%)
2. 1366x768
551(14.28%)
59.89%
330(13.42%)
77.50%
1.40
00:01:32
0.00%
0(0.00%)
$0.00(0.00%)
3. 1440x900
481(12.47%)
57.38%
276(11.22%)
74.43%
1.51
00:01:44
0.00%
0(0.00%)
$0.00(0.00%)
4. 1280x800
245(6.35%)
63.67%
156(6.34%)
75.92%
1.52
00:02:14
0.00%
0(0.00%)
$0.00(0.00%)
5. 2560x1440
204(5.29%)
55.39%
113(4.60%)
65.20%
1.58
00:02:20
0.00%
0(0.00%)
$0.00(0.00%)
6. 1920x1200
201(5.21%)
66.67%
134(5.45%)
68.16%
1.66
00:01:59
0.00%
0(0.00%)
$0.00(0.00%)
7. 1680x1050
176(4.56%)
69.32%
122(4.96%)
71.59%
1.57
00:01:06
0.00%
0(0.00%)
$0.00(0.00%)
8. 1536x864
175(4.54%)
64.57%
113(4.60%)
78.29%
1.43
00:01:19
0.00%
0(0.00%)
$0.00(0.00%)
9. 360x640
109(2.83%)
78.90%
86(3.50%)
73.39%
1.36
00:01:04
0.00%
0(0.00%)
$0.00(0.00%)
10. 1600x900
82(2.13%)
65.85%
54(2.20%)
78.05%
1.54
00:01:56
0.00%
0(0.00%)
$0.00(0.00%)

**Comment by Carreau** [comment]
But that is *screen resolution* not *browser height*, I know we get screen res, but that is not super useful, unless everyone uses their browser full-screen and without any decorations and windows border !

**Comment by choldgraf** [comment]
Ah ha - I figured out how to get a custom report for browser size:

![image](https://user-images.githubusercontent.com/1839645/33954331-ce503398-dfec-11e7-9f78-a4f11b218c86.png)

also, wow the formatting on my previous comment got messed up somehow, I'm gonna put it in `details`

**Comment by choldgraf** [comment]
For ref: 
![image](https://user-images.githubusercontent.com/1839645/33954636-b2a29a86-dfed-11e7-84f5-10e5dec00d68.png)

**Comment by Carreau** [comment]
I'm confused if this is really browser size as all the measures are multiple of 10px...

I used pandas to remove the width and got the following cumulative curve for seen browser height:

<img width="632" alt="screen shot 2017-12-14 at 12 42 54" src="https://user-images.githubusercontent.com/335567/33990819-800c4ce0-e0cc-11e7-8907-604ea3e0910f.png">

**Comment by minrk** [comment]
I assume they round to buckets for anonymizing purposes

**Comment by minrk** [comment]
I think this and other reports point to using a different page for people coming to fill out a form vs people visiting a filled-out link who are just waiting to launch (which is served by the ParameterizedMainHandler at this point). Probably much less information should be shown in that case.

**Comment by Carreau** [comment]
> I think this and other reports point to using a different page for people coming to fill out a form vs people visiting a filled-out link who are just waiting to launch (which is served by the ParameterizedMainHandler at this point). Probably much less information should be shown in that case.

We could add a custom metric point to segregate the two case. 

IMHO when automatically launching we should also show the Moore fundation logo or any other sponsors.

**Comment by choldgraf** [comment]
> I assume they round to buckets for anonymizing purposes

Probably also just to keep it more manageable for showing data. Counting by pixel-perfect browser sizes would be pretty messy.

> I think this and other reports point to using a different page for people coming to fill out a form vs people visiting a filled-out link who are just waiting to launch (which is served by the ParameterizedMainHandler at this point). Probably much less information should be shown in that case.

I totally agree. That's related to #196 and #350 too (I should close one of those now that I just realized they are dupes hah)

> IMHO when automatically launching we should also show the Moore fundation logo or any other sponsors.

Definitely, this could be part of the federation model too, allowing deployers of BinderHub to specify their own "launch_image.png" or something like this

**Comment by choldgraf** [comment]
So we now have two different pages for "click a binder link" vs. "create a binder link". We also have #260 to suggest modifying for branding etc. So shall we close this one in lieu of the other issues? @Carreau what do you think?

**Comment by manics** [comment]
No-one responded to the last comment, closing.
