### ISSUE TITLE
Dynamic Fav: Revert to normal icon if re-click "Launch" after fail.

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/binderhub#337]
cc @choldgraf 
Do you also have a "currently-building" fav ?

**Comment by choldgraf** [comment]
Yep - that PR should already include this.

re: currently building (or "succeed") I thought about this but figured I'd keep it simple. That said, I just mocked these up:

building:
<img src="https://user-images.githubusercontent.com/1839645/33806547-b7c9325c-dd7e-11e7-958a-d28d44adab64.png" width=16 />

succeed:
<img src="https://user-images.githubusercontent.com/1839645/33806555-c4afb216-dd7e-11e7-98d1-2fd3eab10957.png" width=16 />

**Comment by choldgraf** [comment]
(note that most browsers have a darker background than the github page background, so the lights will show up a little bit better)

**Comment by Carreau** [comment]
Liked it. The "Succeed" is likely unnecessary as the notebook will just be launched, bu we can still include it.

**Comment by choldgraf** [comment]
yeah - I added it in case we ever build some kind of workflow where the repo doesn't auto-launch

**Comment by choldgraf** [comment]
will be closed by https://github.com/jupyterhub/binderhub/pull/347
