### ISSUE TITLE
Review and improve initial message in form and/or clarity of UI element title

### ISSUE THREAD

**Issue by willingc** [jupyterhub/binderhub#340]
"Begin typing..." implied to me that I should type in the box with the message. The exclamation mark makes it feel like an order instead of guidance.

<img width="924" alt="screenshot 2017-12-10 14 54 51" src="https://user-images.githubusercontent.com/2680980/33809291-5678acd0-ddba-11e7-9e16-3643ee07e618.png">

**Suggestion**

Soften message. Perhaps something similar to: "After filling in the form, a generated URL for sharing your Binder will appear here."

**Comment by Carreau** [comment]
+1 marking as "Good first issue".

**Comment by choldgraf** [comment]
@willingc @Carreau do you think it'd be worth creating a "user interface" tag for these issues? In my mind UI things require a particular skillset / kind of interest, and might be worth highlighting w/ a tag

**Comment by willingc** [comment]
The `user experience` tag covers UI/UX issues. It's orange since it is something that typically involves designers 👍
