### ISSUE TITLE
race condition mounting docker-in-docker socket in build

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binderhub#349]
When using docker-in-docker, there is a chance that dind hasn't started when a build is requested. If this happens, the volume mount to load `/var/run/dind/docker.sock` into the build container could occur before dind has created the socket, in which case the volume mount will have its default behavior of creating a directory at the mount point. If this happens, docker-in-docker will be inaccessible until `/var/run/dind` is cleaned out manually and the `dind` pod is restarted.

Two possible fixes:

1. postStart hook to add a node label and use nodeSelectors to schedule builds only where dind is known to be up and running. This should fix the issue robustly, but requires elevated permissions to modify the node.
2. mount *directory* rather than the file. This will still result in a failed build when the race occurs, but at least it won't mess up the socket for all subsequent builds on the node. Downside: when not using dind, the directory to mount is `/var/run`, which can have *lots* of stuff in it.

**Comment by yuvipanda** [comment]
If this happens again, the symptom is that the dind pods will be in crashloopbackoff. You can fix by:

1. Find out which host it crashed on. You can do so by doing `kubectl --namespace=<ns> get pod -o wide`
2. SSH into the node (for mybinder.org, it's `gcloud compute ssh <nodename>`)
3. Run `sudo rm -rf /var/run/dind/docker.sock/`
4. Delete the dind pod

**Comment by minrk** [comment]
This should have been fixed by #539 but doesn't seem to have done. It's possible the same fix is needed elsewhere, or we need a kube version bump on the nodes.

**Comment by manics** [comment]
Hopefully this is fixed, if not please reopen!
