### ISSUE TITLE
Refactor index.js

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#356]
First line of index.js says:

```
/* If this file gets over 200 lines of code long (not counting docs / comments), start using a framework
```

The file is now over 200 lines long, and the lack of architecture there is causing higher than needed friction for implementing new features. Would be great if we can refactor it into using modern JS best practices - using a package manager, modularized imports, components (React?), etc.

**Comment by willingc** [comment]
Let's go ahead and use React to refactor as it's lightweight yet powerful and there's experience within the team on using it.

**Comment by choldgraf** [comment]
I hear that react is a good framework to use if you like python ;-)

**Comment by captainsafia** [comment]
Closing in favor of https://github.com/jupyterhub/binderhub/issues/777 and https://github.com/jupyterhub/binderhub/issues/774.
