### ISSUE TITLE
Support Pipfiles

### ISSUE THREAD

**Issue by araichev** [jupyterhub/binderhub#357]
Love your project.
Would be great if you could support [Pipfiles](https://github.com/pypa/pipfile) for users of Pipenv.

**Comment by choldgraf** [comment]
first off, wow I hadn't heard of pipfiles before...that is cool!

I agree repo2docker (and thus Binder) should support pipfiles. To me the main question is whether the pipfile syntax will change at all at this point? Should we assume that the structure of pipfiles and the commands you'd invoke to install from it etc. are stable at this point?

As long as the project wouldn't change too much I'd say PRs are def welcome for a [build pack in repo2docker](https://github.com/jupyter/repo2docker/tree/master/repo2docker/buildpacks). That's the logic that we use to go from config file -> Dockerfile command that implements whatever is in the config file.

**Comment by araichev** [comment]
[Pipenv](https://docs.pipenv.org/) is now the officially recommended Python packaging tool from Python.org, and it uses Pipfiles.
So that suggests some stability, but i don't know enough of about the development of either the Pipfile spec or Pipenv to comment beyond that.

I don't have the capacity at present to work on this feature request, but i hope someone does out there.

Again, nice work on this project!

**Comment by willingc** [comment]
I'm going to go ahead and label this as an enhancement. Pipenv is a pleasure to use and has some nice features like the versioning and hash with the `pipfile.lock` which could be very handy for reproducibility. Thanks @araichev for suggesting the addition.

https://docs.pipenv.org/basics/#example-pipfile-pipfile-lock

https://docs.pipenv.org/basics/#importing-from-requirements-txt

**Comment by choldgraf** [comment]
agree, thanks @araichev for bringing this up!

**Comment by yuvipanda** [comment]
I've moved this to https://github.com/jupyter/repo2docker/issues/174, with more details on what needs to happen! I agree we should support it when we need to!
