### ISSUE TITLE
Rebuild does not clear status bar

### ISSUE THREAD

**Issue by willingc** [jupyterhub/binderhub#37]
If you have a failed build, enter updated file path and press rebuild. The status bar does not clear when doing the new build.

<img width="1032" alt="screen shot 2017-05-30 at 11 48 40 am" src="https://cloud.githubusercontent.com/assets/2680980/26599669/3a64e2b8-452e-11e7-9d10-4af42dd70a53.png">

**Comment by choldgraf** [comment]
this is fixed now, yes?

**Comment by willingc** [comment]
Yes, fixed.
