### ISSUE TITLE
UI - Add indicator/message that file path is optional

### ISSUE THREAD

**Issue by willingc** [jupyterhub/binderhub#38]
`File to Launch` is optional.

<img width="960" alt="screen shot 2017-05-30 at 12 02 23 pm" src="https://cloud.githubusercontent.com/assets/2680980/26600202/051a3fd4-4530-11e7-8703-39b3c58fb717.png">

**Comment by choldgraf** [comment]
Think this is as easy as adding `(optional` after `File to Launch` ?
