### ISSUE TITLE
Option for requirements.txt and config to be in subdirectory

### ISSUE THREAD

**Issue by stuaxo** [jupyterhub/binderhub#381]
I'd like my jupyter extension to use mybinder, however it has its own requirements.txt

It would be great if mybinder could check for requirements.txt environment.yml etc in a .mybinder directory before checking the root folder.

**Comment by betatim** [comment]
You can place your files in a `binder/` subfolder, once this exists files in the top level directory will be ignored.

**Comment by choldgraf** [comment]
just opened https://github.com/jupyterhub/binder/pull/56 to try and make this clearer in the binder docs

**Comment by stuaxo** [comment]
Great, the using page is the one I ended up from by starting at mybinder clicking docs and then requirements.

**Comment by choldgraf** [comment]
Gonna close this as we now have language about this here:

https://mybinder.readthedocs.io/en/latest/using.html#config-files

and in the faq:

https://mybinder.readthedocs.io/en/latest/faq.html#can-i-put-my-configuration-files-outside-the-root-of-my-repository

Thanks for reporting @stuaxo , it's very helpful in improving the documentation!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/project-toml-in-binder-subdirectory-not-installing-packages/6265/6

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/project-toml-in-binder-subdirectory-not-installing-packages/6265/8
