### ISSUE TITLE
Remove helm update instructions in contributing.md ?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#383]
In contributing.md it has a line about running helm update on the jupyterhub repo. In a subsequent step, it then asks you to run an install script that seems to be calling the same thing:

https://github.com/jupyterhub/binderhub/blob/master/testing/minikube/install-hub#L40

Does that mean we can remove the lines about asking people to manually call `helm update`?

**Comment by minrk** [comment]
I suppose it does. It depends on if we want the install-hub script to always be used, vs doing things step by step with possible deviations along the way, depending on what you are testing. An extra `helm update` isn't so costly.

**Comment by minrk** [comment]
Perhaps clearer would be to document the manual steps and then state "the install-hub script automates steps X-Y with some defaults, if they work for you"

**Comment by manics** [comment]
https://github.com/jupyterhub/binderhub/blob/master/CONTRIBUTING.md has changed a lot!
