### ISSUE TITLE
Use a Kubernetes registry-secret instead of GCR json to connect to the registry (support ACR)

### ISSUE THREAD

**Issue by rakelkar** [jupyterhub/binderhub#385]
I want to to use an Azure Container Registry instead of GCR. Binder instructions (2.3)  require JSON from GCR that I obviously don't have. 

Looking into the code I see helm creates a binder-secret that holds the JSON and all the code seems to need is the username/password. Seems like using a kubernetes docker-registry secret can make the code provider agnostic?

I can take a shot at a PR if this sounds reasonable?

**Comment by yuvipanda** [comment]
Heya! 

From my understanding, a docker-registry secret is just a Kubernetes secret object structured in a specific way, with a username and password. For GCR, the 'password' is the service account file. For ACR, it looks like it might be generating a password that you can access with `az acr credential show` (at least according to https://medium.com/@chaliy/your-very-own-private-docker-registry-for-kubernetes-cluster-on-azure-acr-ed6c9efdeb51?)?

Either way, will welcome patches that document how to set this up on Azure, including ACR!

Thanks!

**Comment by rakelkar** [comment]
Awesomesauce - may just end up being a docs PR then...

**Comment by shibbas** [comment]
I created a PR that should help fix this: https://github.com/jupyterhub/binderhub/pull/797

**Comment by betatim** [comment]
Closed by @shibbas's PR 🎉.
