### ISSUE TITLE
Default image on py3.6?

### ISSUE THREAD

**Issue by fperez** [jupyterhub/binderhub#387]
I see that @willingc bumped the python version in `doc/env.yml` to 3.6 (yay!), but I was just testing @choldgraf's binder-stats notebook and, despite its own `reqs.txt` not pinning the Python version, I get a 3.5.

Is the default image a 3.5, or is this an artifact of an old build? I think we should be promoting 3.6 throughout for now, f-strings and pathlib are too nice to miss :)

**Comment by willingc** [comment]
The docs build uses 3.6 since it’s best to keep current with that. Yes, f-strings are very nice. :-)

**Comment by choldgraf** [comment]
Yep, we have an issue open to bump to python 3.6 when we change the default image to artful (can't find issue # cuz I'm  on my phone). Definitely agree!

**Comment by choldgraf** [comment]
latest repo2docker now uses artful, so gonna close this!
