### ISSUE TITLE
URL builder doesn't observe browser autocomplete

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/binderhub#388]
The URL builder catches everything I type, but it misses my autocomplete choices.

This is with Chrome:
![binder-complete](https://user-images.githubusercontent.com/10248125/34495406-db97c1f2-efa9-11e7-9829-55ff49c39158.gif)

**Comment by choldgraf** [comment]
good catch! I think this would be fixed by adding "change" to the `on(` section of each field:

https://github.com/jupyterhub/binderhub/blob/master/binderhub/static/js/index.js#L200

**Comment by choldgraf** [comment]
@ryanlovett can you check the mybinder.org behavior again now that #404 is merged? You will have to click outside of the text field after selecting your drop-down item, but maybe this is enough to consider this issue addressed?

**Comment by ryanlovett** [comment]
I can confirm that the url updates after clicking outside of the text field, after tabbing, and even after clicking "launch" (!). The correct image was built and run. The url does not update after clicking the copy button however which I think is the one time where having the accurate url matters the most.

**Comment by choldgraf** [comment]
ah so you mean that if you do:

start typing -> select your repo from drop-down -> immediately click copy, then the wrong URL is copied?

**Comment by ryanlovett** [comment]
Yes, exactly. And then if I click anywhere outside the text field the url doesn't update.

**Comment by choldgraf** [comment]
hmmmmm....ok let's leave this issue open then, and I can try giving it another shot later when I've got a moment. Thanks for the feedback @ryanlovett :-)

**Comment by ryanlovett** [comment]
No problem. Once I get out from under the start of the semester I'll take a look too.

**Comment by manics** [comment]
Is this still a problem?

**Comment by choldgraf** [comment]
I'm not sure how to reproduce it - my browser doesn't give me drop-down options to choose from :-/

Maybe @ryanlovett can try it and see if it's still a problem, and if we don't hear back in a day or two we should close this

**Comment by ryanlovett** [comment]
Looks like this has been fixed. Thanks!
