### ISSUE TITLE
Document how to upgrade deployments to a higher version of binderhub/r2d

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#390]
Users that deploy a BinderHub may want to upgrade to newer dev versions of `binderhub` or `repo2docker`...we should include information in the docs about how to do this. Would this be done by asking people to re-run `helm install` with a new `--version` argument, or would it be in a config file?

**Comment by manics** [comment]
https://github.com/jupyterhub/mybinder.org-deploy is an example, and we're planning on more frequent releases of repo2docker. I'll close this but feel free to update the docs if still needed.
