### ISSUE TITLE
Decide on what to do for default when there is no build pack detected

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#40]
For a lot of repositories there's no requirements.txt or environment.yaml file.

We should decide what to do in these cases.

**Comment by yuvipanda** [comment]
I think we should just launch a minimal python3 environment, and make that visible to the user (suggested by @willingc).

**Comment by yuvipanda** [comment]
Deployed now

**Comment by willingc** [comment]
Yay!!!!!! :cake: :tada: 🍨 🍨 and more 🍦
