### ISSUE TITLE
v0.1 release

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#400]
## Current plan
- BinderHub begins "releases" - next release is v0.1
- BinderHub docs / install instructions are tagged to these releases too
- `mybinder.org` continues to operate on `master`

At the last meeting we discussed that it will be helpful to begin making BinderHub releases. This makes it easier for us to guarantee similar experiences between deployments of BinderHub, and adds some stability to the set of features users can expect.

Let's use this issue to discuss major changes / issues that we'd like to see in this release. I've re-purposed our beta milestone to reflect this, so please add pre-existing issues there:

https://github.com/jupyterhub/binderhub/milestone/1

**Comment by yuvipanda** [comment]
I think my binder.org should continue to be deployed close to master like
we have now. Releases should be for other people to use, rather than for
the mybinder.org deploy. We could / should probably do a release every two
months or so, that is too long a time to wait between deploys...

Other than that, +1.

**Comment by choldgraf** [comment]
Fair enough - we just need to make sure that it's clear to users that `mybinder.org` is running the latest dev version, otherwise we'll get confused users who follow the instructions and don't understand why their version of binder is different from what's on `mybinder.org`

**Comment by choldgraf** [comment]
ok, I've updated the top-level comment to match our current milestone (v0.1)

**Comment by choldgraf** [comment]
@yuvipanda is this something that can happen independently of #435 (merging bhub and jhub helm charts?) I think so since we'll still keep the BinderHub repo for the python code etc, yeah? Then the BinderHub docs will just mention a specific version of the jupyterhub helm chart

**Comment by choldgraf** [comment]
Ping on this one to make sure everyone is happy with the list of items in the v0.1 milestone:

https://github.com/jupyterhub/binderhub/milestone/1

please feel free to edit/add/comment/etc! cc @jupyterhub/binder-team

**Comment by choldgraf** [comment]
done! outstanding issues are moved to v0.2 and we now have a v0.1 release, so closing this!

https://github.com/jupyterhub/binderhub/releases/tag/0.1.0
