### ISSUE TITLE
Need to run `npm run webpack` before dev now?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#403]
Now that #372 is merged, I found that Binder wouldn't build locally anymore because of a `<script>` loading error. I looked at the travis build and noticed that it runs `npm run webpack`. After I ran this, Binder displayed properly.

Is this something that will need to happen (`npm run webpack`) everytime the javascript changes? Either way, we should document this in `CONTRIBUTING.md` yeah?

**Comment by Carreau** [comment]
Got bitten by that as well. I'm wondering if we could hook also the Tornado autoreload to rebuild as well.

**Comment by minrk** [comment]
> Is this something that will need to happen (npm run webpack) everytime the javascript changes?

Yes, exactly right.

>  I'm wondering if we could hook also the Tornado autoreload to rebuild as well.

Possibly, though it's very slow so you wouldn't want to do it unless you are actively working on the js. Probably a separate `webpack watch` is what we want for those working on js.
