### ISSUE TITLE
Ocassionally Flaky CI

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#410]
Sometimes CI fails because of an error like:

```
binderhub/tests/test_build.py::test_build[gh/binderhub-ci-repos/requirements/d687a7f9e6946ab01ef2baa7bd6d5b73c6e904fd] JupyterHub not available at http://127.0.0.1:30123: HTTPConnectionPool(host='127.0.0.1', port=30123): Read timed out. (read timeout=5)
ERROR [ 11%]
```

Restarting usually fixes it. This is quite annoying and needs to be looked into.

**Comment by willingc** [comment]
[Pastebin of detailed Travis log](https://pastebin.com/GZyiG4sj)

**Comment by yuvipanda** [comment]
@willingc nice! Although the errors I saw were for test-helm, rather than test-main I think! But definitely seen both flake.
