### ISSUE TITLE
BinderHub v0.1 on JOSS

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#421]
Per https://github.com/jupyterhub/binder/issues/48 we decided that a good first step for citation is to submit a JOSS article for BinderHub. It seems to me that v0.1 is a good candidate for this.

Does anybody have any qualms with me putting together a JOSS proposal that we can review/submit *after* we release v0.1? That way we'll be able to give people something citable for Binder.

## Relevant links
* [the jupyter guidelines](https://github.com/jupyter/governance/blob/master/papers.md#process-for-journal-of-open-source-software-joss) for JOSS.
* [the JOSS author guidelines](https://joss.theoj.org/about#author_guidelines)

**Comment by ellisonbg** [comment]
I am +1 with that. My only comment is that we should be clear about the authorship criteria and responsibilities.

**Comment by choldgraf** [comment]
good point @ellisonbg - I added a link to the Jupyter JOSS guidelines in the top comment

**Comment by choldgraf** [comment]
OK, added https://github.com/jupyterhub/binderhub/pull/428

**Comment by jzf2101** [comment]
I don't see the paper?

**Comment by manics** [comment]
Closing for the same reasons as in https://github.com/jupyterhub/binderhub/pull/428
