### ISSUE TITLE
BinderHub + JupyterHub Scipy 2018 Talk/Poster Proposal

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#422]
### [Click here](https://hackmd.io/MYDg7AzAnALAjBAtAVgKYCMqJhAJgNkRH2QAZFVgpcoRlh9c4Yg=) to make additions/comments/edits on the SciPy proposal

The scipy 2018 deadline for talks/proposals is **February 15th**.

Submission guidelines page:  https://scipy2018.scipy.org/ehome/299527/648140/

This issue is meant for discussing a submission for a talk/proposal for SciPy 2018.

**Comment by betatim** [comment]
Don't think I will make it to SciPy. Going to fly the binder flag in Europe though.

**Comment by choldgraf** [comment]
sounds good! I think that a lot of work can also just go into general tutorial materials etc that we can reuse for a number of different events

**Comment by mpacer** [comment]
Submissions are actually February 9th. I'm interested in being involved with this.

**Comment by yuvipanda** [comment]
Happy to help with specific questions, but I don't think I'll have time to be super involved!

**Comment by willingc** [comment]
Happy to help on the slide deck and review proposal. I'm not sure if I will make SciPy this year. We may be doing some outreach classes at Cal Poly this July :-)

**Comment by choldgraf** [comment]
Hmmm, I'm not sure we'll have the representation of people at scipy to be able to do this. I assume we need at least 2 folks there.

I might go, but it depends on how much other stuff I have going on that summer. Is anybody on the Binder team _definitely_ going to scipy that would like to help give a tutorial? @mpacer you mentioned you're interested in being involved, does that == "giving the tutorial" or are you going to be busy with organizing the conference?

**Comment by choldgraf** [comment]
going once, going twice? I don't think we should commit ourselves to giving a tutorial at a conference if we aren't sure we'll have the #s to attend...

**Comment by mpacer** [comment]
Alright. So I was talking with @choldgraf on slack and had an idea that given the limited number of people who may be in attendance, it may make more sense to propose a talk/poster on Binderhub/repo2docker. 

In addition to the talk/poster, we would submit a paper to the proceedings. 

The topic of the paper would differ from a JOSS paper, instead it would focus on the research angles of the projects. The nature of the problem and the design decisions that were made when organising the libraries in order to achieve the desired performance characteristics. Analytics (including some nice figures) would be good for that as well.

**Comment by choldgraf** [comment]
I think that sounds like a good idea to me - we don't have a reliable guess on whether enough people will attend for a tutorial, and could use a longer form paper for people to cite Binder. I'm happy to help out with writing etc, and if I end up attending scipy could give a talk or something (we already have a few talks sitting around that we could use).

To me the big question is what kind of scope to put around a paper or talk. There's JupyterHub / repo2docker / the helm charts / the specific instance on `mybinder.org`. What would make for a compelling narrative? Anybody have ideas? Or maybe we can discuss @ the team meeting?

**Comment by mpacer** [comment]
> To me the big question is what kind of scope to put around a paper or talk. There's JupyterHub / repo2docker / the helm charts / the specific instance on mybinder.org. What would make for a compelling narrative? Anybody have ideas? Or maybe we can discuss @ the team meeting?

I was specifically suggesting that we focus on the design decisions of the two libraries (binderhub and repo2docker). It probably wouldn't make sense to talk about those without covering some aspects of JupyterHub as well… but I figured that that could be (and has been?) a talk in its own right and so shouldn't be the main focus. I'm thinking the analysis of the specific service itself plays the role of the "results" section of the paper. I don't know enough about the helm charts to know what role they would have in this narrative.

**Comment by choldgraf** [comment]
Updated the top-level comment with more up-to-date info. Specifically, note that since we're now planning on a talk/poster we have until **February 9th** to submit. I can put together sometime that we can discuss @ the group meeting and we can plan to submit on the 9th in true fly-by-the-seat-of-our-pants academic fashion :-D  If somebody else would like to put together this proposal, that'd be great too!

**Comment by choldgraf** [comment]
Note we now have until **February 15th** to submit (I'll update dates above accordingly)

**Comment by choldgraf** [comment]
Hey all - I've created a hackmd where people can make additions/edits/comments to the SciPy proposal:

https://hackmd.io/MYDg7AzAnALAjBAtAVgKYCMqJhAJgNkRH2QAZFVgpcoRlh9c4Yg=

**anybody should feel free to contribute!**

If someone would like to start a draft, you might wanna check out the [JOSS proposal](https://hackmd.io/BwZgJmDGBsCcYFoCGAzEBGBAWWKBGySArJgAxhJ4CmY0II0qQA==) to mine some content.

**Comment by choldgraf** [comment]
Just a note that @mpacer added a bunch of great content in the form of an outline! I took a quick pass at re-organizing today, can take another pass tomorrow. If folks have thoughts etc, please do jump in!

**Note: we have 3 days to submit this proposal!**

https://hackmd.io/MYDg7AzAnALAjBAtAVgKYCMqJhAJgNkRH2QAZFVgpcoRlh9c4Yg=

**Comment by mpacer** [comment]
The notes were quickly jotted down during a conversation with @minrk. I'm sorry you had to wade through that which had been in an unstructured form.

I think some of these stuff that had been there wasn't useful due to the later portions of the conversation. I had intended to sort through that… Is there a way to look at the history so I can see the state from before your changes? I think your changes were probably good but they eliminated some of the mental road-signs I had been using to determine what was and what wasn't useful…

**Comment by choldgraf** [comment]
ah my bad, I didn't realize you didn't want folks to make edits to that - was just trying to be helpful :-/

I'll hold off on any more edits until somebody mentions that it's open for a round of edits etc!

**Comment by mpacer** [comment]
No, it's good now & open for edits! Because you had edited it, it's now much more interpretable! Thank you @choldgraf for all your hard work (& I'm still sorry for having made it necessary).

**Comment by mpacer** [comment]
Hi @choldgraf @minrk I took a stab at reworking the the description to be further away from a generic Binder talk (which wasn't obviously differentiated from the original SciPy Binder talk) and tried to focus more on repo2docker and BinderHub as being newly developed components of the larger system which has been improved for large scale maintainability and deployment improvements. 
I would appreciate feedback! 

If people have ideas as to what details to go into for the long description, that would also be great.

Also, @choldgraf will you be at SciPy this year? If so I'd imagine putting credentials for you, @minrk (who mentioned explicitly that he would be at SciPy), and I… is there anyone else? I don't want to leave anyone out.

**Comment by mpacer** [comment]
Hello all, please see the hackmd at https://hackmd.io/MYDg7AzAnALAjBAtAVgKYCMqJhAJgNkRH2QAZFVgpcoRlh9c4Yg=?

Unless someone wishes to make specific changes, I'm going to be submitting this version around 23:00 PST tonight.

**Comment by mpacer** [comment]
I have made a https://github.com/jupyterhub/jhub-proposals/pull/1 to record the version that I am preparing to submit. Any changes will be made as a modification to the one in that PR.

**Comment by betatim** [comment]
Congrats on the submission! Fingers crossed it gets picked. Going to close this.
