### ISSUE TITLE
Adding the sphinx-gallery Binder button to Matplotlib

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#423]
Now that Sphinx Gallery has a Binder button prototype in there, I'd like to start making PRs to add it to websites that already use sphinx-gallery. I was going to start with Matplotlib, since it has the largest reach. However, looking at the numbers I'm a bit worried that we'll end up saturating our traffic.

I took a look at the matplotlib daily traffic over the last few months **only for pages within `/gallery/`**, and it hovers somewhere around 10,000 users a day. If we assume that 1% of people actually *click* on a Binder link within those examples, that's still 100 extra users per day.

Currently we're hovering at around 800 hits/day to `mybinder.org`. That means if we start getting an extra 100 a day from another source, that's a 12% increase from a single source.

So, I wanted to open this issue to make sure we're cool with that. It's kind of a double-edged sword, since obviously a 12% bump in traffic would be awesome. But I want to make sure it doesn't bring the cluster down to a halt...

what do folks think?

**Comment by yuvipanda** [comment]
This should probably be in the mybinder.org-deploy repo :)

**Comment by choldgraf** [comment]
good point

**Comment by choldgraf** [comment]
https://github.com/jupyterhub/mybinder.org-deploy/issues/298
