### ISSUE TITLE
Document how to develop BinderHub using the GKE cluster for testing

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#426]
Sometimes it's a pain in the butt to set up minikube etc on your own machine (sorry windows users), but it *should* be possible to develop locally and have BinderHub point to a pre-existing kubernetes cluster on GKE. We should document how to do this in the `CONTRIBUTIND.md` doc

**Comment by manics** [comment]
Do you think we still need to do this?

**Comment by choldgraf** [comment]
I think we should close this, as the demand hasn't come up since this was opened
