### ISSUE TITLE
JupyterCon talk on BinderHub

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#446]
We should have a talk at JupyterCon:
* around BinderHub internals and how it works,
* a bit of a Roadmap ('State of BinderHub' maybe?). This might include repo2docker - but
* repo2docker might also be a talk by itself.

This would be separate from the mybinder.org deployment, which has an issue tracking it in https://github.com/jupyterhub/mybinder.org-deploy/issues/344

[Here's a HackMD](https://hackmd.io/IwNgzApgRgJg7AVgLQgGYA5kBZ3Dk9EOYJYAJihCiwTDnQE4wg==#) to discuss a "past/present/future of BinderHub" talk

**Comment by yuvipanda** [comment]
This is one (or two!) talks that I hope someone other than me signs up for!

**Comment by betatim** [comment]
Can I edit your top comment into a bullet point list of topics per talk?

**Comment by yuvipanda** [comment]
@betatim feel free!

**Comment by betatim** [comment]
I'd be interested in "state of binderhub" and ideally would like to find a conspirator to form a double act with.

**Comment by choldgraf** [comment]
I like "state of BinderHub" too - could be similar to the [past, present, and future of jupyterhub](https://drive.google.com/open?id=1PTFdG1IdAmftXbRLqvOqlE38nKNTjGYgsLlaEgRwCK0) talk I gave at the MSDSE summit this year

**Comment by betatim** [comment]
I find "State of bhub" a bit of an awkward title, I think I like your "past, present and future" better.

Maybe we can [HackMD it](https://hackmd.io/IwNgzApgRgJg7AVgLQgGYA5kBZ3Dk9EOYJYAJihCiwTDnQE4wg==#)

**Comment by choldgraf** [comment]
+1 to a hackMD (I added a link to the top-level comment)

**Comment by willingc** [comment]
Closing here as this was covered by the issue in the team-compass repo.
