### ISSUE TITLE
Automatically pull git submodules?

### ISSUE THREAD

**Issue by kmader** [jupyterhub/binderhub#447]
I used submodules in my [repository](https://github.com/kmader/webdnn_binder) and I had to add a [line to the postBuild](https://github.com/kmader/webdnn_binder/blob/9e6043c13d38bc512d37e8faff889f7dec928b58/postBuild#L1) for the submodules to be pulled as well. 
```
git submodule update --init --recursive
```

It seems like better form to have this be automatic (since the folders for the submodules still show up but are simply empty).

**Comment by minrk** [comment]
Yup, `git clone` should ~always be `git clone --recursive`. Fixed by https://github.com/jupyter/repo2docker/pull/233
