### ISSUE TITLE
Add the ref to "launch" events?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#452]
I was looking through the prometheus launch events, and wonder if it'd be relatively easy to add the label pod to each one:

e.g., couldn't we add something like `ref=self.key` (after adding `key` to `self`) here:

https://github.com/jupyterhub/binderhub/blob/9d91e12f4f9c1e0c53f0c305a3e634388d48db98/binderhub/builder.py#L388

(here's `key`: https://github.com/jupyterhub/binderhub/blob/9d91e12f4f9c1e0c53f0c305a3e634388d48db98/binderhub/builder.py#L168)

that way we could see if there are particular repos that are causing super long build times, and we could also quantify the number of launches for each repo...

**Comment by yuvipanda** [comment]
Nope, because you'll end up blowing through our resources pretty quickly. Each combination of metric keys will create a new metric, and if you add ref that's pretty much infinite numberof metrics. So we can't do that without slowing prometheus to a crawl.

https://prometheus.io/docs/practices/naming/ has more info.

**Comment by yuvipanda** [comment]
Specifically, from https://prometheus.io/docs/practices/naming/#labels:

> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/mybinder.org-deploy/issues/97 or similar is the work needed for us to actually be able to gather this data.

**Comment by choldgraf** [comment]
ah ok :-( 

I'm gonna remove all of that part of https://github.com/jupyterhub/binderhub/pull/453 then
