### ISSUE TITLE
When I can't access a pod, tell me how to create a new pod from the same public repo

### ISSUE THREAD

**Issue by das-g** [jupyterhub/binderhub#458]
(originally suggested [on Twitter](https://twitter.com/RaphaelDasG/status/964641858054844419))

When someone [has published a personal pod URL<sup>1</sup>](https://twitter.com/pythonsummit/status/964442816637296640) (or has shared it with me, see #160), I won't (and probably shouldn't) be able to access that pod.

Chances are, that they didn't want to give me access to their personal pod, but instead to a new pod based on the same publicly hosted notebook file or repo, which they could have achieved by sharing the ["binder link"<sup>2</sup>](https://mybinder.readthedocs.io/en/latest/introduction.html#generating-a-sharable-binder-link).

Thus, the error page I land on when following the pod URL should explain the difference between these two (if possible, without requiring prior knowledge of kubernetes lingo or other implementation details) **and tell me where to get to a new pod for that notebook file or repo** (i.e. the corresponding sharable binder link).

(Could be combined with #457, but either suggestion could be implemented without the other, so I'm filing them as separate issues.)

---
<sup>1</sup>On the mybinder service, an URL beginning with <code>https://<strong>hub.</strong>mybinder.org</code> &hellip;
<sup>2</sup>On the mybinder service, the URL of form `https://mybinder.org/v2/<provider-name>/<org-name>/<repo-name>/<branch|commit|tag>?filepath=<path/to/notebook.ipynb>`

**Comment by choldgraf** [comment]
ah this is a great point IMO - the challenge I think is that this token page is being served from the _jupyterhub_ side. @minrk is there a way to define custom templates for things like the "input your token" hub page? I think we could clear up a lot of confusion with a more helpful error message.

**Comment by das-g** [comment]
For me, it doesn't say "input your token", it says "403 : Forbidden".

**Comment by minrk** [comment]
Yes, we can make a custom template for the login page. Here's [an example](https://github.com/minrk/binder-template-example) that replaces the token page with a link to the original binder URL. What we need to do:

1. create custom template files
2. load the binder URL into the env
3. add to /etc/jupyter/jupyter_notebook_config to load the custom templates and binder URL

We ought to be able to do this via the new [appendix](https://github.com/jupyter/repo2docker/pull/226) arg to repo2docker.

**Comment by minrk** [comment]
Thinking about how to do this in practice, adding files via the appendix is a bit tricky. RUN is easy, but ADD isn't since we don't have a way to affect the build context. One way to do it is to clone the appendix and do it all via RUN. We could make the binder appendix its own repo, or we could put it in this repo, which would make it easier to keep everything in sync:

```python
appendix="""
USER root
ENV BINDER_URL={binder_url}
RUN cd /tmp \
 && wget {binderhub_archive_url} -O binderhub.tar.gz \
 && tar -xzf binderhub.tar.gz appendix \
 && ./appendix/appendix.sh \
 && rm -rf binderhub.tar.gz appendix
USER $NB_USER
""".format(
  binderhub_archive_url='https://github.com/jupyterhub/binderhub/archive/abc123.tar.gz',
  binder_url='https://mybinder.org/v2/gh/foo/bar/ref',
)
