### ISSUE TITLE
Set up doctr w/ the jupyterhub account to auto-build the docs

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#46]
I just realized that the docs that are being served on the website are really outdated. I've updated them with a push to gh-pages, but we should get doctr set up to auto-build with travis so we don't need to think about this. I could set it up myself but then it'd be tied to my github account, I think it'd be better if the `jupyterhub` account were building. What do folks think?

**Comment by willingc** [comment]
Let's build and host on RTD. I'm fine with it being hosted elsewhere as well.

**Comment by willingc** [comment]
RTD link: https://binderhub.readthedocs.io

This will build and deploy on each PR merge. I've made @choldgraf, @yuvipanda, and @minrk maintainers on RTD.

**Comment by choldgraf** [comment]
ah yep, that's right I forgot we were using RTD :)

**Comment by choldgraf** [comment]
and that will be auto-built when we push changes do `doc`?

**Comment by willingc** [comment]
Yes, any change to source files in the `doc` directory will build on RTD. It's totally cool to have both places for the docs since the same will be built on each.

**Comment by yuvipanda** [comment]
Going to close this since I am guessing we'll just use RTD for now :)
