### ISSUE TITLE
delete of multiple files throws errors 

### ISSUE THREAD

**Issue by fomightez** [jupyterhub/binderhub#471]
This happens once an instance is running from MyBinder. If you go to the Jupyter dashboard where the Jupyter UI lists files for the typical launched notebooks (not JupyterLab), if you try to delete more than one file, you get an error "Forbidden".

Tim Head was actually unclear on where to file but suggested here first.
>humm. actually not sure where that should be filed as error, binderhub or the notebook, probably best to start with binderhub.

(Workaround is to delete in the terminal or using exclamation and command in the notebook. Or use python in the notebook.)

**Comment by betatim** [comment]
A super simple repository like https://mybinder.org/v2/gh/terna/pandas-datareader/master also reproduces this bug. Trying to delete even a single file leads to the following error:

> Traceback (most recent call last): File "/srv/venv/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute result = yield result File "/srv/venv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run value = future.result() File "/srv/venv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) File "<string>", line 4, in raise_exc_info File "/srv/venv/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper yielded = next(result) File "/srv/venv/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 235, in delete yield gen.maybe_future(cm.delete(path)) File "/srv/venv/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 278, in delete self.delete_file(path) File "/srv/venv/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 499, in delete_file send2trash(os_path) File "/srv/venv/lib/python3.6/site-packages/send2trash/plat_other.py", line 185, in send2trash dest_trash = find_ext_volume_trash(topdir) File "/srv/venv/lib/python3.6/site-packages/send2trash/plat_other.py", line 145, in find_ext_volume_trash trash_dir = find_ext_volume_fallback_trash(volume_root) File "/srv/venv/lib/python3.6/site-packages/send2trash/plat_other.py", line 139, in find_ext_volume_fallback_trash check_create(trash_dir) File "/srv/venv/lib/python3.6/site-packages/send2trash/plat_other.py", line 84, in check_create os.makedirs(dir, 0o700) File "/usr/lib/python3.6/os.py", line 220, in makedirs mkdir(name, mode) NotADirectoryError: [Errno 20] Not a directory: b'/home/jovyan/README.md/.Trash-1000' 

(the formatting is already screwed up in the notebook UI) Two questions: does anyone remember having successfully deleted files via the UI before? I have never tried, so this might not be a new bug but one that was there all along. If this used to work, ideas on what got changed to get us started tracking this down?

**Comment by betatim** [comment]
The error is in `send2trash` and they released a new version a few days ago, but `pip show send2trash` on the example repo above says we are still on 1.4.2 from November 2017.

However https://github.com/hsoft/send2trash/compare/1.4.2...master suggests that @takluyver fixed something related to permissions exactly where this error is coming from. I'd suggest we make a PR to https://github.com/jupyter/repo2docker to upgrade `send2trash` to the latest version and see what happens.

**Comment by takluyver** [comment]
It's probably going to need a new release of notebook as well to take
advantage of the changes in send2trash.

**Comment by betatim** [comment]
Related https://github.com/jupyterhub/jupyterhub/pull/1688

I think that PR (once it gets deployed) should fix this?

**Comment by takluyver** [comment]
Yup, if send2trash is disabled, this shouldn't come up.

**Comment by manics** [comment]
Sounds like this wasn't a BinderHub bug.
