### ISSUE TITLE
Consider including the grafana / prometheus helm charts in the base binderhub chart

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#478]
One of our grant deliverables is "Provide user-facing UI for statistics and Binder health monitoring". I think at the time we imagined creating these stats ourselves, but I think it's clear that grafana/prometheus is the easiest solution and we don't wanna re-create the wheel.

Could we make it easier for people to deploy their own grafana/prometheus services by including those charts in the binderhub meta chart w/ reasonable default configuration in the helm chart? If that was done, I think we could consider this deliverable "delivered"

**Comment by minrk** [comment]
And if not in the chart itself, include getting all the way to grafana + prometheus as siblings to binderhub in the docs.

**Comment by jhamman** [comment]
Is there any documentation at the moment for how you all configured grafana for mybinder.org?

**Comment by betatim** [comment]
The helm chart for mybinder.org is in https://github.com/jupyterhub/mybinder.org-deploy/ which includes the grafana+prometheus configs.

**Comment by manics** [comment]
I think https://github.com/jupyterhub/mybinder.org-deploy/ is good enough
