### ISSUE TITLE
Using a non-gcr.io registry

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#486]
We should document how to use a registry other than `gcr.io`. I think giving DockerHub as an example should suffice here. From the suggestion that @willingc gave, I believe we need to tell people how to fill in this part of the chart:

https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/values.yaml#L26

With the right values for DockerHub. In particular, we also need to give context for what this "JSON authentication" is which I believe is explained here:

https://docs.docker.com/engine/reference/commandline/login/#privileged-user-requirement

does this look correct?

cc @minrk

**Comment by willingc** [comment]
A few more links from the gitter discussion:

DockerHub for the registry, but these docs look pretty good: https://docs.docker.com/registry/deploying/

Probably user set in values.yaml and credentials in secrets.yaml under registry. https://binderhub.readthedocs.io/en/latest/setup-binderhub.html#create-secret-yaml-file

**Comment by minrk** [comment]
From what I recall from working on #342 we make assumptions about how auth works with gcr.io that's not generalized to other registries. I know that local un-authenticated registries won't work without changes there. I haven't tried with the DockerHub registry, so it might be that it does work and we need to be clear what config to use, or it's possible that we need to make some changes. It should be a matter of testing with the hub.docker.com and documenting and/or fixing what's needed. We definitely need changes to allow the local wide-open registry case, though.
