### ISSUE TITLE
build logs of a repo are not displayed properly in binder

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/binderhub#487]
Hi, we have deployed our own binder and it is running here: https://notebooks.gesis.org/binder/

Currently we have a problem with build logs. When we put the repo link and launch, for long time we don't get any build logs. They all appear at once when the build is done. When I check logs of binder pod, there is "WARNING Connection pool is full, discarding connection", which must be related to this problem. 

For example, you can try with this repo https://github.com/binder-examples/appmode and you will see that all logs appear just before redirection to the new launched server.

As @choldgraf said on gitter channel, you had this problem before. I would like to what was the reason and how did you fix it?

Thanks a lot

**Comment by betatim** [comment]
I think "WARNING Connection pool is full, discarding connection" is a "known to be harmless warning" (which is suboptimal). There are many of these in the mybinder.org logs as well.

Copying over some information from gitter: notebooks.gesis.org runs https://github.com/jupyterhub/helm-chart/blob/gh-pages/binderhub-0.1.0-0bb083d.tgz Do you remember the last version before this that worked?

When I try and build a repo on your instance I get errors about not being able to connect to the event stream in the console. Could it be a particular HTTP proxy setup that is causing this?

**Comment by bitnik** [comment]
Thanks a lot for checking this.

Unfortunately no, I don't exactly know when it worked last time. But I can go through the history of our helm config file and on staging deploy each version we already had. Would that help?

And which repo did you try to build on our instance? Where did the error appear exactly? Weird, I have never seen it before.

**Comment by bitnik** [comment]
I still don't get that error but you are right. When I try to build with notebooks.gesis.org:<binder_node_port>/binder/ and bypass reverse proxy (nginx), logs work without problem. Do you have any advice how we should proceed to solve this?

**Comment by bitnik** [comment]
hey, it is solved. problem was proxy buffering of nginx. I set `proxy_buffering off;` inside binder location in nginx conf and it works again :) Thanks a lot for pointing the problem!
