### ISSUE TITLE
Customizing hostname for jupyterhub companion

### ISSUE THREAD

**Issue by djsegal** [jupyterhub/binderhub#494]
How do you change the hostname for a jupyterhub companion?

Let's say you have:
+ a binderhub at `XX.XXX.XXX.XX`
+ a jupyterhub at `YY.YYY.YYY.YY`

How do you make it so a domain:

+ `example.com` points to `YY.YYY.YYY.YY`
+ and have the binderhub correctly redirect to it?

**Comment by choldgraf** [comment]
I believe this is exposed via helm chart configuration...the clearest way to see it's use is by checking out the `mybinder.org` helm chart: https://github.com/jupyterhub/mybinder.org-deploy/blob/master/config/prod.yaml#L17

It is annoyingly not documented well though...the Binder deployment docs are more "alpha" whereas the service itself is "beta" :-)

**Comment by djsegal** [comment]
Fair enough. Got it to work
