### ISSUE TITLE
Helm keeps uninstalling on Google cloud

### ISSUE THREAD

**Issue by djsegal** [jupyterhub/binderhub#496]
I setup a binderhub exactly as given in the docs.

However, once I want to change something the **next day**, I get a `helm not found` error:

```
myusername@google-project:~$ helm install jupyterhub/binderhub --version=v0.1.0-e54c217 --name=binder --namespace=binder -f secret.yaml -f config.yaml
-bash: helm: command not found
```

----

The way I've tried to circumvent the problem previously is reinstalling `helm` through:

+ `curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash`

However, this then breaks my binder build 

// and I have to try over from scratch on a new gmail account 😢

-----

i.e. you get the following error on binder right after the docker image is built 

(but before its saved & deployed)

```
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Built image, launching...
Launching server...
Failed to create temporary user for gcr.io/google-project/binder-prodmyusername-2dwebio-2dbinder-8s3d52:2f02w41sdv123caser512
```

**Comment by willingc** [comment]
Hi @djsegal,

I think you may not have the PATH to helm set in your bash config. 

- If you type, `helm version` do you get any output or not found?

- `which helm` should display where in your filesystem helm is installed.

**Comment by djsegal** [comment]
Just so we're on the page, we're talking about:

+ `helm` not working the next day on a `Google Cloud Shell machine`
+ at https://console.cloud.google.com/home/dashboard

-----

it appears that:

`curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash`

leads to:

```
> which helm
/usr/local/bin/helm
```

**Comment by willingc** [comment]
Thanks for clarifying that you are using the console within Google Cloud.

[Reference - see Step 4](https://cloud.google.com/solutions/deploying-memcached-on-kubernetes-engine)

> This command makes the helm binary discoverable from any directory during the current Cloud Shell session. To make this configuration persist across multiple sessions, add the command to your Cloud Shell user's ~/.bashrc file.

**Comment by djsegal** [comment]
Wooooo. Thanks!

**Comment by djsegal** [comment]
Is there a way to add this to the docs, so everyone doesn't get tripped up by it?

**Comment by willingc** [comment]
Sure @djsegal. Do you wish to create a PR or open an issue and indicate where the text would be helpful? Thanks.

**Comment by djsegal** [comment]
On, https://binderhub.readthedocs.io/en/latest/create-cloud-resources.html#installation

Right below:

> The simplest way to install helm is to run Helm’s installer script at a terminal:
>
> `curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash`

Mention something along the lines of:

To add helm to the cloud console's permanent load path, setup a `bashrc` file:

`touch ~/.bashrc; echo "PATH=$PATH:/usr/local/bin" >> ~/.bashrc

-----

As an aside, it is also confusing why you don't just do:

```
helm init --service-account tiller
```

Right after installing `helm` with `curl`

**Comment by djsegal** [comment]
Wrapping this up. Don't use `helm` on google cloud console. 

Just do it on your laptop.
