### ISSUE TITLE
Blog post 

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#50]
Probably going to riff off of Andrew's original blog post:

https://elifesciences.org/labs/a7d53a88/toward-publishing-reproducible-computation-with-binder

Once we announce the beta we should partially do so with a blog post on the jupyter website, twitter, etc. Here are some things to mention:

* Principles behind the changes
* Technical backend differences
* What's different between current and previous from a user perspective
  * New URL structure
  * The initial environment is different
  * Be more specific / complete about your requirements
  * No more manual building, it gets automatically rebuilt if someone clicks a link
  * This means that if you push to master it'll now automatically get rebuilt
  * However now you can point it to a specific hash / tag / branch
  * It should be much faster after the initial build
* Public grafana dashboard
* Hardware restrictions for users
* Link to documentation for new deployments
* Future development stuff
  * R support

Suggestions from other folks? @yuvipanda @willingc @minrk ?

**Comment by willingc** [comment]
cc @parente @rgbkrk fyi

**Comment by choldgraf** [comment]
closing for https://github.com/jupyterhub/binder/issues/22
