### ISSUE TITLE
LOADING.md - Implementation specifications needed

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#501]
I was thinking that temporarily showing a server-detached notebook rendering using nbviewer might be appreciated when a specific notebook file to be loaded is known (when a index.ipynb exist or the filepath query param is set for example).

I really appreciate the interactive fun graphics as it is now though, but at the same time a web developer friend recently told me about how Amazon had concluded that every 100ms of loading made them loose a lot of users. This idea might be a way to combat the comparably huge loading time.

Another idea would be to support the choice of some loading screen content based on a file in the repo named "loading.ipynb" or similar, or perhaps by some setting file.

**Comment by minrk** [comment]
That's a very interesting idea! Running nbconvert on binder might be a level of complexity we aren't prepared for *yet*, but it could be a nice feature.

**Comment by betatim** [comment]
Could we use an iframe with nbviewer inside? Downside is that we now depend on an external service, upside is that the additional complexity for mybinder.org is low.

**Comment by choldgraf** [comment]
I'm +0 on this, leaning towards -.1 :-) 

The mean reason other than the increase in complexity is that I think a big feature of Binder is precisely that it *doesn't* make a ton of special assumptions about the workflows we're enabling. When I tell people "you can totally run RStudio, JupyterLab, OpenRefine, etc" in Binder they think it's really cool, so I'm a bit hesitant to start treating notebooks as "special" relative to all the other workflows that are out there...

**Comment by consideRatio** [comment]
That is a point that makes a lot of sense to me @choldgraf !

What about being able to have a rendered "LOADING.md" provided by the repo or similar shown during loading? I'm just tossing the ideas out here for more than me to process.

**Comment by choldgraf** [comment]
`LOADING.md` sounds cool! It'd also be cool if you could make it a gif or something like this. I'm not sure from a technical perspective how difficult it'd be though...

**Comment by minrk** [comment]
LOADING.md is cool, but we should be careful if it can do things like reference other files in the repo (e.g. a relative URL for an inlined screenshot). That can get tricky real quick because to fully render the markdown, we need to have URL handlers that serve the whole repo as static files (this is a significant fraction of what nbviewer does).

**Comment by choldgraf** [comment]
So, are we +1 on `LOADING.md`? If so, @consideRatio could you edit the top-level comment / issue title (or open a new issue) with this more actionable path forward? :-)

**Comment by consideRatio** [comment]
#### TODO
- [ ] Specify the wanted behavior of LOADING.md

**Comment by consideRatio** [comment]
The idea of LOADING.md introduced complexity, and was resolved better with #593.
