### ISSUE TITLE
Internal Server Error while building docker image of github repo with binderhub via google cloud kubernetes

### ISSUE THREAD

**Issue by lalwanigunjan** [jupyterhub/binderhub#503]
Cannot build docker image of github repository.
It says "Internal Server Error"
Please help with the same.

**Comment by choldgraf** [comment]
Can you give more information about your deployment as well as a link to a
github repository you're trying to build?
--

**Comment by lalwanigunjan** [comment]
https://github.com/lalwanigunjan/AdsTeam6Presentation 
I followed all the steps mentioned in binderhub docmentation right from  Setting up Kubernetes on Google Cloud
https://binderhub.readthedocs.io/en/latest/

**Comment by minrk** [comment]
Can you include the logs of the binder and/or hub pod that include the error?

**Comment by lalwanigunjan** [comment]
Error from server (NotFound): services "binder-binderhub" not found

![image](https://user-images.githubusercontent.com/34087129/37857606-d6115564-2ed2-11e8-9e07-d5bf0b32c864.png)

**Comment by choldgraf** [comment]
Hi @lalwanigunjan , we are talking about the logs from your kubernetes pod that is running `binder-` or `hub-`.
