### ISSUE TITLE
Error: watch closed before Until timeout

### ISSUE THREAD

**Issue by Emaasit** [jupyterhub/binderhub#520]
I followed the "CONTRIBUTING.md" instructions to install binderhub locally. When I ran this command:

`helm install --timeout=1000000 --name=binder-test-hub jupyterhub/jupyterhub --version=v0.7.0-f58c7e7 --namespace=binder-test -f /Users/demaasit/binderhub/testing/minikube/jupyterhub-helm-config.yaml`

I get the following error:

`Error: watch closed before Until timeout`

Should I increase the "VERY-LARGE-NUMBER" in `--timeout=1000000`?

**Comment by Emaasit** [comment]
Yes, locally on minikube on my Mac OS.

**Comment by minrk** [comment]
You could also try removing the timeout arg.

**Comment by choldgraf** [comment]
@Emaasit did removing the `--timeout` arg solve this for you?

**Comment by ryanlovett** [comment]
Fwiw, I saw this error with JupyterHub on AKS with a very large --timeout. There were hook-image-puller pods left running. When I ran without --timeout, helm install quickly succeeded.

**Comment by manics** [comment]
Hi :wave: This is an old issue so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
