### ISSUE TITLE
No feedback why launch fails

### ISSUE THREAD

**Issue by jdemeyer** [jupyterhub/binderhub#522]
While there are plenty of logs while *building* docker images for binder, there are no logs at all while *launching* the image. I only get
```
Found built image, launching...
Launching server...
Image gcr.io/binder-prod/r2d-05168b0-jdemeyer-2dpep575binder-097db3:a4fc44a26cd379aceddb739168a4267338707da3 for user jdemeyer-pep575binder-0fukjo5h took too long to launch
```

In this case, the failure was because of a broken Jupyter installation, but the lack of logs is really annoying.

**Comment by choldgraf** [comment]
Usually something like this is actually an error under-the-hood on the binder servers or instability in google cloud. Once a Docker image is built, it *should* launch (AKA, it shouldn't be the user's fault if it doesn't, unless they're using a Dockerfile). There's been a bit of instability over the last few days so this could be what you ran into...

**Comment by jdemeyer** [comment]
> unless they're using a Dockerfile

That's actually the whole point of this issue. When something goes wrong with a customized image, it's not easy to find out why.

**Comment by choldgraf** [comment]
Yeah - the challenge there is that Dockerfiles present a big forking paths problem and we are a bit hesitant to design lots of process around them. (e.g., we'd need to run a check on each Dockerfile to find pre-defined errors and then give an error message for each)

We're treating Dockerfiles as "this is an advanced use-case, if you're doing it then you should expect a bumpier process in getting things set up just right". However we try to give as much helpful information as possible in constructing a Dockerfile for use with Binder/JupyterHub - have you found this page?

https://mybinder.readthedocs.io/en/latest/dockerfile.html

**Comment by jdemeyer** [comment]
To be entirely clear, I didn't use a `Dockerfile` but a `postBuild` script. Such a script is easier to use than a `DockerFile` but given that it can execute arbitrary code, it can also mess up things badly. 

Yes, I found https://mybinder.readthedocs.io/en/latest/dockerfile.html and I think that it's pretty clear actually.

**Comment by choldgraf** [comment]
Ah- could you share a link to your repo? Perhaps we can spot check the
problem even if the larger issue of unhelpful error messages is unresolved

**Comment by jdemeyer** [comment]
I already solved my problem, it works now. Anyway, the repo is https://github.com/jdemeyer/pep575binder

**Comment by choldgraf** [comment]
What solved your problem? The reason I ask is that I'm trying to tease apart errors due to configuration problems (which we probably could build error messaging around) and errors due to server problems (which will be hard to capture with an error message)

**Comment by jdemeyer** [comment]
> What solved your problem?

Installing Jupyter in the image.

**Comment by choldgraf** [comment]
I thought you said you were using a `postBuild` script and not a `Dockerfile`?

**Comment by choldgraf** [comment]
Hey - I'm going to close this since it sounds like your issue was resolved, but please do feel free to reopen in case you'd still like discussion on something!

**Comment by jdemeyer** [comment]
Has the issue in the title "No feedback why launch fails" been addressed? It's not because I managed to launch my Jupyter notebook anyway, that this underlying issue is solved.
