### ISSUE TITLE
Licensing requirements/notes

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#540]
Add some guidance to our documentationabout what you need to do to comply with the license of binderhub, repo2docker, jupyterhub, etc when deploying/distributing your own binderhub deployment.

Is there an example we can copy? Right now it isn't super clear to me what we would write beyond "please make sure you read LICENSE and then follow it."

cc @willingc

**Comment by jzf2101** [comment]
I can help with this @willingc

**Comment by willingc** [comment]
Thanks @jzf2101. I'll let you take the lead on this since I'm traveling for the next 3 weeks. Let me  know if you need anything.

**Comment by jzf2101** [comment]
I've assigned myself and will keep you posted

**Comment by choldgraf** [comment]
Thanks @jzf2101 !

**Comment by manics** [comment]
I'm closing this as this applies to all JupyterHub (and Jupyter?) projects. Please re-open if necessary.
