### ISSUE TITLE
Allow Kerberos Authentication

### ISSUE THREAD

**Issue by lukasheinrich** [jupyterhub/binderhub#548]
A lot of academic institutions rely on Kerberos to do authz/authn and this works by authenticating against a server via UDP packets, see:

https://web.mit.edu/kerberos/krb5-1.5/krb5-1.5.4/doc/krb5-admin/Configuring-Your-Firewall-to-Work-With-Kerberos-V5.html

It would be very useful, if those ports could be opened for the firewall. A major use-case is the ability to stream access-controlled data into the notebook.

Let me know if this should be moved to a more specific repo.

Thanks.

**Comment by lukasheinrich** [comment]
If this is not possible / deemd out-of-scope for the mybinder.org deployment, I think at least it should be possible to do this for on-prem deployments.

**Comment by betatim** [comment]
This is a question of how you configure your deployment and what level of trust users have in it. For example on mybinder.org users should never type in passwords or other sensitive information, but on a private binderhub deployment internal to a company that might be totally acceptable.

We should link to where in the helm chart the network policies are configured and consider making the docs better.

**Comment by lukasheinrich** [comment]
Thanks @betatim, I'll close this for now. Just for posterity, my understanding is now that the public mybinder.org deployment sees authentication support as out-of-scope, since clicking a binder link should "just work"?

**Comment by betatim** [comment]
Jupp
