### ISSUE TITLE
Feature request: install an utility and have it ready to use after building

### ISSUE THREAD

**Issue by aborruso** [jupyterhub/binderhub#557]
Hi,
I would like to use an utility like this one https://github.com/ericchiang/pup.

I install it without any problem using `go get github.com/ericchiang/pup` in `postBuild`.

But, it's not ready to use, I must open a notebook and run:

```
! chmod +x /home/jovyan/go/bin/pup
! export PATH="/home/jovyan/go/bin:$PATH"
```

Thank you

**Comment by choldgraf** [comment]
this relates to https://github.com/jupyter/repo2docker/issues/196 as well - I think once that issue is tackled, we could more easily support this as a hacky solution

**Comment by betatim** [comment]
Maybe we should simply add `/home/jovyan/{local}/bin` to the path. That would support the immediate need for having executables that users bring along at a later stage.

**Comment by choldgraf** [comment]
not a bad idea...

@minrk what do you think about @betatim 's suggestion as a stop-gap?

**Comment by aborruso** [comment]
@betatim good idea. But probably it's also necessary to give the user so set `chmod +` to installed utilities in `/home/jovyan/{local}/bin`, in postBuild file

**Comment by betatim** [comment]
`postBuild` runs as the user that owns `/home/jovyan` so you can change permissions on files there.

**Comment by aborruso** [comment]
Ok, great @betatim and sorry for my error.

Than your idea is fully a great idea, thank you. 
With `/home/jovyan/{local}/bin` the problem is solved. It would be a small great new feature

**Comment by choldgraf** [comment]
Is this just a matter of adding something like

```
# So users can move executables here with postBuild
ENV PATH {{ /home/jovyan/{local}/bin:${PATH}}}
```

to here: https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/base.py#L73

?

**Comment by betatim** [comment]
@aborruso you want to give this a go and create PR?

**Comment by aborruso** [comment]
@betatim wow, done https://github.com/jupyter/repo2docker/pull/311

And thank you @choldgraf

**Comment by aborruso** [comment]
@betatim @choldgraf another related question.

If I add in the postBuild something like

   npm install mapshaper --prefix ./home/jovyan/bin

the path of the installed utility wiI be `/home/jovyan/bin/node_modules/mapshaper`. 

If I install a go utility, in example using `go get github.com/ericchiang/pup`, the path of the utilty will be `/home/jovyan/go/bin/pup`.

A solution could be in example to add these rows in postBuild?

```
cd /home/jovyan/locale/bin
sudo ln -s  /home/jovyan/bin/node_modules/mapshaper mapshaper
sudo ln -s /home/jovyan/go/bin/pup pup
``` 

Thank you

**Comment by betatim** [comment]
Fixed in https://github.com/jupyter/repo2docker/pull/311

**Comment by aborruso** [comment]
@betatim than is it just enabled in mybinder?

Thank you for all

**Comment by betatim** [comment]
No, it hasn't been deployed yet. I will try and get to it today.
