### ISSUE TITLE
npm install not permitted

### ISSUE THREAD

**Issue by aborruso** [jupyterhub/binderhub#558]
Hi,
I have `npm install -g mapshaper` in postBuild, but I'm blocked because I'm not root.

Is there another way to install a nodejs package and have it ready to use after building?

Thank you

**Comment by betatim** [comment]
Currently there is no builtin support for npm packages so `postBuild` is the only game in town.

Does anyone (@yuvipanda @willingc @minrk) remember why we decided that `postBuild` should not run as root?

**Comment by betatim** [comment]
Let's move this issue to [repo2docker](https://github.com/jupyter/repo2docker).
