### ISSUE TITLE
Binder tries to process setup.py and fails - regression

### ISSUE THREAD

**Issue by mserranom** [jupyterhub/binderhub#559]
This used to work properly: https://mybinder.org/v2/gh/productml/blurr/master?filepath=docs%2Fexamples%2Fnyse.

Now it fails with a "Dependency not Found" error when processing `setup.py`. We don't use a `requirements.txt` but `pipenv` instead, so there's nothing to resolve (we also don't need to resolve anything for our notebooks in the repo, they're self-contained.) 

It used to be fine, can't tell exactly when it stopped working, perhaps ~ May 1st 2018.

**Comment by betatim** [comment]
The source of this behaviour is that we added support for automatically running `pip install .` when there is a `seutp.py`. This is the PR (and linked discussion): https://github.com/jupyter/repo2docker/pull/289

**Comment by mserranom** [comment]
Makes sense, but the problem I see is that `requirements.txt` is not the only way out there to do dependency management. Would be nice to have a way to opt-out `setup.py` processing, otherwise more people might continue running into issues.

**Comment by choldgraf** [comment]
@mserranom if you add a `binder/` folder and put requirements files in there, anything inside will supersede whatever is in the root of the repository. You can use that to avoid `setup.py` installs

**Comment by betatim** [comment]
Note that it is enough to simply create an empty `binder/` directory. That will stop repo2docker from using anything outside it.

How do we decide if we keep automatic `setup.py` processing or make it opt-in? This is the first time we received a -1 on it. Should we keep track of 👍s and 👎s for a while?

**Comment by choldgraf** [comment]
in this case, we would have been fine if `pipenv` was installed, right? I think it should be OK to tell people "if there's a setup.py file and no reqs.txt, Binder will try to install using this file, but note that you can't use non-standard installation steps in there as they won't be in the base Docker image"

Then again, pipenv is probably something we should support sooner than later too :-)

**Comment by betatim** [comment]
Yes it would have worked had `pipenv` been installed. Though it sounded like they wanted to disable `setup.py` processing completely/were surprised this was happening.

**Comment by jzf2101** [comment]
I think taking of pipfiles would be the wayu to solve this too.

**Comment by manics** [comment]
Give the ages of this issue I'm assuming we're not going to change the behaviour now.
