### ISSUE TITLE
Make this work with minikube

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#57]
We should possibly allow configuring this to not need an image registry, for the (common?) special case of just having one node (such as minikube). It'll just check local docker instead of registry.

This might eventually allow us to have a single node non-kubernetes setup if needed.

**Comment by yuvipanda** [comment]
Works now! Just need docs :D

**Comment by choldgraf** [comment]
the main things would be to not set up a google container registry, as well as point people to instructions on setting up minikube in the first place, yeah?

**Comment by minrk** [comment]
I think this is addressed by #93, which includes necessary config and setup doc for testing.
