### ISSUE TITLE
some problem with mybinder: it seems not work

### ISSUE THREAD

**Issue by aborruso** [jupyterhub/binderhub#582]
Hi,
in this moment it's impossible to build this https://mybinder.org/v2/gh/aborruso/bashnotebook/master

**Comment by choldgraf** [comment]
you can find a dashboard of the launch / failure statistics here: 

https://grafana.mybinder.org/d/3SpLQinmk/1-overview?refresh=1m&panelId=16&fullscreen&orgId=1&from=1528142156664&to=1528185356665

What kind of error messages are you getting?

**Comment by aborruso** [comment]
@choldgraf it is freezed in this way

![immagine](https://user-images.githubusercontent.com/30607/40963089-c613bac6-68a7-11e8-9054-a1c3a65da812.png)

**Comment by aborruso** [comment]
Now it works

**Comment by choldgraf** [comment]
good catch - it turns out this was a failing node in google cloud...launches were succeeding, but builds were failing which is why this didn't show up in the errors

**Comment by aborruso** [comment]
Now it's builded , but it's impossible to load ant it remains in this status

![immagine](https://user-images.githubusercontent.com/30607/40979731-e8390654-68d6-11e8-9cda-e9cb4c4d43bb.png)

**Comment by choldgraf** [comment]
can you double check that this doesn't work even if you wait a while? if the docker image is large it'll take a while

**Comment by aborruso** [comment]
Now it works thank you
