### ISSUE TITLE
Expose binder/notebook image name via environment variable to notebook container

### ISSUE THREAD

**Issue by jhamman** [jupyterhub/binderhub#586]
*First of all. You all rock. I recently deployed a binderhub on GCP following your docs and it basically worked on my first try.* 

I would like to find a way to expose the name (e.g. a GCR or dockerhub path) of the built docker image in the notebook environment. I want to do this because I'd like to give the name of this docker image to `dask-kubernetes` to support scaling computations done in a binder notebook across a larger kubernetes cluster.

I have looked at the current environment variables but it doesn't seem like this functionality is covered yet. 

(more discussion on the larger use case and progress related to this issue here: https://github.com/pangeo-data/pangeo/issues/283)

**Comment by betatim** [comment]
Off the top of my head I can't think of a reason why we couldn't do this. Will need to think a bit about _how_ to do it. Binderhub itself has nothing to do with how each pod is started, it makes an API request to JupyterHub. So it is probably something to configure in kubespawner.

---

As a temporary bandaid you can probably construct the name of the image from the information available inside the container + your admin knowledge. Checkout https://github.com/jupyterhub/binderhub/blob/59ace6dc8223a6f88e4eea29ecca0f1838e5a9c3/binderhub/builder.py#L243-L247 for how the name is computed.

**Comment by jhamman** [comment]
@betatim - thanks for your response. I'll look into the bandaid that you mention. Would it make sense to cross post this with kubespawner?

**Comment by choldgraf** [comment]
+1 to opening this up in kubespawner so we can figure out where is the right place for this fix to happen!
