### ISSUE TITLE
Feature: display repository status and history

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#589]
I recently created #588 that suggests we fetch information a repo right after it is entered in a initial step, before thinking about what branch and file to start.

If that is done, we can at an early stage figure out if the repo is already built and up to date, if previous versions of the repo is built, what previous launch parameters have been used with the repo, and perhaps more...

Displaying such information might be relevant to the user, the user might realize that it is the lecture/lecture01.ipynb of this repo that is the most common starting point for example.

**Comment by choldgraf** [comment]
Seems like an interesting idea - I believe that @betatim had a similar issue open somewhere but I can't figure out which repo it was in :-P

**Comment by willingc** [comment]
Related to https://github.com/jupyterhub/binderhub/issues/565

**Comment by manics** [comment]
See https://github.com/jupyterhub/binderhub/issues/565
