### ISSUE TITLE
Add support for RISE display

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#59]
It would be really cool if users could build repositories that were meant to be viewed with RISE. This way people would click a link and they'd be taken to an interactive RISE view automatically, which could be used to step people through material, tell stories in a linear fashion, etc.

This should be tagged as a future feature request but I think it'd be pretty cool if we could implement this such that we use RISE when giving talks about Binder in the future!

**Comment by choldgraf** [comment]
See: https://github.com/damianavila/RISE/issues/264 which is blocking on this issue getting merged

**Comment by damianavila** [comment]
I merged the PR @choldgraf... not sure when I going to release the new version but you have it on master by now.

**Comment by damianavila** [comment]
Release is out :wink: https://github.com/damianavila/RISE/issues/299#issuecomment-341903114

**Comment by choldgraf** [comment]
Woohoo! https://github.com/binder-examples/jupyter-rise
