### ISSUE TITLE
Update JLab on Binder To Improve URL handling 

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/binderhub#598]
Thanks to @afshin for all the hard work.

We have had issues with routing on JLab URLs @consideRatio https://github.com/jupyterlab/jupyterlab/issues/4502 .  This has been resolved with the latest release.  Do we update the version in the r2d buildpack or here?

**Comment by choldgraf** [comment]
@jzf2101 let us know when repo2docker is bumped and then we can start the process here! I'm +1 on updating JupyterLab, I think it's been a while since we've done so.

**Comment by jzf2101** [comment]
FWIW we need to wait until JLab is formally updated we're still in prerelease for the features we want.

**Comment by manics** [comment]
JupyterLab will have been updated several times since this issue was opened.
