### ISSUE TITLE
Dropdown menu selection causes a scroll jump

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#608]
When you select between "File" and "URL" (or in the GIF here repo providers) the page jumps back to the top if you had scrolled down a bit. Not quire sure which bit of JS is causing this but we should fix it.

To reproduce: visit mybinder.org, scroll down a bit, change between File and URL in the urlpath dropdown. This will reset the scroll to the top of the page causing a "jump"

![repo-providers](https://user-images.githubusercontent.com/1448859/42680648-e0071cce-8685-11e8-8446-f12085eadb02.gif)

**Comment by choldgraf** [comment]
think this is the bug in question: https://stackoverflow.com/questions/3252730/how-to-prevent-a-click-on-a-link-from-jumping-to-top-of-page ?
