### ISSUE TITLE
Outgoing TCP connections ?

### ISSUE THREAD

**Issue by imandr** [jupyterhub/binderhub#609]
Hello.

I am trying to use binder to publish a demo notebook for a distributed data analysis framework. The notebook is supposed to be the client and the workers are at FNAL. The notebook was never able to connect to the workers. The TCP connections timed out. Do I understand correctly that outgoing TCP connections from inside the binder container are blocked ?

Thanks !

**Comment by betatim** [comment]
BinderHub the software itself does not block network requests. The particular configuration used on mybinder.org (a piece of public infrastructure) does block outgoing network connections except for HTTP(s) and git.
