### ISSUE TITLE
No timezone configuration in running image

### ISSUE THREAD

**Issue by ElDeveloper** [jupyterhub/binderhub#610]
When I run a python command that needs timezone information I get an error pointing to a missing timezone configuration. For example if you install the tzinfo package and run the following block:

```python
from datetime import datetime
import tzlocal

datetime.fromtimestamp(datetime.now(), tzlocal.get_localzone())
```

You get this error:

```
---------------------------------------------------------------------------
UnknownTimeZoneError                      Traceback (most recent call last)
<ipython-input-1-a09b01ca19dc> in <module>()
      2 import tzlocal
      3 
----> 4 datetime.fromtimestamp(datetime.now(), tzlocal.get_localzone())

/srv/conda/lib/python3.5/site-packages/tzlocal-1.3-py3.5.egg/tzlocal/unix.py in get_localzone()
    121     global _cache_tz
    122     if _cache_tz is None:
--> 123         _cache_tz = _get_localzone()
    124     return _cache_tz
    125 

/srv/conda/lib/python3.5/site-packages/tzlocal-1.3-py3.5.egg/tzlocal/unix.py in _get_localzone(_root)
    115             return pytz.tzfile.build_tzinfo('local', tzfile)
    116 
--> 117     raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
    118 
    119 def get_localzone():

UnknownTimeZoneError: 'Can not find any timezone configuration'
```

From searching online, this seems to be fixable by installing the tzdata package (see for example [this thread](https://github.com/rembo10/headphones/issues/2465), and the [stack exchange post](https://unix.stackexchange.com/q/110522/102369) they refer to). That being said, I'm not exactly sure why that file would be missing or if this is within the scope of configuration for binder images.

**Comment by minrk** [comment]
Thanks. I think we can install the `tzdata` in the base image. If you need it right now, you can add it to your `apt.txt` file.

Perhaps more portable is to use code like:

```python
from datetime import datetime, timezone
datetime.now(tz=timezone.utc)
```

which doesn't require tzdata to be installed.

**Comment by ElDeveloper** [comment]
Thanks @minrk, this fixes the problem. I installed the package via `apt.txt`.

I'm all for more portable code, except this error came from a dependency :\

I believe this is not an issue then? So for now I'm closing this but feel free to reopen if you think this is within the scope of binder.
