### ISSUE TITLE
Going from z2jh to z2bh

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/binderhub#612]
Related to #611 and https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/643

@aculich and I discussed working through the tutorials in the following order:

1. littlest jupyterhub on GCP
2. zero to jupyterhub
3. zero to binderhub

@betatim and @matthew-brett @LotteWeerts started working through this yesterday and we have some ideas on how to document this.

It would be useful to document the best way to transition from each tutorial so you don't destroy your session each time.

**Comment by choldgraf** [comment]
I think one trick here is that z2jh has you set up `config.yml` in a particular way (with the secret inside it) whereas the binderhub install has you put the secrets in `secret.yml`.

That said, I agree we should more smoothly transition between the two!

**Comment by choldgraf** [comment]
also @jzf2101 is there a place where you guys were writing down notes / slides / etc from your run-through?

**Comment by matthew-brett** [comment]
No, sorry, I don't have notes.  I believe the instructions worked, once I had correctly followed them.  I don't have terminal logs, because I could not get helm etc to work from my laptop, so all my commands were in the Google Cloud terminal.  Unless y'all know how to get history from that?

**Comment by manics** [comment]
Is this something we still need/want to document? Or are the current docs good enough?

**Comment by choldgraf** [comment]
+1 on closing this for now and following up in subsequent issues if there are specific improvements we need to make
