### ISSUE TITLE
can docker registry be exposed to the public from mybinder.org?

### ISSUE THREAD

**Issue by ctb** [jupyterhub/binderhub#619]
it'd be nice to be able to grab the binder from mybinder.org for local use.

**Comment by betatim** [comment]
IIRC the original reasoning behind not exposing the registry was the cost of paying for network I/O.

Can I interest you in https://github.com/binder-examples/continuous-build - not only does it make sure your repo works with repo2docker it also contains the code to push the build image to dockerhub (or a registry of your choosing).

**Comment by ctb** [comment]
On Fri, Jul 20, 2018 at 09:49:59AM -0700, Tim Head wrote:
> IIRC the original reasoning behind not exposing the registry was the cost of paying for network I/O.

ahh, ok. is it that significant?

> Can I interest you in https://github.com/binder-examples/continuous-build - not only does it make sure your repo works with repo2docker it also contains the code to push the build image to dockerhub (or a registry of your choosing).

gotcha.

**Comment by jzf2101** [comment]
This is also discussed in https://github.com/jupyter/repo2docker/issues/339

**Comment by betatim** [comment]
Closing this as it is resolved.
