### ISSUE TITLE
Getting filepath right for notebook preview

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#622]
via #616 

Works:
https://mybinder.org/v2/gh/engineersCode/EngComp1_offtheground/master?filepath=notebooks_en%2F2_Jupyter_strings_and_lists.ipynb

Doesn't work:

https://mybinder.org/v2/gh/engineersCode/EngComp1_offtheground/master?filepath=%2Fnotebooks_en%2F2_Jupyter_strings_and_lists.ipynb 

This is quite hard to spot for users. Maybe we can add a tooltip/hint to the urlpath form field that asks users if they want to add a leading slash?

**Comment by choldgraf** [comment]
I made a very tiny rearranging edit to make it easier to parse :-)

also, is there *ever* a time that we want to have a leading slash there? If not, could we just sanitize it?

**Comment by betatim** [comment]
I don't *think* we need a leading slash ever. But I am not sure if it is true. I'd merge a PR that sanitises or warns.

**Comment by minrk** [comment]
clsoed by #660
