### ISSUE TITLE
Building pods that also have lots of traffic take up BinderHub CPU

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#624]
In a recent outage we discovered that a build pod that gets a lot of traffic will eat up all of the BinderHub pod CPU. This seems to be because each subsequent `/build` request reserves more CPU resources, and if the build doesn't finish fast enough, this saturates Binder pod.

We should find a way to avoid this CPU saturation error!

Alternatively, if this fix isn't possible, then we should figure out a way to spot and/or prevent build pods from taking extremely long amounts of time if they are also popular.

**Comment by betatim** [comment]
Related #625 and #626. Mitigate but don't completely solve the problem (I think).

**Comment by minrk** [comment]
We already have a pool that sets an upper limit for the number of concurrent builds to be watched (default: 32). It's possible that the mybinder.org resource limits are such that watching 32 builds is more than one cpu core worth of work. We can either turn this number down or turn the CPU allocation of binderhub up to handle it.

Fixes:

- #626 fixes an issue where a full build queue would prevent launches of built images from starting as well

Mitigations:

- #625 limits the cost of a new watcher connecting to an existing build that has a lot of logs to process
- #628 limits the cost of requests that start watching a build and then promptly disconnect, which I *think* consumes a build slot until the build finishes.

We should do some profiling to figure out precisely what is consuming the CPU

**Comment by manics** [comment]
Have we solved this problem?

**Comment by choldgraf** [comment]
I think since all of the PRs that @minrk mentions are merged, we could close this one and re-open something if the issue pops up again (I think we would have known if it hadn't been addressed)
