### ISSUE TITLE
Blocking stdout and stderr? 

### ISSUE THREAD

**Issue by jan-janssen** [jupyterhub/binderhub#630]
I really like the idea of https://mybinder.org to demonstrate new software. But I have issues working with C++ based Libraries https://github.com/jan-janssen/lammps-notebooks/issues/1 the same notebook works fine on my docker images but I am not able to get it working on mybinder.org . 

Best regards 

Jan

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).

**Comment by kysrpex** [comment]
I also experience this issue when running PyLammps on mybinder.org. It is indeed unrelated to BinderHub.

A solution is to disable Python's stdout buffering. For example, you may disable it using the [`PYTHONUNBUFFERED` environment variable](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED). If you are using your own Dockerfile, including the following line:

```dockerfile
ENV PYTHONUNBUFFERED=1
```

**Comment by minrk** [comment]
repo2docker, which powers mybinder.org [sets PYTHONUNBUFFERED=1](https://github.com/jupyterhub/repo2docker/blob/0345a86143681b86f68381d62786cd23f94b0e53/repo2docker/buildpacks/base.py#L180)
