### ISSUE TITLE
Preview not working for Jupyter Lab link

### ISSUE THREAD

**Issue by fangohr** [jupyterhub/binderhub#645]
Found the following yesterday:

Opening a repo in binder using the notebook using this link 
https://mybinder.org/v2/gh/fangohr/introduction-to-python-for-computational-science-and-engineering/master?filepath=index.ipynb 

works fine: a preview of the index.ipynb file is displayed, while the container is provisioned. See jupyter-notebook-file-preview-works.png (attached).

<img width="1089" alt="jupyter-notebook-file-preview-works" src="https://user-images.githubusercontent.com/4489119/44584290-74a8d000-a776-11e8-9c1c-4f9b648262a1.png">

Opening the same repo in binder using Jupyter Lab also works, but the preview that is displayed is for the table of contents, not the file specified: 
https://mybinder.org/v2/gh/fangohr/introduction-to-python-for-computational-science-and-engineering/master?urlpath=lab/tree/index.ipynb
See jupyterlab-file-preview-not-working.png (attached).

<img width="1122" alt="jupyterlab-file-preview-not-working" src="https://user-images.githubusercontent.com/4489119/44584300-7d010b00-a776-11e8-9b62-9dc0ff7d2e02.png">

If it helps: both links are available on [this page](https://github.com/fangohr/introduction-to-python-for-computational-science-and-engineering/blob/master/Readme.md) which tries to give users a choice to either use classic notebook or JupyterLab. 

There is another recent issue that may be related (https://github.com/jupyterhub/binderhub/issues/644) but I found the link not so clear, so link that I created a new one).

**Comment by choldgraf** [comment]
Ahh good catch - I believe that this is because we're not checking for `urlpath` here: https://github.com/jupyterhub/binderhub/blob/01d643d7ae98f560f08f4fb5e43bfbf34f159863/binderhub/templates/loading.html#L41 and so it is defaulting to showing the root of the repository.

I think a solution here could be to have a more fine-grained REST API (so instead of `urlpath=` we could have `app=lab&filepath=index.ipynb`. @yuvipanda don't we do something similar with nbgitpuller?

**Comment by betatim** [comment]
I am -0 on adding a new parameter to the URL. It makes it more complex. How stable is the lab support for opening a file directly? If it is allowed to go away/change again I think we should investigate if we can handle this via making our nbviewer URL generation smarter. Then circle back on this once there is some kind of stable API for lab to open links.

**Comment by jzf2101** [comment]
@fangohr:  @afshin can chime in, but I believe one would need to use [workspaces](https://jupyterlab.readthedocs.io/en/latest/user/urls.html) instead of `urlpath=lab/notebook.ipynb` to get the result you want.

**Comment by mpilosov** [comment]
any support on `app=lab`? I am trying to use gitpuller in binder and want it to auto-open jupyterlab and a file, and since both rely on `urlpath`, it seems like I cannot specify both. Or does one need to use workspaces as per @jzf2101 ?

**Comment by choldgraf** [comment]
I don't believe that this has been implemented currently, but I am happy to review a PR from somebody that tries implementing this!

**Comment by afshin** [comment]
@mpilosov @choldgraf You can link directly to a file with just a URL without having to use workspaces, *e.g.*, this link: https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/try.jupyter.org?urlpath=lab/tree/demo/big.csv

You just need to have `urlpath` equal `lab/tree/path/to/some/file`
