### ISSUE TITLE
BUILDER: Environment variables

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#65]
We should let users define environment variables w/ their repositories.

* Should this be its own file, or should we just ask people to use a `binder.yml` file in this case?

**Comment by yuvipanda** [comment]
This should be in repo2docker :)

Anything related to how repos are turned into images should be there...

**Comment by choldgraf** [comment]
yep I just realized I was in the wrong repo :-P already opened another one in repo2docker a second ago and will port these over there (except for the binderfile one, which is I think more appropriate here, yes?)

**Comment by yuvipanda** [comment]
Nope, they all belong in repo2docker :)

Thanks for moving them over!
