### ISSUE TITLE
Resolving branch names for repo providers that aren't github.com or gitlab.com

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#675]
For repoproviders that are not GitHub.com or Gitlab.com users have to specify the commit SHA by hand. Leaving the SHA field in the form empty (default) or writing `master` doesn't work.

This is because BinderHub talks to the GitHub API to resolve `master` or the branch name to a SHA. However we currently don't do this for repoproviders that aren't GitHub.com or GitLab.com.

Explaining to new comers why it works for one GitLab instance but not a different one is hard.

@minrk suggested we try and detect if a source is a gitlab instance and then talk to the API without authorisation token. This would get users the same behaviour as for an instance we "know" about. The downside is we might run into API rate limits.

So we need some good UI around this.

A stopgap might be to edit the form we show to make it more obvious which fields are required and which optional in the different cases.

**Comment by minrk** [comment]
Additionally, if there's a way to resolve refs with the *git* API without cloning, that would be great. I'm not aware of a way to do this, though.

**Comment by djhoese** [comment]
I'd like to +1 this feature request. I have a gitlab instance at my work where the repository is public and would like to point binder to the master branch. Having to point it to a commit hash causes a weird chicken/egg problem where I can't include the URL to binder in a README until I already have a working configuration commit. If I make a change I have to update the URL in the README every time *after* I commit.

**Comment by sauerburger** [comment]
I had the same chick-egg problem. I created a website with a quick workaround until this is supported natively: https://b4gl.sauerburger.io/

The site uses the gitlab api to resolve the ref and then redirects to mybinder.org using the resolved git commit. Feel free to use it.

**Comment by betatim** [comment]
Closed by #895
