### ISSUE TITLE
Add UI to generate badges

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#68]
Right now people don't know how to generate badges unless they've been on gitter! Make a fairly small UI for this.

**Comment by choldgraf** [comment]
One idea here would be to add a little dropdown arrow to the right of `launch`. If you clicked it, there would be another option for `copy binder link to clipboard` as well as `copy binder badge to clipboard` or something like this.

**Comment by minrk** [comment]
Dropdown arrow implemented in #122
