### ISSUE TITLE
Force re-creation of image when underlying library changes

### ISSUE THREAD

**Issue by pdehaye** [jupyterhub/binderhub#683]
Situation:  a binder relies on a library that has changed, and an image is already in memory of mybinder.org (for how long?). 

Wish 1: It would be nice to have a way to force recreation of an image by passing the right argument on top of the direct link to the binder. 

Wish 2: It would be nice to have a way to force recreation of an image when the underlying libraries have changed by passing the right argument on top of the direct link to the binder. 

It seems to me that wish 2 would be the most appropriate for a "launch binder" test me button on a github repo.

**Comment by betatim** [comment]
Hi @pdehaye! The image will be rebuilt automatically if you make a new commit in the repository. We recommend you specify the versions of the dependencies you care for and the bump those when a new one is released.

BinderHub assumes that you specified the versions of your dependencies such that building the same commit at multiple points in time will result in the same image.

**Comment by pdehaye** [comment]
Makes sense.
