### ISSUE TITLE
passing variables

### ISSUE THREAD

**Issue by pdehaye** [jupyterhub/binderhub#684]
It would be nice if one could add variable names and values in the hyperlink so that these would end up as additional environment variables in the launched binder. 

For instance `mybinder.org/{path}?DATA="hello"` would lead to the environment variable DATA populated.

**Comment by jmansour** [comment]
This would be very useful.

**Comment by manics** [comment]
See https://discourse.jupyter.org/t/pass-parameters-to-a-notebook-on-jupyterhub-binderhub/1973 for some discussion
