### ISSUE TITLE
REST API for requesting kernels doesn't seem to work anymore

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#689]
Recently @ines and I discovered that requests to BinderHub's kernel API wasn't working anymore (neither for Juniper, nor for thebelab). An attempt to request a kernel results in a version of this error:

```
Failed to load https://hub.mybinder.org/user/binder-examples-requirements-69hfkvk9/api/kernels?1539279191043: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://minrk.github.io' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by choldgraf** [comment]
(relevant issue https://github.com/explosion/spaCy/issues/2840)

**Comment by betatim** [comment]
https://github.com/jupyterhub/mybinder.org-deploy/pull/763 contains changes to the CORS setting. I am about to sign off for the night so won't revert it. If someone else wants to experiment please do and leave some notes so we can pick up tomorrow morning.

**Comment by Miniland1333** [comment]
The thing that sticks out to me is
`import z2jh`
Do you have an idea what this new line is referencing? I don't see a file matching this import statement

**Comment by choldgraf** [comment]
Here's the change @betatim is talking about:

https://github.com/jupyterhub/binderhub/compare/dd2de38...24ad99a

and here's the CORS config in binderhub:

https://github.com/jupyterhub/mybinder.org-deploy/blob/953802e6b284e9ef6578c3cd60ac497809050ddd/mybinder/values.yaml#L29

I agree the z2jh import is strange

**Comment by betatim** [comment]
Repaired in https://github.com/jupyterhub/mybinder.org-deploy/pull/764
