### ISSUE TITLE
Berkeley: Mechanical engineering workshop

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#69]
@aculich could you note a few thoughts / pros and cons about your use of Binder in the event we recently spoke about? Stuff like something that would have made the use of binder more simple,  something you expected it to do that it didn't do, that kind of thing. I'd like to keep track of the experience folks have!

**Comment by yuvipanda** [comment]
Not sure if this is actionable anymore, so going to close this :)
