### ISSUE TITLE
Create documentation for setting up authentication

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#691]
Recently @bitnik got the PR for authentication merged in #666 , we now need to document this so that others can replicate it!

@jhamman - think that you could give a PR for this a shot once you deploy for pangeo? :-)  OR, just write down the steps you followed and I can turn it into a PR

**Comment by bitnik** [comment]
Hi, has anybody started to work on this? If not, I want to do it this week.

**Comment by choldgraf** [comment]
I haven't seen any PRs! Please feel free to give it a shot if nobody chimes in, people who make documentation PRs are the best people :-)

**Comment by manics** [comment]
Done in https://github.com/jupyterhub/binderhub/pull/707
