### ISSUE TITLE
Sharing Images Built with Binder

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/binderhub#694]
On a few occasions, people have asked me about being able to take an image and run the code in the image using their own compute.  How would someone deploy a binder that could have this kind of system? 

Related: https://github.com/jupyter/repo2docker/issues/37

**Comment by betatim** [comment]
We don't have good instructions on how to get a host with a working dockerd setup. This might even be out of scope for Project Binder?

If you do have a machine up and running that has docker then you can use `repo2docker https://github.com/org/repo`. What would you add to that or why did that not work for the people who asked you? It could be that it isn't well enough known and we should add it as a FAQ for the BinderHub documentation.

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
