### ISSUE TITLE
Setup binderhub with minikube

### ISSUE THREAD

**Issue by andycamh** [jupyterhub/binderhub#695]
Hi ,
I want to test jupyterhub on minikubernet. I have come to setup binderhub.
after execute the command
helm install jupyterhub/binderhub --version=0.1.0-85ac189  --name=camhdockerhub --namespace=camhdockerhub -f secret.yaml -f config.yaml
the command kubectl --namespace=camhdockerhub get svc proxy-public always return the 
EXTERNAL-IP is under <pending> status. 
is anybody have the experience to setup binderhub under minikubernet environment.

**Comment by choldgraf** [comment]
Hey @andycamh , it's a bit hard to understand your problem...what guide were you following in order to do this? Zero to JupyterHub? BinderHub?

**Comment by choldgraf** [comment]
hey @sgibson91 actually for installing binderhub locally using minikube, could you try following these instructions?

https://github.com/jupyterhub/binderhub/blob/master/CONTRIBUTING.md#installation

Those are from the contributing guide...we hadn't assumed people would want to deploy binderhub locally for purposes other than development, but I'd be curious to hear what your use-case is! maybe should expose these instructions more?

**Comment by sgibson91** [comment]
Hi again,

I'm having time out issues following the contributing guidelines.

This line:
```
./testing/minikube/install-hub
```
causes this TimeoutError:
```
Traceback (most recent call last):
  File "./testing/minikube/install-hub", line 115, in <module>
    wait_for(hub_running, "Hub is up")
  File "./testing/minikube/install-hub", line 102, in wait_for
    raise TimeoutError(f"{msg} did not occur in {timeout} seconds")
TimeoutError: Hub is up did not occur in 300 seconds
```

**Comment by aliceminotto** [comment]
Hi, I'm also having the same issue deploying on opennebula and using the kubernetes app. Did someone find a workaround for this?

**Comment by betatim** [comment]
This is a fairly old issue so it might make sense to start a new thread on https://discourse.jupyter.org/ to discuss your specific problem. Opennebula and minikube are probably different enough that the debugging steps are different.

In the forum post I'd start with explaining which instructions you are following and some information about opennebula (I don't think a lot of people here have experience with it).

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
