### ISSUE TITLE
Document and improve how to cut a new release

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#718]
In https://github.com/jupyterhub/binderhub/pull/717 we're adding a small amount of text on how to cut a new release, however it could be much-improved. This issue is to keep track of this item!

**Comment by betatim** [comment]
Maybe instead of adding a lot of documentation we can work towards having it automated so that the instructions can be:
* update change log via a PR
* tag a release on GitHub
* open new section in the change log via a PR

Which is roughly what we have on repo2docker.

**Comment by choldgraf** [comment]
good call, updated the title to reflect taht

**Comment by minrk** [comment]
The chart itself also has a version in helm-chart/binderhub/Chart.yaml. If the two are to have the same version (they do for now, but this is not the case for jupyterhub, and probably will stop being the case with binderhub as it matures), then we need to make sure to update them together.

**Comment by consideRatio** [comment]
- Closed in favor of #1666 with concrete details to complement with
