### ISSUE TITLE
Update the docs build which is missing traitlets

### ISSUE THREAD

**Issue by willingc** [jupyterhub/binderhub#728]
The docs builds are failing for the past 5 days due to missing traitlets. Likely due to refactoring of docs build in #711.

I don't know why the badge is not updating on the README here, but the [builds are failing on RTD](https://readthedocs.org/projects/binderhub/builds/).

**Comment by willingc** [comment]
Reopening as docs build is still failing. Though the traitlets error is solved.

**Comment by choldgraf** [comment]
hmm, the error message in RTD is that "npm" is not installed...but do we need npm for anything in the sphinx build? I didn't realize that was a dependency

**Comment by betatim** [comment]
We need npm when we install BinderHub which we install because we use autodoc. At least it seemed like that was what pulled in the traitlets dependency.

Should we get npm installed on RTD or investigate what our docs build actually does and if we want to change it?

**Comment by willingc** [comment]
Refresh my memory please. Why are we using Circle CI for docs? Seems as though it doesn't build in the same way that RTD does.

**Comment by choldgraf** [comment]
@willingc we're mostly using it to have an easy way to quickly look at the doc build in a PR...I find it quite useful to go into the circle artifacts and paste a link to the updated documentation.

That said, I agree it's problematic that the environments would be different :-/

**Comment by willingc** [comment]
I think we have two separate problems: a) render a preview for review (which CircleCI does well) and b) ensure the production docs are building on RTD and up to date.

Let me give some thought to this re: RTD and hooks to report build status to us.

**Comment by choldgraf** [comment]
yay! I think #755 solved the problem (which updated to the latest readthedocs build image). @willingc do things look good to you?

**Comment by choldgraf** [comment]
sigh, not travis is broken on master - I really doubt that was a result of #755 though, since it was only changing the readthedocs.yml file...I'll restart and see if that fixes it

**Comment by manics** [comment]
docs build is currently working
