### ISSUE TITLE
BinderHub CI timeouts

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#740]
Over the last few weeks BinderHub travis runs have been error'ing because of timeouts more often than not. This means they are essentially useless because we get in the habit of hitting restart all the time or merging despite travis being red.

From my observation it has been mostly in the part where we ask to build one of the CI repos. The error message doesn't say much so I wonder if this is because building that repo now takes a long time or because the test command that triggers the build can't reach binderhub and then times out?

Does anyone have an idea where to start digging or what changed?

**Comment by betatim** [comment]
One idea: should we explicitly fetch the ubuntu bionic base image before launching the tests? repo2docker will fetch it later but maybe that is super slow or otherwise leads to timeouts?

**Comment by choldgraf** [comment]
totally agree with this - I get really nervous when we start "assuming failure" in the tests :-/

**Comment by manics** [comment]
We're no longer on Travis!
