### ISSUE TITLE
JUPYTERHUB_API_URL vs HUB_SERVICE_HOST vs just `hub`?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#742]
I'm setting up a binderhub for neurips. I did it using cert-manager so i configured my binder and hub k8s service to be a ClusterIP instead of a LoadBalancer.

I find that the binder pod is unable to connect to the hub. I wonder why that is, debugged and found:

```
# from launcher.py
        hub_api_url = os.getenv('JUPYTERHUB_API_URL', '') or self.hub_url + 'hub/api/'
```

After inspecting the binder pod, I did not find the `JUPYTERHUB_API_URL` env var, but I found:
```
'HUB_SERVICE_HOST': '10.0.2.45'
'HUB_SERVICE_PORT': '8081'
```

I realize I could configure `hub_url` though through `c.BinderHub.hub_url` or through provided helm chart values in `binderhub.config.BinderHub.hub_url: http://hub:8081`

(or  `hub.neurips:8081` / `hub.neurips.svc:8081` / `hub.neurips.svc.cluster.local:8081`)

---

Something should perhaps be changed? I'm not sure what should be done, but it would be nice to not need to configure this at all as we know the hub's service name. But, I don't know how things work if I go back to a LoadBalancer for sure though...

---

Eh updated that to be the following, as if not the redirection to the user pod at a later stage got messed up.

```
binderhub:
  config:
    BinderHub:
      hub_url: https://hub.neurips.mybinder.org`
```

**Comment by minrk** [comment]
Yup, I think you've got it: hub_url should be set to the public URL of the hub. Is there anything to change here? I'd hesitate to use service connections, since what I really want in the long term is to take the Hub *out* of the binderhub chart and instead use them as siblings. Then, the communication between the two would have to be more explicit.

**Comment by consideRatio** [comment]
Yepp there is no issue except potentially an documentation update, I don't recall reading info about setting hub_url in between the initial docs until arriving at the "tear down" instructions. But perhaps it would had worked if I did not messed with the service to become a ClusterIP?

**Comment by consideRatio** [comment]
This is because I was blind. :)

```yaml
config:
  BinderHub:
    hub_url: http://<IP in EXTERNAL-IP>
```

**Comment by minrk** [comment]
I think it needs to be set in general. Making sure that's covered in the docs is something we should definitely do.
