### ISSUE TITLE
Vivaldi browser crashes when opening notebooks

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#754]
In #753 @januz reports that their browser (Vivaldi) crashes when starting a notebook with an R kernel.

Do you @januz have a minimal example that reproduces this behaviour so we can investigate why this happens?

**Comment by januz** [comment]
@betatim While trying to open an R notebook crashes my Vivaldi reliably, this seems to be related to my personal setup. I tried it out in an additional user account on my machine, and opening a notebook with an R kernel works there. So, I don't think that you can do anything on your end, but I should try to find out what causes this behavior (plugins, etc.)... Thanks!

**Comment by betatim** [comment]
Ok, I'll close this issue for the moment then. Feel free to reopen.
