### ISSUE TITLE
build docker image failed.

### ISSUE THREAD

**Issue by chenyg0911** [jupyterhub/binderhub#761]
binderhub with helm chart。
name: binderhub
version: 0.2.0-f80738c
registry: docker hub.
Try to deploy binderhub with sample: https://github.com/binder-examples/requirements.git
![default](https://user-images.githubusercontent.com/16010372/50816996-57f3ea00-135d-11e9-9fb9-88b7f334b166.png)

```
kubectl exec -it binder-fd9cddb54-njxnk -n binder -- bash
root@binder-fd9cddb54-njxnk:/# ping archive.ubuntu.com
PING archive.ubuntu.com (91.189.88.161) 56(84) bytes of data.
64 bytes from keeton.canonical.com (91.189.88.161): icmp_seq=1 ttl=61 time=378 ms
64 bytes from keeton.canonical.com (91.189.88.161): icmp_seq=2 ttl=61 time=298 ms
^C
--- archive.ubuntu.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 298.127/338.110/378.094/39.987 ms

```
What's the problem?Does repo2docker need setup extra env?

**Comment by minrk** [comment]
This is likely a DNS configuration problem, but it's a little confusing to figure out exactly where that would be. The build doesn't run in the binder pod, it's a separate `build-...` pod. Still, the DNS resolution here is happening in docker build, which is where docker itself runs. Are you using docker-in-docker or the host docker? If dind, can you check network accessibility in the dind container? If host, can you run a basic docker build that does some apt-getting?

**Comment by chenyg0911** [comment]
Thank you for your response. Yes, the binder will start a pod like build-binder-2dexamples-2drequirements-55ab5c-c68f25. And when it start, I attch to the pod to check the dns. The DNS seems OK.

```
root@build-binder-2dexamples-2drequirements-55ab5c-c68f25:/# ping security.ubuntu.com
PING security.ubuntu.com (91.189.88.152): 56 data bytes
64 bytes from 91.189.88.152: icmp_seq=0 ttl=61 time=296.327 ms
64 bytes from 91.189.88.152: icmp_seq=1 ttl=61 time=351.423 ms
64 bytes from 91.189.88.152: icmp_seq=2 ttl=61 time=404.431 ms
64 bytes from 91.189.88.152: icmp_seq=3 ttl=61 time=1668.565 ms
64 bytes from 91.189.88.152: icmp_seq=4 ttl=61 time=665.534 ms
64 bytes from 91.189.88.152: icmp_seq=5 ttl=61 time=643.070 ms

```

**Comment by chenyg0911** [comment]
Change to dind, build success.
