### ISSUE TITLE
build-in jupterhub can't terminate pod.

### ISSUE THREAD

**Issue by chenyg0911** [jupyterhub/binderhub#762]
Test binderhub on k8s, whitch deployed with helm chart binderhub-0.2.0-f80738c.
After binder launch a pod in jupyterhub. When quit button clicked.  Hub terminate the pod, but restart it immediately. Can't really terminate the pod. 
kubectl get pod -n binder -w: 
```
jupyter-binder-2dexamples-2drequirements-2dvjhtyiao   1/1   Running   0     2s
jupyter-binder-2dexamples-2drequirements-2dvjhtyiao   0/1   Completed   0     77s
jupyter-binder-2dexamples-2drequirements-2dvjhtyiao   1/1   Running   1     78s
```

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
