### ISSUE TITLE
Specify jupyterlab home before lauch

### ISSUE THREAD

**Issue by fmaussion** [jupyterhub/binderhub#764]
Hi all, apologies if this is a trivial question.

I'd like jupyterlab to have its "home" in a folder within the repository, not at the repository root. It will make a nicer user experience if all the repository config files aren't available in the jupterlab directory tree.

Note that starting from a specific notebook within the repository already makes it much nicer by starting at the right place in the tree, but I'd like users not to even be able to see or access the repository root folder.

Is there a way to do that? Thanks a lot!

**Comment by gnestor** [comment]
@jhamman In a similar vein, if I wanted to start jupyterlab in dev-mode on binder (usually `jupyter lab --dev-mode`), would my start script presumably look like:

```bash
#!/bin/bash

alias jupyter="jupyter lab --dev-mode"

exec "$@"
```

I tried that it doesn't seem to be working...

**Comment by fmaussion** [comment]
Thanks @jhamman ! I moved the issue to https://github.com/jupyter/repo2docker/issues/561
