### ISSUE TITLE
Create example binder repos

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#78]
We need to do at least two things:

1. Make sure all the old binder examples point to our new examples that cover the same kinds of material
2. Cover some use-cases many people will have, using each of the languages / build workflows that we support.

Here's where new examples will be located:

https://github.com/binder-examples

# Old repos
- [x] requirements
- [x] conda_environment
- [ ] remote_storage
- [ ] dockerfile
- [ ] dockerfile_two

# New repos
- [ ] legacy dockerfile (using the andrewosh image)
- [ ] from jupyter stacks dockerfile
- [ ] from your own dockerfile

# Use cases
- [ ] Installing latex

# New usecases for which we should have repos:
![image](https://user-images.githubusercontent.com/1839645/28738528-e58fc6d2-73a8-11e7-8e2a-851ed85be1df.png)

**Comment by yuvipanda** [comment]
ty. I'd add:

1. legacy dockerfile (using the andrewosh image)
2. from jupyter stacks dockerfile
3. from your own dockerfile

**Comment by m-weigand** [comment]
Not sure if this is the right place, but after I had some problems installing latex requirements for matplotllib, and not using Dockerfiles. So, in case you want to include this as an example, here is a working binder repo for using matplotlib with latex support:
[https://github.com/m-weigand/binder-example-latex-mpl](https://github.com/m-weigand/binder-example-latex-mpl)

**Comment by choldgraf** [comment]
Ack just saw this - thanks @m-weigand! I think it'd be helpful to show people how to build w/ latex.

**Comment by choldgraf** [comment]
we've added nearly all of these and I think we can consider the issue completed

**Comment by willingc** [comment]
@choldgraf :tada: :cake: Love the binder-examples org.
