### ISSUE TITLE
Updating xterm to 3.11.0

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#786]
Does anyone know if we can't update directly to https://github.com/xtermjs/xterm.js/releases/tag/3.11.0 ?

There are a few things like copy&pasting from the logs that is hard and drives me mad. We are at 2.9 or something like that so potentially a long way away from 3.11.0. I might give it a shot unless someone knows more about xterm.js and upgrading it.

**Comment by yuvipanda** [comment]
dooo itttt

**Comment by captainsafia** [comment]
I think this would be a good idea. There's also been a [security alert](https://github.com/jupyterhub/binderhub/network/alerts) out on the version on xterm that we are currently at.

**Comment by manics** [comment]
https://github.com/jupyterhub/binderhub/pull/1365
