### ISSUE TITLE
font files are not served under base url

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/binderhub#793]
In index.css there are 3 font files loaded with relative path:
https://github.com/jupyterhub/binderhub/blob/74b3d69c1c37a2ca05cff816b81b68ba515ac0ae/binderhub/static/index.css#L3-L16
But for both mybinder (base url is '/') and GESIS binder (base url is '/binder/') they are loaded from `/static/dist/...` in styles.css:
- https://mybinder.org/static/dist/styles.css
- https://notebooks.gesis.org/binder/static/dist/styles.css

I don't know if this is because how they are loaded in index.css or because of [webpack config](https://github.com/jupyterhub/binderhub/blob/master/webpack.config.js).

Actually this is not a problem for GESIS binder. I just wanted to report the issue.

**Comment by betatim** [comment]
I think webpack rewrites the URLs when it creates `styles.css` from the input CSS files.

I am not sure if there is a problem with how things currently work or if this issue is about improving the documentation (I'd welcome that :) ) or something else?

**Comment by bitnik** [comment]
But isn't it a problem that they are always served under `/static/dist/...` without considering the base url of the application? If base url is different than '/', those file won't be found. Maybe I am totally wrong :) I really don't know much about css files and webpack.

**Comment by betatim** [comment]
Ah! I think I agree with you that who ever re-writes that path to be `/static/dist/...` needs to take care to also include the base URL. I read your comment about `notebooks.gesis.org/binder/static/dist/styles.css` as "the files are being loaded from that URL, the fonts are somehow included in the CSS (by magic of webpack) and it includes the base URL and for mybinder.org it doesn't so all is as expected".

Now that I actually looked at the two CSS files you linked I see the problem. (Maybe I should have had a second coffee for breakfast.) -> We need to communicate the base URL to webpack. Maybe @captainsafia or @yuvipanda can help out with advice on how to do that best.
