### ISSUE TITLE
Image detection has hard dependency on gcr.io structure

### ISSUE THREAD

**Issue by shibbas** [jupyterhub/binderhub#800]
Hi, 

It looks like the registry has a hard dependency on image name to be like gcr.io with a project id (i.e. 2 levels). `image_name = "gcr.io/<google-project-id>/<prefix>-name:<tag>"`

https://github.com/jupyterhub/binderhub/blob/64bb3c7fb2a501ff31e1f29e572758f2589b5d97/binderhub/builder.py#L273

However, the documentation mentions to set up custom registry without the project ID, which causes the image to be rebuilt all the time. `image_name = "your-registry.io/<prefix>-name:<tag>"`

I've worked around it by just adding a projectID to my image prefix for ACR but was wondering if the correct fix for supporting all custom registries as well as gcr registry is what I'm proposing here: https://github.com/shibbas/binderhub/commit/c4a31cd893cd527c9f0479c6afacca24dca7961e

If not, perhaps an update to the documentation for custom registries?

**Comment by betatim** [comment]
I think even better than updating the docs would be to fix the code so it works with custom registries a la `gcr.io/project-id` and `project-id.azure.io/`. Do you want to create a PR for that?

**Comment by shibbas** [comment]
Yup, i can do that. Thanks for the feedback!

**Comment by sgibson91** [comment]
Hey @shibbas I'm really struggling to connect an ACR to my BinderHub, would you mind glancing over the following issue? https://github.com/alan-turing-institute/the-turing-way/issues/317

Thanks in advance!

**Comment by shibbas** [comment]
I think you might be using the wrong token_url in your config yaml. ACR token url is something like below: https://<ACR_NAME>.azurecr.io/oauth2/token?service=<ACR_NAME>.azurecr.io.

**Comment by sgibson91** [comment]
Thank you, I wasn't sure what the token would be so this definitely helps. It's still not working for me, but I'm beginning to suspect it's something to do with the Service Principal my IT services set up for me rather than the code.

**Comment by sgibson91** [comment]
Hey again @shibbas :wave: Have you experienced a BinderHub not pulling from an ACR and just continuously rebuilding the image?

**Comment by shibbas** [comment]
This thread actually was started because of that issue :) If you read the first comment from March, Binderhub has a hard dependency on the gcr.io structure. To work around it, you can add another level to your image prefix. `image_name = "your-registry.io/<some-project-id>/<prefix>-name:<tag>"`. That should pull the image down.

**Comment by sgibson91** [comment]
That's amazing, thank you!

**Comment by betatim** [comment]
As a none AZR user: is there something we can add to the docs or the code so that people don't have to re-discover this?

**Comment by sgibson91** [comment]
I was going to write up some docs about connecting an Azure Container Registry, as per issue #869, today and include this 🙂
