### ISSUE TITLE
Pipe symbol in connecting DockerHub registry docs can be confusing

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/binderhub#811]
[Link to Discourse topic](https://discourse.jupyter.org/t/debugging-binderhub-immediately-fails-to-build-a-binder/525)

I've just built a BinderHub that pushes images to a DockerHub organization and became slightly confused by the pipe (|) symbol in [the documentation](https://binderhub.readthedocs.io/en/latest/setup-binderhub.html#id2): `<docker-id|organization-name>/<prefix>-`.

I read this as literal and put both my ID and my organization into the config file which caused my BinderHub to fail to build as repo2docker was throwing an "invalid image name" error. After reading the note box more thoroughly, I realised my mistake and everything now works but perhaps we can make this more transparent in the documentation for skim-readers?

E.g. maybe explicitly saying "or": `<docker-id OR organization-name>/<prefix>-`?

Happy to open a PR when we've decided on a suitable phrasing. Thank you! ✨

**Comment by betatim** [comment]
Using an English word instead of `|` sounds like a good solution to me.
