### ISSUE TITLE
adding commit hash into launch event logs

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/binderhub#814]
I just found out a note of mine about adding commit hash into launch event logs (https://github.com/jupyterhub/binderhub/blob/master/binderhub/event-schemas/launch.json). Probably I was thinking it would be useful to have it for analysis but right now I cannot come up with an example. That's why I wanted to ask your opinion.

**Comment by betatim** [comment]
We have the "tag/branch name" that people enter on the website already. We could store the resolved reference as well. It would be interesting but I hardly ever look at the tag/branch name so .. maybe we already log "enough"?

**Comment by bitnik** [comment]
yes, I agree that we log enough (for now).
