### ISSUE TITLE
Add specific contribution guidelines for documentation

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/binderhub#817]
This was an idea that came out of a documentation workshop at the Collaborations Workshop run by the Software Sustainability Institute.

For new users coming to contribute to a project, they are the mostly likely candidates to find gaps in your documentation and potentially come up with solutions to these gaps. Therefore, I'm proposing a section in `CONTRIBUTING.md` that outlines the process by which to update the docs, including:

* opening an issue to discuss the change **or** document the knowledge gap if they themselves can't fill it
* where do the sources files for the docs live
  * this may include an "improve this page" style link on the host website which links to the repo, distinct from the "Page source" link currently implemented
* how to locally compile the docs to preview your changes before making a pull request

I hope you think this is a good idea, I think it will encourage even more people to get involved! :)

**Comment by sgibson91** [comment]
This could probably just be a summary of the [Jupyter contribution guidelines for documentation](https://jupyter.readthedocs.io/en/latest/contrib_docs/index.html) with the specific `make` command to locally compile 😄

**Comment by betatim** [comment]
I think this is a great idea! I think we should have a short version of this guide in https://github.com/jupyterhub/binderhub/blob/master/CONTRIBUTING.md which describes the steps you mentioned with the commands you can copy&paste. And then a link to the longer version at https://jupyter.readthedocs.io/en/latest/contrib_docs/index.html.

Even as an experienced contributor I find the full version quite overwhelming and "oh my god where do i even start?" where as if you give me a bullet point list with ten steps that fits on one screen I am "ok, easy peasy, this will take 5minutes" (even though it usually takes longer, but at least I get started).

**Comment by sgibson91** [comment]
@betatim I think you addressed this in #824 and can be closed
