### ISSUE TITLE
Binder beta isn't finding base Docker images

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#82]
Just replicated a user's error message building both with reqs.txt and environment.yml

![image](https://user-images.githubusercontent.com/1839645/29194337-ec566b94-7ddd-11e7-90ce-2b8e7ae1a21e.png)

Maybe a link with the Docker image registry got broken with the DNS move?

@yuvipanda ?

**Comment by choldgraf** [comment]
@willingc @minrk any thoughts on why this might be? this is currently causing all binder builds (w/o pre-existing images) to fail...

**Comment by yuvipanda** [comment]
This was all on me. Fixed by deploying new version of repo2docker to beta
too!

**Comment by choldgraf** [comment]
Fixed by @yuvipanda magic
