### ISSUE TITLE
Making the awesome bar happen

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#842]
What do people think for us making a call to redesign the landing page/create-your-binder-badge form?

Via [some tweets](https://twitter.com/psychemedia/status/1125499017482461185) I realised I don't actually use it all that much myself because I have the [magic binder button](https://addons.mozilla.org/en-US/firefox/addon/open-with-binder/) ([source](https://github.com/Carreau/open-with-binder)) in my browser. We have talked a lot about making a "awesome bar".

In reality we aren't the best when it comes to knowing our way around webpack, JS, react, vue, etc and for sure not the most talented when it comes to making things look good.

We have made good experiences with making a call to get a repo2docker logo.

So, should we just tweet, discourse and generally publicise an issue that asks for help to design the awesome bar? I'd say in the issue what we are looking for "awesome bar" == "paste the URL to a notebook and get a binder link and badge that will "just work" or say that it doesn't know what to do. This is basically what open-with-binder does. Maybe we can even do something clever with detecting that the user wanted RStudio or some such. Colour scheme should fit with what we have now. Tech stack: "modern JS, react based, opinionated, simple to maintain and deploy as part of a tornado app".

ref: #351

**Comment by choldgraf** [comment]
I'm all for it - "make the landing page a more top-notch javascript app" has been on the list for a while now, and I agree that there's a lot of community expertise out there that we could use if folks are willing to help!

Given that we don't (I think) have a roadmap for binderhub, I'm +1 on an issue scoping out the problem and kind of solution that we'd like, similar to the end of your last paragraph, and linking to it from the Discourse

**Comment by consideRatio** [comment]
@betatim for such a design request I'd ask what the paste action could potentially trigger. Is it only allowed to trigger JS logic in the browser, or can it also trigger some backend logic that could conclude if the file exist etc?

**Comment by betatim** [comment]
Closed in preference for #844.

I'd start with JS things only and the assumption that the person is copy&pasting a link from somewhere. So the target is likely to exist but maybe not publicly accessible.
