### ISSUE TITLE
Deprecating old Binder repos

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#85]
We should start deprecating the repos inside of `binder-project` so that people don't get confused when we announce the reboot. I've made a sample commit to the readme of `example-requirements`. What do you think about this?

https://github.com/binder-project/example-requirements

@willingc @yuvipanda @freeman-lab

**Comment by yuvipanda** [comment]
Do it

On Aug 15, 2017 11:22 AM, "Chris Holdgraf" <notifications@github.com> wrote:

We should start deprecating the repos inside of binder-project so that
people don't get confused when we announce the reboot. I've made a sample
PR to the readme of example-requirements. What do you think about this?

https://github.com/binder-project/example-requirements

@willingc <https://github.com/willingc> @yuvipanda
<https://github.com/yuvipanda> @freeman-lab <https://github.com/freeman-lab>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jupyterhub/binderhub/issues/85>, or mute the thread

**Comment by choldgraf** [comment]
(I'm gonna wait to get one more "OK" from either @willingc or @freeman-lab, since it'll touch a lot of the public-facing components of the binder ecosystem)

**Comment by willingc** [comment]
Hi all. I agree that adding a deprecation/moving message to the older repos makes sense. When something changes (even though we are excited for the progress), users often need a bit of reassurance that the changes make their life better not more stressful :-) A bit more context on the move would be helpful. See example README text here: https://github.com/willingc/example-requirements/blob/master/README.md

**Comment by choldgraf** [comment]
sounds good - I'll add @willingc 's messages today unless somebody has other thoughts!

**Comment by willingc** [comment]
You might add a link to the gitter channel for binder/mybinder.

**Comment by choldgraf** [comment]
@willingc can you create a gitter channel for the `binder` repo I created? For some reason I can't find it in my own gitter. That's a good idea tho, I'll add a link. here will be the final text I use. Speak now or FHYP :-)

## :dash: :dash: **The Binder Project is moving to a [new repo](https://github.com/jupyterhub/binderhub).** :dash: :dash:

:books: Same functionality. Better performance for you. :books:

Over the past few months, we've been improving Binder's architecture and infrastructure. We're retiring this repo as it will no longer be actively developed. Future development will occur under the [JupyterHub](https://github.com/jupyterhub/) organization.

* All development of the Binder technology will occur in the [binderhub repo](https://github.com/jupyterhub/binderhub) (https://github.com/jupyterhub/binderhub)
* Documentation for *users* will occur in the [jupyter binder repo](https://github.com/jupyterhub/binder) (https://github.com/jupyterhub/binder)
* All conversations and chat for users will occur in the [jupyterhub binder gitter channel](https://gitter.im/jupyterhub/binder) (https://gitter.im/jupyterhub/binder)

Thanks for updating your bookmarked links.

## :dash: :dash: **The Binder Project is moving to a [new repo](https://github.com/jupyterhub/binderhub).** :dash: :dash:

---

**Comment by willingc** [comment]
@choldgraf I set up the channel and added you. Here's the link: https://gitter.im/jupyterhub/binder 

Gitter also added link to the README.

As for the above text:

- second bullet jupyter->jupyterhub
- I think it's fine to remove the URLs and just have the actual link.

**Comment by choldgraf** [comment]
woot! thanks Carol! I just confirmed that the new binder chatroom works!

sounds good re: edits, I'll make those and will make the PRs later today!

**Comment by choldgraf** [comment]
this is done!
