### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#86]
- [ ] the [DNS page](https://binderhub.readthedocs.io/en/latest/setup-dns.html) could be removed and instructions placed in [setup binderhub](https://binderhub.readthedocs.io/en/latest/setup-binderhub.html)
- [x] the page on [tearing down a binder deployment](https://binderhub.readthedocs.io/en/latest/turn-off.html) should be filled out.
- [x] the [contributor guide](https://binderhub.readthedocs.io/en/latest/contributor-guide.html#binderhub) isn't really a contributor guide...it's just the readme. We should either flesh this out, or remove the content and link to the appropriate section in the readme IMO
- [x] the [API page](https://binderhub.readthedocs.io/en/latest/api/api-index.html) doesn't seem to be rendering properly.

**Comment by choldgraf** [comment]
a few to-do items @yuvipanda @willingc ... any thoughts / new items welcome!

**Comment by willingc** [comment]
Resolved API page build. One setting in RTD config for setup.py install wasn't checked.

**Comment by choldgraf** [comment]
@yuvipanda on this page: https://binderhub.readthedocs.io/en/latest/setup-binderhub.html

we have the wording

"Now find the IP of the nginx-ingress-controller:

`kubectl --namespace=support get svc support-nginx-ingress-controller`

And make DNS records for both binder and jupyterhub that point to that IP."

What do we mean by "make DNS records for both Binder and JupyterHub point to that IP"?
