### ISSUE TITLE
Add a repository quota white list

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#882]
It would be helpful if we had the ability to give some repositories special status relative to others. It seems that a good start (and one that would be immediately useful) would be to set up a **white list** configuration for repositories.

I looked into a little bit and don't have time to work on it more today, but putting my thoughts here in case it helps point someone in the right direction (maybe @sgibson91 can also riff off of this for creating a "whitelist" of non-banned repositories too?)

## Potential implementation

My guess is that this would follow a similar pattern as the **banned_specs** configuration. E.g. here's how it looks in the configuration for mybinder.org

https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/values.yaml#L46

It seems like this should be done at the RepoProvider level, although one question is where the quote whitelist would actually be checked. The banning check is done at the `get` event here: https://github.com/jupyterhub/binderhub/blob/908c4439f63b08744e2074e76dabb9883b1632e9/binderhub/builder.py#L233

While the quota checking is done under the `launch` event here: https://github.com/jupyterhub/binderhub/blob/908c4439f63b08744e2074e76dabb9883b1632e9/binderhub/builder.py#L462

The trick is that the `get` event has access to the repoprovider instance, while launch does not...so that's the main question I've got for implementing this.

## Other questions

* How would we test something like this? I maybe in the test infrastructure we can set the per_repo_quota to be really small (like, 1) and then try to launch a second test pod and make sure it works?
* More generally, is there a way to create async launch requests with python?

**Comment by betatim** [comment]
In my imagination we'd copy the repo banning setup but instead of providing just a regex to match as yes/no we also provide a limit for that regex in the config.

You could work out what the quota is for the matching regex in `get` (via asking the repo provider like we do for `is_banned()`). Then pass that limit into `launch` as an additional argument [here](https://github.com/jupyterhub/binderhub/blob/908c4439f63b08744e2074e76dabb9883b1632e9/binderhub/builder.py#L297).

Then in `launch` we'd do something like:
```python
async def launch(self, kube, specific_quota=None):
  if specific_quota is not None:
    quota = specific_quota
  else:
    quota = self.settings.get('per_repo_quota')
  ...
```

**Comment by choldgraf** [comment]
ah ok - if we're alright adding extra kwargs to `launch` then I think it would be much more straightforward

**Comment by betatim** [comment]
I hadn't thought of the idea to make it a more general config, I like it!

I think we should consolidate `banned_specs` with this new key so we don't end up with two places that do similar stuff. It would be polite to provide some amount of time where people can keep using `banned_specs` (internally we translate it to a repo with a quota of zero?!) and get a warning that they should transition to the new way. Seems like the polite thing to do and makes mybinder.org ops team's life a little easier too.

Not a fan of the new name `spec_configuration_override`. I had to think a good moment about what it meant, what was likely to be the config found within it, etc. I'll suggest some names in the PR.

What do you think of using this as a way to configure limits for whole organisations (say all repos in the  `binder-examples` org)? It is possible right now, I like the idea of being able to do this and maybe it gives us an idea for how to name this config option.
