### ISSUE TITLE
Expose k8s events to users via the log

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#886]
Right now the feedback to users during the launch of a pod ends at "launching ...". This means there are long periods where "nothing" happens as far as a user can tell. We could pipe some of the kubernetes events related to the pod being launched to the user to give them something to look at and see progress.

In the background several things are happening like pulling the image, starting the init containers, etc.

Concretely the idea is to forward the events from https://gist.github.com/betatim/e8db23942746ec873c876fc4a2396b22#file-binder-launch-log-txt-L1-L11 to users.

cc @sgibson91

**Comment by betatim** [comment]
#852 is related.

**Comment by minrk** [comment]
JupyterHub 1.0 already provides an EventStream API for spawning servers, and KubeSpawner populates this with kubernetes events:

![progress](https://user-images.githubusercontent.com/151929/60509877-4832de00-9cce-11e9-92b5-9d367c4ca142.gif)

 We should be able to forward this to users pretty well.
