### ISSUE TITLE
Using contributing guidelines to test an auth configuration generates a 403 Forbidden redirect

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/binderhub#892]
Hi all,

I'm going to be hacking on an idea I have for allowing private repo access over the coming months (in an alan-turing-institute fork of BinderHub): see https://github.com/alan-turing-institute/the-turing-way/issues/291#issuecomment-508784717

In order to test the hack, I was following the [contributing guidelines](https://github.com/jupyterhub/binderhub/blob/master/CONTRIBUTING.md#one-time-installation) but modified for an auth configuration.

Specifically, the different commands I'm running are:

```
./testing/minikube/install-hub --auth  # step 7
python3 -m binderhub -f testing/minikube/binderhub_auth_config.py
```

I get a login page as expected and enter both username and password as "dummy" - but unfortunately this gives me a "403: Forbidden" redirection.

Any help on this appreciated, thank you! ✨

**Comment by sgibson91** [comment]
A related issue on pangeo: https://github.com/pangeo-data/pangeo/issues/156

Output:
```
$ python -m binderhub -f testing/minikube/binderhub_auth_config.py
[I 190722 14:43:40 app:642] BinderHub starting on port 8585
[I 190722 14:43:44 web:2246] 302 GET / (::1) 5.54ms
[W 190722 14:43:58 auth:972] oauth state '<redacted>' != None
[W 190722 14:43:58 web:1782] 403 GET /oauth_callback?code=<redacted>&state=<redacted> (127.0.0.1): oauth state does not match. Try logging in again.
[W 190722 14:43:58 web:2246] 403 GET /oauth_callback?code=<redacted>&state=<redacted> (127.0.0.1) 2.01ms
```

**Comment by sgibson91** [comment]
I think this error is due to the IP `127.0.0.1:8585` not being reachable. This is the OAuth callback URL here:

https://github.com/jupyterhub/binderhub/blob/137ec19b015ec84d0eb8d60b4ba2aa4ef3340ed7/testing/minikube/jupyterhub-helm-auth-config.yaml#L6

**Comment by sgibson91** [comment]
So after a lot of clearing of browsing history, deleting/rebuilding `minikube` and using an incognito window, I've now got the test binderhub accepting authentication.

Happy to close this, but also interested to know if anyone else had a similar issue?

**Comment by manics** [comment]
Closing as no-one else has responded.
