### ISSUE TITLE
Spawn Singularity containers

### ISSUE THREAD

**Issue by nuest** [jupyterhub/binderhub#893]
From a recent email on the Singularity mailing list:

> This will allow a K8s cluster to spawn Singularity containers natively rather than within a Docker instance.  
> 
> https://sylabs.io/guides/cri/1.0/user-guide/
> https://github.com/sylabs/singularity-cri

Which made me think: could/should BinderHub support Singularity? Is this rather an issue for JupyterHub?

**Comment by manics** [comment]
Assuming Singularity can run images built by Docker it's purely a JupyterHub issue. See discussion in https://github.com/jupyterhub/binderhub/issues/1318
