### ISSUE TITLE
Can I deploy mybinder over the infrastructure my server?

### ISSUE THREAD

**Issue by brayanrodbajo** [jupyterhub/binderhub#894]
Hi. Can I deploy mybinder over the infrastructure my server? I understand that when I launch a Jupyter Notebook in a Mybinder executable environment the infrastructure is provided by Mybinders servers. 

Thanks in advance.

**Comment by sgibson91** [comment]
The guide to building your own Binder service on a cluster/server you have access to live at [binderhub.readthedocs.io](https://binderhub.readthedocs.io/en/latest/) 🙂
