### ISSUE TITLE
Tell users when their launch requires a Docker pull

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#896]
Having a bunch of conversations with people at SciPy, it seems clear to me that we should find a way to tell people **why** their launch is taking so long, rather than just spinning the wheel and saying "launching server..."

Regardless of any kind of optimization for speed, I think simply having another log message that says "It's the first time this Binder has been run on this machine, please be patient while we load your environment" would make people a lot more understanding of why it takes longer.

**Comment by consideRatio** [comment]
Hmmm hmmm I wonder if we can, from a design perspective, make this something like a transition between key steps extracted from parts of the log other other places? Hmmm...

# Key step brainstorming

- __BUILD__
  Potentially with sub-sections, or reporting of key events extracted, like "Installing Python 3.7" or "Detected environment.yml - installing".
- __PUSH__
  Could perhaps show how large the image was, and how much we estimate need to actually push, as a lot of the docker layers probably are cached, or something like that?
- __PULL__
  I assume binderhub waits until the pod is considered ready before redirecting to it? This is still summarized as launching server right?
- __LAUNCHING SERVER__
  This is the phase where the user pod's container is actually starting up after the pulling of the docker image.
- __VISIT SERVER__
  We will leave the screen at this point.

**Comment by choldgraf** [comment]
Yeah I agree - I think that "launching server" is currently a few steps wrapped into one (docker pull, server launch, server redirect) but users don't have the ability to know which sub-step they're on

**Comment by betatim** [comment]
Related work https://github.com/jupyter/repo2docker/pull/727

**Comment by choldgraf** [comment]
yep that works for me!
