### ISSUE TITLE
Improve error reporting in the console

### ISSUE THREAD

**Issue by fedorov** [jupyterhub/binderhub#90]
I was starting a new mybinder, and I get “Failed” message and no details in the console.

To work around this, I tried “docker build” locally - the error was trivial: "Error response from daemon: LABEL must have two arguments”. However, it would be nice if I could see this error in the mybinder console too!

**Comment by willingc** [comment]
@fedorov I agree :-) We should have better error reporting and messages in the console. Updating the issue title.

**Comment by choldgraf** [comment]
We've made some improvements on these and also have a more general error handling thread here: https://github.com/jupyterhub/binderhub/issues/131 closing in favor of that
