### ISSUE TITLE
Improvements to the social media images

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#908]
Now that social media images work, a few things we could do to improve them:

- [x] Make the background of the image white so that it pops better
- [ ] Add a square image as well (I think that you can have both a rectangular and a square image and sites will choose the best one)
- [x] Should we make any changes to the tagline that is shared as well? I was thinking it’d be good to have the word “open” in there
- [ ] Get the full URL of the image automatically(copypasted from @betatim):

   > To include the host checkout 
   > https://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.static_url 
   > though we probably want to use 

   > https://github.com/jupyterhub/binderhub/blob/master/binderhub/app.py#L148-L158

   > as the "base" instead of the host on which BinderHub is actually running. In the case 
   > of our federation it would mean you'd get different URLs depending on which cluster 
   > you get sent to. I think.

**Comment by betatim** [comment]
My comment in Point 4 was about how to make the URL of the image absolute and reusing some config we already have. Tried to make the text better by editing your comment.

---

Another idea would be to generate the content of the image "on the fly" to include the name of the repo that is being launched. A bit like shields.io let's you generate custom shields by specifying things in the URL. I think that would be nice to make it easier to see where the link is going. At least on twitter I now just see a t.co link which doesn't tell me much about what link I am about to click.

In another iteration we could think about how to combine the binder logo with the social media image of a repository (on GitHub).

Thse would be a great task to help out with if you know design but are new to programming as the first steps would be about mock ups and finding a good design.

---

Another thing to discuss is should we show the large card or the small card? So card type `summary` vs `summary_large_image`.

---

Should there be more margin on the left and right side of our card image? Right now it feels like it is an image that got auto-cropped to me :-/

**Comment by choldgraf** [comment]
It seems like the margin point is an easy one to address...I can make a PR that shrinks this down a little bit and adds a white background.

re: summary vs. large summary, it sounded like most blogs recommended defaulting to the "larger" image because it is more common across other platforms. but happy to think about other perspectives there.

re: auto-generating the name, that sounds like a great idea although more complex than I can tackle in a weekend afternoon hack :-)

**Comment by betatim** [comment]
> auto generating images

Nods, this isn't a Sunday morning hack project, would make a nice first contribution though :) Probably wise to tackle it in two steps even: figure out what the image should look like (design) and then figure out the code to generate it on the fly.

> large vs small

Yeah dunno. I was thinking that we use a lot of space in people's timeline with our large image and there isn't a lot of info in it -> more polite to be smaller? *shrug* Not a high priority task.

Another thought: could we (easily) customise the message users see to include the repo name? What do I mean? In this card:

<img width="571" alt="Screen Shot 2019-07-29 at 17 14 21" src="https://user-images.githubusercontent.com/1448859/62059864-579d3c80-b224-11e9-86f7-76f2530a9f85.png">

there is a title, description and a hostname. We could expand the description to include "Try out $repolink without installing anything." or some such?

**Comment by choldgraf** [comment]
see https://github.com/jupyterhub/binderhub/pull/910 for some thoughts - good point re: title, I think it might be easier than I'd initially thought so if you want we can iterate on some quick ideas there

**Comment by choldgraf** [comment]
@betatim here's what the twitter box looks like now, what do you think?

![image](https://user-images.githubusercontent.com/1839645/62430852-e273b080-b6d6-11e9-88db-c8a403af7217.png)

(we can still choose twitter-specific images etc, just asking if you've got thoughts on the design to tack on to those changes)

**Comment by betatim** [comment]
Came here to post a screenshot of the same tweet and its card :) I think this is a pretty great v2!

Agree on "GitHub repository" being long, what do you think of something like "Run/Launch/some-verb github.com/<org>/<repo>@master" for the title? Even longer though ...

Undecided on the white space. Though I think "if in doubt add white space" is probably good advice for non designers like us.

Maybe for launch pages we keep the title as is and put something that tells the user what they will do if thye click the link into the description? I don't know why but I feel like telling people what will happen if they click the link is important/entices clicking. Might just be my old-man'ess that is angry and twitter, mailinglist, etc URLs being obfuscated via t.co or other trackers so I can't see where I am about to go (or if I already visited that page previously).

**Comment by choldgraf** [comment]
Sounds good - I'll bump the white space, and maybe play around with the wording a bit (I agree we shouldn't change the title much, and the description could use some changing).

Also just FYI apparently Facebook detects if the image is square and displays a different-sized card if so, so I don't think we need a twitter-specific image unless we *want* the big banner image on facebook

**Comment by choldgraf** [comment]
I think this is now fixed!
