### ISSUE TITLE
helm chart binderhub-0.2.0-409f200 contains bhub image with tag 0.2.0-9174211

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/binderhub#919]
Hi, I just deployed binderhub-0.2.0-409f200 on GESIS Binder, but I realised that it uses binderhub image with tag 0.2.0-9174211 instead of 0.2.0-409f200. I think something went wrong when https://github.com/jupyterhub/binderhub/pull/838 is merged or am I wrong? Actually it is only documentation update. So it shouldn't create a new chart actually?

If you point me the code where chart generation is done, I can also look at what is wrong.

**Comment by betatim** [comment]
We use https://github.com/jupyterhub/chartpress to make the charts and it is called in https://github.com/jupyterhub/binderhub/blob/10a3deeab94bdf584094bdcdb674f5c59a14d38b/ci/test-helm#L47 For some runs `$PUSH` contains the arguments that ask `chartpress` to publish stuff.

**Comment by bitnik** [comment]
I just ran `chartpress` locally

```bash
git checkout 9174211
chartpress
```

Output
```bash
$> git log -n 1 --pretty=format:%h -- . ../setup.py ../binderhub
$> git log -n 1 --pretty=format:%h -- images/image-cleaner chartpress.yaml
Skipping build for jupyterhub/k8s-image-cleaner:0.2.0-c56fb9e, it already exists
$> git log -n 1 --pretty=format:%h -- ../setup.py ../binderhub .. chartpress.yaml
Skipping build for jupyterhub/k8s-binderhub:0.2.0-9174211, it already exists
Updating binderhub/values.yaml: imageCleaner.image: {'repository': 'jupyterhub/k8s-image-cleaner', 'tag': '0.2.0-c56fb9e'}
Updating binderhub/values.yaml: image: {'repository': 'jupyterhub/k8s-binderhub', 'tag': '0.2.0-9174211'}
```

For helm chart tag it runs `git log -n 1 --pretty=format:%h -- . ../setup.py ../binderhub` which outputs `409f200` on commit `9174211` because last change is done in doc folder. But for image tag it runs `git log -n 1 --pretty=format:%h -- ../setup.py ../binderhub .. chartpress.yaml` with extra paths `.. chartpress.yaml` and it outputs `9174211`. That is the reason why image and helm chart tags are different. Those extra paths are added in `build_imagesmethod (https://github.com/jupyterhub/chartpress/blob/master/chartpress.py#L221-L224).

**Comment by bitnik** [comment]
This causes that 2 commits `409f200` and `9174211` are creating helm charts with same version but each chart has different image. And second chart override the first one.

**Comment by betatim** [comment]
Not a chartpress expert but sounds like we should use the same set of paths to decide if a new chart tag is needed and if a new image is needed. Naively the chart tag determination should be the OR of all image tag determinations: if anything is updated then the chart tag also has to be updated?

**Comment by bitnik** [comment]
I am not chartpress expert neither but I think the same. Image and chart should have same tags.

Should I move this issue to chartpress repo?

**Comment by betatim** [comment]
Sounds good. Or make a PR straight away?

**Comment by chicocvenancio** [comment]
I fail to see the problem with different image and chart tags, to me it seems expected that they won't match at times.

**Comment by bitnik** [comment]
@minrk what do you think?

Before I wanted to move this issue to chartpress repo because I thought there is a problem on chartpress side. But now I see that actually it takes all those paths from `chartpress.yaml` and also there is `contextPath` specified  for binderhub image:

https://github.com/jupyterhub/binderhub/blob/f565958c4d3921df1cdbd809a1b937f0b250e12a/helm-chart/chartpress.yaml#L1-L24

Maybe we should just add path `..` into `charts.paths`?

**Comment by betatim** [comment]
I think the problem isn't that sometimes the chart and image tag don't match but that we produce the same chart tag but with two different image tags in it.

At moment A create a new chart with tag `x` containing image tag `a1`.

At moment B (later in time) create a new chart (also) with tag `x` but now containing image tag `b1`. The chart tag should be `y` because its content changed.

That is how I read the bug report. I think the fact that we produce two charts with the same tag but different "content" is a bug.

**Comment by betatim** [comment]
> Maybe we should just add path `..` into `charts.paths`?

I think we should try this and see what happens. Can always later make a PR to chartpress that it automatically considers the union of `charts.paths` and the `paths` and `contextPath` of all the images.

**Comment by bitnik** [comment]
Closing this issue. I think this is solved by https://github.com/jupyterhub/binderhub/pull/927. We can re-open this issue if it happens again.

**Comment by bitnik** [comment]
This happened again. PR https://github.com/jupyterhub/binderhub/pull/1008 made only changes in doc folder. And chartpress created same chart version (binderhub-0.1.0-456.7e32ac0) with a new image (jupyterhub/k8s-binderhub:0.1.0-459.ede498d). 

Chart binderhub-0.1.0-456.7e32ac0 was already created after PR https://github.com/jupyterhub/binderhub/pull/1004 with image 
jupyterhub/k8s-binderhub:0.1.0-456.7e32ac0 and this is actually what is deployed on mybinder.org and GESIS Binder. Yesterday (after https://github.com/jupyterhub/binderhub/pull/1008) I was expecting a new PR to upgrade binderhub, but it didn't happened and this is how I realised the problem.

I don't have time to really investigate this but I think this is caused by https://github.com/jupyterhub/binderhub/pull/1004.

**Comment by consideRatio** [comment]
Oh! Chartpress should always produce a more modern chart version than chart image =/ that is a bug. I bet it relates to the contextPath of the binderhub image being broader than the chart's context itself somehow.

**Comment by bitnik** [comment]
I just looked at https://github.com/jupyterhub/binderhub/pull/1004 in more detail (and made a comment there). I think this is fixed in chartpress but the version we use here doesn't include that fix.

**Comment by bitnik** [comment]
Closing again by https://github.com/jupyterhub/binderhub/pull/1014
