### ISSUE TITLE
Add repoprovider for Figshare

### ISSUE THREAD

**Issue by nuest** [jupyterhub/binderhub#938]
Add support for (DOI-based) launching of Binders from [Figshare](https://en.wikipedia.org/wiki/Figshare). I'm not an active Figshare user myself (my :heart: belongs to Zenodo), but I imagine this could be interesting for many academic users.

- DOI prefix on Figshare is `10.6084` (there are some institutions with custom DOIs, asked my contact at Figshare)
- https://docs.figshare.com/ has the API docs
- existing applications/integrations documented at https://knowledge.figshare.com/apps

Just want to see if anyone would fancy working/collaborating on this.

**Comment by betatim** [comment]
A first step would be to add a content provider for Figshare to https://github.com/jupyter/repo2docker/tree/master/repo2docker/contentproviders. After that build the BinderHub integration needed here.

When doing the BinderHub work we need to have a little check that we find all the places where the content providers are mentioned. At the back of my mind I have "there is duplication" but not sure.

**Comment by nuest** [comment]
I've opened a PR for repo2docker.

I suggest to update the UI to just say "DOI" instead of Zenodo. Or should we also list all supported repositories explicitly?

![image](https://user-images.githubusercontent.com/1325054/64486636-ba282600-d22f-11e9-901d-3dfb271e684a.png)

**Comment by betatim** [comment]
Maybe we can extend/change the Zenodo provider in BinderHub to support Zenodo and Figshare with a view of it one day supporting all DOIs. In the UI that users see I'd still name the different sources with their own labels till we support a large fraction of possible DOIs.

Mostly to avoid the situation where people submit DOIs that we don't understand and that then lead to an error.

**Comment by nuest** [comment]
All DOIs generically will be impossible, because there is no API (AFAIK) connecting DOI and file retrieval. We will always need to match landing page URL to a specific code for downloading.

So :+1: on explicit names in the drop-down.
