### ISSUE TITLE
Use the Hub API to spawn users

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binderhub#94]
TODO list (mostly for min):

We should create a NullAuthenticator and use the Hub API to spawn users with tokens, rather than tmpauthenticator

- [x] demonstrate that this works (https://github.com/jupyterhub/jupyterhub/pull/1383)
- [x] create [NullAuthenticator](https://github.com/jupyterhub/nullauthenticator), which doesn't allow logging in at all
- [x] use the Hub API to spawn servers and retrieve tokens instead of redirect to `/tmplogin`
- [x] support deleting users in cull_idle_servers, rather than just stopping servers https://github.com/jupyterhub/jupyterhub/pull/1380
- [x] take a pass on errors on the JupyterHub side (#91 covers lots of errors on the binderhub side, but not failure to run after the fact)
- [x] add token for binder to the Hub via (non-managed) services config
- [x] validate images by running `jupyterhub-singleuser --version` after build

**Comment by yuvipanda** [comment]
Most of these have just been deployed!

**Comment by minrk** [comment]
#135 / #142 deals with failure to launch by including launch errors in the event stream. The image validation is also less significant, since now we only assume that the image is a web server, and not anything else.

**Comment by yuvipanda** [comment]
We do this now!
