### ISSUE TITLE
Unquote displayed link for "pure git" repository

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#942]
When a user launches a "pure git" repository we show the following on the build page:

<img width="895" alt="Screenshot 2019-09-01 at 16 31 22" src="https://user-images.githubusercontent.com/1448859/64077986-1641f600-ccd6-11e9-9c42-49c137802b30.png">

It should display something more like "Starting repository: https://gitlab.kwant-project.org...." instead. To reproduce this open https://mybinder.org/v2/git/https%3A%2F%2Fgitlab.kwant-project.org%2Fqt%2Flocalization_landscape.git/master?urlpath=lab/tree/index.ipynb

The place to change this is probably in https://github.com/jupyterhub/binderhub/blob/master/binderhub/repoproviders.py#L219 at the location where the value to display is passed to the template. Or maybe we need to do this in the template itself. Depends a bit on how the value passed into the template is used.

To work on this you need to know (or teach yourself) a little bit about URL quoting and Jinja templates.

**Comment by OrthoDex** [comment]
Hi! Binder user here, can I take this up?

**Comment by souvik3333** [comment]
Hi, Is anyone working on this?
