### ISSUE TITLE
iframes in markdown cells are empty

### ISSUE THREAD

**Issue by ingodahn** [jupyterhub/binderhub#943]
iframes in markdown cells, containing external web pages, are rendered as a blank html page, The external content is correctly shown in nbviewer.
See https://github.com/sagemath/sage-binder-env/issues/7 for an example

**Comment by betatim** [comment]
Do you get an error message in your browser's console (open the developer tools to see the console)?

**Comment by ingodahn** [comment]
The console doesn't show any error message. You may checkout a minimal
example at https://github.com/ingodahn/frametest.git.
Inspection of the displayed iframe shows

[image: image.png]

Am Mi., 4. Sept. 2019 um 09:15 Uhr schrieb Tim Head <
notifications@github.com>:

**Comment by betatim** [comment]
For me the console shows an error that the content security policy doesn't allow loading content from that source.

**Comment by ingodahn** [comment]
I see it now too as a sanitizer message. I noted the same behaviour with an
embedded youtube video. Is this a binder policy (it seems to be in
security.js) and can it be changed?

Am Mi., 4. Sept. 2019 um 13:37 Uhr schrieb Tim Head <
notifications@github.com>:

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
