### ISSUE TITLE
Replacement for beta.mybinder.org ?

### ISSUE THREAD

**Issue by TrakJohnson** [jupyterhub/binderhub#95]
Is there any replacement for https://beta.mybinder.org/ ? Or is there any easy way to host the docker images generated by repo2docker ?

**Comment by choldgraf** [comment]
hey - I'm a bit confused by what you mean. How do you mean `replacement`? Could you clarify?

**Comment by TrakJohnson** [comment]
@choldgraf I didn't get to use it, but it looks like the website would take a github link as input, generate the jupyterhub server for you and then give a link, where you can edit the jupyter files. I have no server to be able to host what binderhub offers so this looked like a nice solution.

**Comment by choldgraf** [comment]
the idea of binderhub is to connect a running jupyterhub service with a tool that auto-builds docker images (from github repositories) and serves them to users through the URL. We've got `beta.mybinder.org` as a public service and a demonstration of the technology, but we encourage people to set up their own BinderHubs (which is a specific configuration of JupyterHub, see binderhub.readthedocs.io) if they'd like to create websites like `beta.mybinder.org` that run on their on cloud setup.

**Comment by TrakJohnson** [comment]
@choldgraf Ahh ok so it was only for demo purposes.. I guess I'll have to figure out how to setup one then. Thanks !

**Comment by choldgraf** [comment]
yep - we've tried to document this so that it's as easy as possible. Follow the instructions to set it up on AWS/google cloud/etc and let us know if something isn't clear, since those docs are still in early stages!
