### ISSUE TITLE
Binderhub is not installing dependencies in Pipfile

### ISSUE THREAD

**Issue by koldLight** [jupyterhub/binderhub#955]
Hi,

I'm having `ModuleNotFoundError` errors in my notebooks for dependencies that are specified in `Pipfile` and `Pipfile.lock`, in my own binderhub server. I've done the setup using the last available version: `0.2.0-fbbc302`. The same repository is being built OK if I use mybinder.org instead of my own server.

I tried also with a simple example, https://github.com/binder-examples/pipfile, and also fails with `ModuleNotFoundError` in my own server.

The build logs shows that repo2docker is using `PythonBuildPack` instead of expected `PipfileBuildPack`:

In my binderhub server (failing build, using `PythonBuildPack`):

```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerscfh47y2'...
HEAD is now at 4005a76 Initial commit
Building conda environment for python=3.7Using PythonBuildPack builder
Building conda environment for python=3.7Building conda environment for python=3.7Step 1/42 : FROM buildpack-deps:bionic
...
```

In mybinder.org server (successful build, using `PipfileBuildPack`):

```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockers48643rz'...
HEAD is now at 4005a76 Initial commit
Building conda environment for python=3.7Using PipfileBuildPack builder
Building conda environment for python=3.7Building conda environment for python=3.7Step 1/54 : FROM buildpack-deps:bionic
...
```

Running last version of `repo2docker` locally (also successful build, using `PipfileBuildPack`):

```
Picked Git content provider.
Cloning into '/var/folders/1j/q3gk1w3j4l7_64pf1k8gf9wr0000gn/T/repo2dockeralsz1d_c'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
Using PipfileBuildPack builder
Step 1/54 : FROM buildpack-deps:bionic
```

Any idea why my own binderhub server is not using the `Pipfile` in the project?

**Comment by consideRatio** [comment]
Hmmmm... Perhaps there is a difference in the repo2docker version used? What decides this version? Is it based on what is installed within a binderhub image? Do you have a custom binderhub image / or an omd one explicitly specified one in your binderhub config.yaml for your binderhub deployment?

**Comment by betatim** [comment]
Could you visit `https://yourbinderhub.com/versions` and post the output here? It should look something like https://mybinder.org/versions

**Comment by koldLight** [comment]
Thanks for your quick response!

I did some research about that. It looks like you can override the repo2docker image in the `config.yaml` of binderhub.

In my previous `config.yaml`, I didn't try to set any specific version of repo2docker (I followed the tutorial [Zero to BinderHub](https://binderhub.readthedocs.io/en/latest/create-cloud-resources.html) using Google Cloud and Google Container Registry). It was:

```
config:
  BinderHub:
    use_registry: true
    image_prefix: gcr.io/<my-gcp-project>/binder-dev-
    hub_url: http://<my-ip>
```

In my new `config.yaml`, I specified the last version of `repo2docker` by doing:

```
config:
  BinderHub:
    use_registry: true
    image_prefix: gcr.io/<my-gcp-project>/binder-dev-
    hub_url: http://<my-ip>
    build_image: jupyter/repo2docker:0.10.0-59.g649a2c6
```

And now it's building successfully (reading the Pipfile) my repos. Build logs now show `Using PipfileBuildPack builder` and there's no more `ModuleNotFoundError` errors.

I don't know why the last available version of binderhub installs, it seems, an old repo2docker dependency, but at least there's a way to override it.

Thanks

**Comment by betatim** [comment]
The default version that BinderHub uses by [default is defined here](https://github.com/jupyterhub/binderhub/blob/master/binderhub/app.py#L359-L365). It is now two releases behind. A PR to update it to 0.10.0 would be great.

Maybe even a section in the guide telling people where to change it and that mybinder.org usually runs "the very very latest commit on `master` so you can too".

**Comment by koldLight** [comment]
@betatim my versions before specifying `build_image`:

```
{"builder": "jupyter/repo2docker:0.8.0", "binderhub": "0.1.0+380.g3fe8143.dirty"}
```

And after that:

```
{"builder": "jupyter/repo2docker:0.10.0-59.g649a2c6", "binderhub": "0.1.0+380.g3fe8143.dirty"}
```

Do you want me to help by doing the suggested PR?

**Comment by betatim** [comment]
> Do you want me to help by doing the suggested PR?

That would be great!
