### ISSUE TITLE
Zenodo support requires repo2docker 0.10.0 but default is 0.8.0

### ISSUE THREAD

**Issue by enolfc** [jupyterhub/binderhub#957]
Testing binderhub deployment with current version (0.2.0-99af80d), it uses repo2docker by default 0.8.0 which does not have Zenodo support. However the GUI will show the option so builds will fail whenever used. 

Not sure if the default should be upgraded or at least the issue should be documented.

**Comment by betatim** [comment]
Closing in favour of #941
