### ISSUE TITLE
Failed to load css resources

### ISSUE THREAD

**Issue by joshuazeltser** [jupyterhub/binderhub#959]
I am trying to install and run an nbextension i created on binder to allow users to try out its functionality. I have been able to install the nbextension, but not of the css files are able to load. I get the following errors: 
![Screenshot 2019-09-22 at 19 32 05](https://user-images.githubusercontent.com/17781896/65392727-b89e4800-dd6f-11e9-994a-8df9b01f1d0a.png)

Does anyone have any idea how I could fix this? 

My repository can be found at: https://github.com/uclixnjupyternbaccessibility/notebook-examples
My binder can be found at: https://mybinder.org/v2/gh/uclixnjupyternbaccessibility/notebook-examples/master

Thanks!

**Comment by pablobernabeu** [comment]
I have the same issue. 

It arises in the Shiny app that's located inside the 'Shiny app' folder.

https://mybinder.org/v2/gh/pablobernabeu/Modality-exclusivity-norms-747-Dutch-English-replication/master?urlpath=rstudio

**Comment by betatim** [comment]
Do you know what generates the links for your extension?

I started the binder link you provided and this is the URL that is being loaded and gives 404:
https://hub.gke.mybinder.org/user/nbextensions/accessibility_toolbar/spell_checker/spellchecker.css?v=20190923140557

It should be something like:
https://hub.gke.mybinder.org/user/uclixnjupyternb-tebook-examples-ztsimprz/nbextensions/accessibility_toolbar/spell_checker/spellchecker.css?v=20190923140557

I suspect that somewhere the links are generated without taking into account that the notebook server is running as part of a JupyterHub.

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
