### ISSUE TITLE
[feature request] Shiny interface deployed from RMarkdown script

### ISSUE THREAD

**Issue by pablobernabeu** [jupyterhub/binderhub#961]
Currently, running a Binder repo into the Shiny app interface (`?urlpath=shiny`) requires having a ui.R and a server.R script. I would like to make a feature request to enable a slightly different form of a Shiny app which is known as [Flexdashboard](https://rmarkdown.rstudio.com/flexdashboard/). 

A Flexdashboard is based on a single Rmarkdown (.rmd) script, which may have any name. In RStudio, the app is run through 'Run Document'. In the R console, it's run with `rmarkdown::run('myfile.Rmd')`.

An example may be found [in this repo](https://mybinder.org/v2/gh/pablobernabeu/Modality-exclusivity-norms-747-Dutch-English-replication/master?urlpath=rstudio), inside the 'Shiny-app' folder. Currently, the app can be run with the 'Run Document' button in RStudio, but [not through the `?urlpath=shiny` interface](https://mybinder.org/v2/gh/pablobernabeu/Modality-exclusivity-norms-747-Dutch-English-replication/master?urlpath=shiny/Shiny-app).

Thank you very much

**Comment by choldgraf** [comment]
hey @pablobernabeu - thanks for the info, I think the fix for this would be in repo2docker, so I've opened up an issue with this issue in it here:

https://github.com/jupyter/repo2docker/issues/799

want to take the conversation over there?
