### ISSUE TITLE
iPhone and iPad accessebility

### ISSUE THREAD

**Issue by alperyilmaz** [jupyterhub/binderhub#970]
hi,
I'm teaching python as undergraduate level course. I'm using binderhub (kudos btw) and my students with Android phones can open existing ipynb files however iPhone and iPad users cannot open a file after double tapping.
Is there a trick or workaround for this problem?
Thanks.

**Comment by betatim** [comment]
No idea and no access to an iPhone :-/. The https://github.com/jupyter/notebook/ repo might be a better place to ask this question because that is the file browser you see when you launch a binder.

**Comment by betatim** [comment]
I see you made a new issue in the notebook repo so closing this one. Thanks for helping out 😀
