### ISSUE TITLE
Helm install fails

### ISSUE THREAD

**Issue by ltetrel** [jupyterhub/binderhub#976]
Hi, 

We are setupping a new binderhub. We successfully did it last May 2019, but when we tried recently it fails at the [helm configuration step](https://binderhub.readthedocs.io/en/latest/create-cloud-resources.html#initialization) : 
```
Error: error installing: the server could not find the requested resource
```
Following [this issue](https://github.com/helm/helm/issues/6374), it seems to be related to helm `v2.14.0` and they should fix it in `v2.15.0` release, or we can still use kubernetes < `v1.16.0`

thanks,

**Comment by manics** [comment]
There are reported problems with kubespawner (used by binderhub) on k8s 1.16: https://github.com/jupyterhub/kubespawner/issues/354

So even if you fix the helm issue it's probably safer to use an older k8s for now.

**Comment by ltetrel** [comment]
Which version of k8s do you recommend ?

**Comment by jhamman** [comment]
We're running Kubernetes v1.13.10-gke.0 for binder.pangeo.io.

**Comment by ltetrel** [comment]
We are running `v1.14.2` on https://github.com/neurolibre but maybe more recent version are also safe.

**Comment by jhamman** [comment]
I tend to look at what z2jh is testing against before upgrading: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/50e5599ce99b8b7ee8f21564d7a49accc5222541/.travis.yml#L19-L22. Currently, they are still on <=1.13.

**Comment by ltetrel** [comment]
Thanks for your feedback @jhamman

**Comment by betatim** [comment]
Looks like this was resolved.
